### ISSUE TITLE
[ISSUE]: dotnet publish: '0.0.1-abc_def.1+1' is not a valid version string

### ISSUE THREAD

**Issue by HenrikRoosKpa** [GitTools/GitVersion#4136] opened 2024-08-05 09:21 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6

### Operating system

Windows

### What are you seeing?

dotnet publish show an error: '0.0.1-abc_def.1+1' is not a valid version string, when branch name contains _.

### What is expected?

FullSemVer generate an SemVer 2.0 string.

### Steps to Reproduce

```powershell
New-Item -Path test -Type Directory
cd test
git init
dotnet new web -o src/my-app
git add .
git commit -m "add my-app"
git checkout -b features/abc_def
dotnet-gitversion /showvariable FullSemVer
dotnet publish src/my-app -p:Version=0.0.1-abc_def.1+1 -o out
```

### Output log or link to your CI build (if appropriate).

```shell
dotnet publish src/my-app -p:Version=0.0.1-abc_def.1+1 -o out
  Determining projects to restore...
C:\Program Files\dotnet\sdk\8.0.303\NuGet.targets(169,5): error : '0.0.1-abc_def.1+1' is not a valid version string. (Parameter 'value') [C:\git\test\src\my-app\my-app.csproj]
```

**Comment by arturcic** [comment] 2024-08-05 10:44
I think it's related to https://github.com/GitTools/GitVersion/pull/4135

**Comment by arturcic** [comment] 2024-08-05 11:22
I will close this issue as duplicate of #4110

**Closed by arturcic** 2024-08-05 11:22 UTC
Labels: needs triage

**Comment by HenrikRoosKpa** [comment] 2024-08-05 11:24
Thanx @arturcic

**Comment by HenrikRoosKpa** [comment] 2024-08-05 14:28
Is verified by our corporate Azure DevOps pipelines. Version 6.0.1 fix this bug.
