### ISSUE TITLE
LibGit2Sharp.Core.NativeMethods cannot be initialized: Unable to load shared library 'git2-7ce88e6' or one of its dependencies

### ISSUE THREAD

**Issue by nZeus** [GitTools/GitVersion#1852] opened 2019-10-10 21:58 UTC
Trying to use GitVersion dotnet tool with [.net core 3 sdk docker image](https://hub.docker.com/_/microsoft-dotnet-core-sdk/) that runs on [GitLab Shared Runner](https://docs.gitlab.com/ee/user/gitlab_com/#shared-runners) (which is CoreOS).

The `5.0.2-beta.1+95` (contains https://github.com/GitTools/GitVersion/pull/1849) throws this exception:

```
Using Docker executor with image mcr.microsoft.com/dotnet/core/sdk:3.0 ...
Pulling docker image mcr.microsoft.com/dotnet/core/sdk:3.0 ...
Using docker image sha256:4422e7fb740c14af167b232a7b485d60a1a696a6507ee75e712817bd27dacdb5 for mcr.microsoft.com/dotnet/core/sdk:3.0 ...
...

$ dotnet tool restore
Tool 'gitversion.tool' (version '5.0.2-beta1.95') was restored. Available commands: dotnet-gitversion

Restore was successful.

$ dotnet tool run dotnet-gitversion /updateassemblyinfo /ensureassemblyinfo
INFO [10/10/19 18:18:06:48] Working directory: /builds/nZeus/my-project/sources
INFO [10/10/19 18:18:06:49] IsDynamicGitRepository: False
ERROR [10/10/19 18:18:06:51] An unexpected error occurred:
System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'git2-7ce88e6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-7ce88e6: cannot open shared object file: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_buf_dispose(GitBuf buf)
   at LibGit2Sharp.Core.Proxy.git_buf_dispose(GitBuf buf)
   at LibGit2Sharp.Core.Handles.GitBuf.Dispose()
   at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)
   at LibGit2Sharp.Core.Proxy.git_repository_discover(FilePath start_path)
   at LibGit2Sharp.Repository.Discover(String startingPath)
   at GitVersion.GitPreparer.GetProjectRootDirectory() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 160
   at GitVersion.Configuration.ConfigFileLocator.Verify(GitPreparer gitPreparer, IFileSystem fileSystem) in D:\a\1\s\src\GitVersionCore\Configuration\ConfigFileLocator.cs:line 56
   at GitVersion.Program.VerifyConfiguration(Arguments arguments, IFileSystem fileSystem) in D:\a\1\s\src\GitVersionExe\Program.cs:line 155
   at GitVersion.Program.VerifyArgumentsAndRun() in D:\a\1\s\src\GitVersionExe\Program.cs:line 101
INFO [10/10/19 18:18:06:52] 
INFO [10/10/19 18:18:06:52] Attempting to show the current git graph (please include in issue): 
INFO [10/10/19 18:18:06:52] Showing max of 100 commits
```

**Comment by arturcic** [comment] 2019-10-11 07:08
as I mentioned https://github.com/GitTools/GitVersion/issues/1824#issuecomment-540716967 the debian 10 is not yet supported. I'll need to think of a way to make it supported

**Comment by nZeus** [comment] 2019-10-11 07:20
what do you think about the idea of having another version of GitVersion tool with that dependency included or ilmerged?

GitLab CI runners are based on CoreOS and I cannot find a way to install packages there :(

**Comment by arturcic** [comment] 2019-10-11 07:23
Are you able to run Docker images there? is so I'd recommend to use the image https://hub.docker.com/layers/gittools/gitversion/5.0.2-beta1-95-linux-debian-9-netcoreapp3.0/images/sha256-ba496f1885415be1bcac0256f0b1af4b6d1ab48db2d1de6116ce6e15462cf419

**Comment by nZeus** [comment] 2019-10-17 22:09
This image throws a different error:

```
ERROR [10/17/19 22:01:58:10] An unexpected error occurred:
System.IO.DirectoryNotFoundException: Can't find the .git directory in sh
   at GitVersion.GitPreparer.GetProjectRootDirectory() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 165
   at GitVersion.Configuration.ConfigFileLocator.Verify(GitPreparer gitPreparer, IFileSystem fileSystem) in D:\a\1\s\src\GitVersionCore\Configuration\ConfigFileLocator.cs:line 56
   at GitVersion.Program.VerifyConfiguration(Arguments arguments, IFileSystem fileSystem) in D:\a\1\s\src\GitVersionExe\Program.cs:line 155
   at GitVersion.Program.VerifyArgumentsAndRun() in D:\a\1\s\src\GitVersionExe\Program.cs:line 101
```

**Comment by Techcadia** [comment] 2019-10-18 00:01
Since others will come here looking for the same thing for alpine-3.9 it should be mentioned that alpine 3.9 was only supported in the most recent published packages. 5.0.2.beta+

**Comment by jburger** [comment] 2019-11-08 08:11
Also spotted on Ubuntu 19.04+libcurl4

**Comment by SignumPL** [comment] 2019-11-13 18:50
When will GitVersion be supported on Debian 10?

**Comment by mprokopov** [comment] 2019-11-22 16:19
It seems guys have figured out a root cause https://github.com/libgit2/libgit2sharp/pull/1741

See this discussion https://github.com/libgit2/libgit2sharp/pull/1732

I guess now it is required a new release to be built.

**Comment by deadman2000** [comment] 2019-11-30 09:43
Temporary solution for Docker:
```
export LD_LIBRARY_PATH=/root/.nuget/packages/gitversion.tool/5.1.2/tools/netcoreapp3.0/any/runtimes/debian.9-x64/native/
```

**Comment by arturcic** [comment] 2019-11-30 11:45
@deadman2000 thanks for sharing

**Comment by robertcoltheart** [comment] 2019-12-02 08:48
Can we get a fix for this? We are struggling with this issue as well under amazon linux.

**Comment by asbjornu** [comment] 2019-12-02 09:22
@robertcoltheart, doesn't @deadman2000's `LD_LIBRARY_PATH` solution work for you?

**Comment by robertcoltheart** [comment] 2019-12-03 04:49
@asbjornu No, the above export command doesn't seem to help, we are still getting the same error

**Comment by deadman2000** [comment] 2019-12-03 08:32
@robertcoltheart  If you use GitVersion as tool, this `Dockerfile` should helps:
```
ARG DOTNET_SDK=3.0
FROM mcr.microsoft.com/dotnet/core/sdk:$DOTNET_SDK

ENV PATH="${PATH}:/root/.dotnet/tools"

ENV GITVERSION_VERSION=5.1.2
RUN dotnet tool install -g GitVersion.Tool --version $GITVERSION_VERSION
ENV LD_LIBRARY_PATH=/root/.dotnet/tools/.store/gitversion.tool/${GITVERSION_VERSION}/gitversion.tool/${GITVERSION_VERSION}/tools/netcoreapp3.0/any/runtimes/debian.9-x64/native/
```

**Comment by robertcoltheart** [comment] 2019-12-03 11:29
Hmm, we don't use docker currently for the EC2 instances. Will investigate further if the above can be adapted for our use case or not.

**Comment by robertcoltheart** [comment] 2019-12-04 02:26
Doesn't look like this will work for us. For clarification, we are using `linux-x64` on Amazon linux AMI 2. Not debian. Any solution on the horizon that will fix this without having to set exports or hack scripts together to make it work?

**Comment by robertcoltheart** [comment] 2019-12-04 09:26
The solution that worked for us was to bump `LibGit2Sharp` to version `0.27.0-preview-0034` and the native binaries version to `2.0.298`. For now we are building this locally and hosting our own binaries, but it would be great if this repo could be updated similarly so that we can use the 'official' sources.

**Comment by artur-stolear-technosoft** [comment] 2019-12-04 09:35
@robertcoltheart thanks for sharing, will take that into consideration

**Comment by arturcic** [comment] 2019-12-04 09:36
@robertcoltheart thanks for sharing, will take that into consideration

**Comment by phatcher** [comment] 2020-02-07 16:37
This was working on Azure DevOps prior to Christmas using the LIBPATH fix, but it's broken now - anyone have a fix?

**Comment by robertcoltheart** [comment] 2020-02-08 12:06
We built our own version of `GitVersion` internally against 0.27.0-preview of LibGit2Sharp. Less than ideal but 🤷‍♂.

**Comment by asbjornu** [comment] 2020-02-10 10:34
What you're saying is that `0.27.0-preview` of LibGit2Sharp fixes the problem, @robertcoltheart? If so, I wonder about the ETA of `0.27.0` and if it's too far into the future, we should perhaps upgrade to the preview in GitVersion?

**Comment by robertcoltheart** [comment] 2020-02-10 10:50
Yes it fixed our use case which was AWS Linux

**Comment by robertcoltheart** [comment] 2020-05-04 06:21
Is there any official way to support this? We're using our internal version but it would be nice to have this properly fixed.

**Comment by arturcic** [comment] 2020-05-04 06:38
@robertcoltheart , currently we are almost ready to release 5.3.0. I would prefer to use a stable version of LibGit2Sharp in this release instead of using a preview. But depending on the response https://github.com/libgit2/libgit2sharp/pull/1741#issuecomment-623280758 we might consider using the preview as well

**Comment by bording** [comment] 2020-05-04 16:51
I commented on the the LibGit2Sharp issue as well, but I don't think we'll be doing a non-preview release any time soon. The work in that PR is mostly a patch to a larger problem that is still being worked on. Even using the preview release that includes that change, there are more Linux distros out there supported by .NET Core that won't work with LibGit2Sharp.

The real fix is to move the support for https into managed code, and that work is ongoing, though progressing slowly.

**Comment by robertcoltheart** [comment] 2020-05-05 07:47
Thanks @bording. @arturcic any chance of having a preview version of GitVersion that uses the 0.27 preview of Libgit2sharp? 😄 At least that will solve our immediate issue, which is custom building a custom fork of Gitversion and hosting it on a custom feed internally.

**Comment by arturcic** [comment] 2020-05-05 07:51
I think I will update Libgit2Sharp to preview version and will release it as 5.3.2

**Closed** 2020-05-05 08:26 UTC
Labels: improvement

**Comment by nZeus** [comment] 2020-05-05 20:44
Thank you for the update!

Today I tried version 5.3.2, but it doesn't work, but no libgit error anymore: 
![image](https://user-images.githubusercontent.com/2727326/81114158-c4670500-8f21-11ea-82bb-429aafbb4809.png)

Probably it's a different issue. I'll try to investigate. Do you have any ideas about why it can fail and why it doesn't produce any output?

**Comment by nZeus** [comment] 2020-05-07 14:15
Created a separate story for the described behavior - https://github.com/GitTools/GitVersion/issues/2260

**Comment by gitfool** [comment] 2020-09-06 03:57
@nZeus the GitLab shared Linux runners are now based on Debian 10, so I got GitVersion to work using @deadman2000's [workaround](https://github.com/GitTools/GitVersion/issues/1852#issuecomment-559936967) above, just before I run my [Cake](https://github.com/cake-build/cake) build. See https://github.com/gitfool/Cake.Dungeon/commit/0655e23b94507896637f21d5636bfd8640542e75.
