### ISSUE TITLE
[ISSUE]: System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by thomhurst** [GitTools/GitVersion#4198] opened 2024-09-03 12:00 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.02

### Operating system

N/A

### What are you seeing?
```
System.NotImplementedException: The method or operation is not implemented.
   at GitVersion.VersionCalculation.MainlineVersionStrategy.IterateOverCommitsRecursive(IEnumerable`1 commitsInReverseOrder, MainlineIteration iteration, IBranch targetBranch, String targetLabel, ILookup`2 taggedSemanticVersions, HashSet`1 traversedCommits) in /_/src/GitVersion.Core/VersionCalculation/VersionSearchStrategies/MainlineVersionStrategy.cs:line 242
   at GitVersion.VersionCalculation.MainlineVersionStrategy.GetBaseVersions(EffectiveBranchConfiguration configuration)+MoveNext() in /_/src/GitVersion.Core/VersionCalculation/VersionSearchStrategies/MainlineVersionStrategy.cs:line 105
   at GitVersion.VersionCalculation.NextVersionCalculator.<>c__DisplayClass14_0.<<GetNextVersions>g__GetNextVersionsInternal|0>d.MoveNext() in /_/src/GitVersion.Core/VersionCalculation/VersionCalculators/NextVersionCalculator.cs:line 264
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.VersionCalculation.NextVersionCalculator.GetNextVersions(IBranch branch, IGitVersionConfiguration configuration) in /_/src/GitVersion.Core/VersionCalculation/VersionCalculators/NextVersionCalculator.cs:line 239
   at GitVersion.VersionCalculation.NextVersionCalculator.CalculateNextVersion(IBranch branch, IGitVersionConfiguration configuration) in /_/src/GitVersion.Core/VersionCalculation/VersionCalculators/NextVersionCalculator.cs:line 158
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in /_/src/GitVersion.Core/VersionCalculation/VersionCalculators/NextVersionCalculator.cs:line 53
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in /_/src/GitVersion.Core/Core/GitVersionCalculateTool.cs:line 45
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in /_/src/GitVersion.App/GitVersionExecutor.cs:line 66
```

### What is expected?

No exception and to produce a SemVer.

### Steps to Reproduce

This has only just starting happening so I'm not sure what's caused it.

### Output log or link to your CI build (if appropriate).

```shell
https://github.com/thomhurst/TUnit/actions/runs/10682299901/job/29607811542
```

**Comment by HHobeck** [comment] 2024-09-03 12:06
Please analyse your issue in more detail and decribe what cause this error. Also add steps to reproduce.

**Comment by thomhurst** [comment] 2024-09-03 12:08
> Please analyse your issue in more detail and decribe what cause this error. Also add steps to reproduce.

I don't know what's causing it. It only started happening today

**Comment by HHobeck** [comment] 2024-09-03 12:13
But if you don't invest the time to find the root cause, who will do it for you?

I think this is a duplicate of:
- #4056

**Closed** 2024-09-03 12:13 UTC
Labels: missing-steps-to-reproduce, needs triage
