### ISSUE TITLE
Discrepencies between GitVersion CommandLine and GitVersionTask

### ISSUE THREAD

**Issue by jonathannaim** [GitTools/GitVersion#460] opened 2015-06-09 09:12 UTC
Hello,

I've just upgraded to latest version 3.0.0-beta0003 for both.

When running GitVersionTask during the build I get the following error message on a release branch : 
```
35>MSBUILD : warning : Could not determine assembly version: Path '****' doesn't point at a valid Git repository or workdir.
```

Whereas when I run GitVersion I get correct information:
```
C:\Users\Jonathan\Source\Repos\****>gitversion
{
  "Major":0,
  "Minor":1,
  "Patch":0,
  "PreReleaseTag":"beta.1",
  "PreReleaseTagWithDash":"-beta.1",
  "BuildMetaData":2,
  "FullBuildMetaData":"2.Branch.release/0.1.0.Sha.0eabeb44abe4b64d35cb09c569c01f8b93c52a50",
  "MajorMinorPatch":"0.1.0",
  "SemVer":"0.1.0-beta.1",
  "LegacySemVer":"0.1.0-beta1",
  "LegacySemVerPadded":"0.1.0-beta0001",
  "AssemblySemVer":"0.1.0.0",
  "FullSemVer":"0.1.0-beta.1+2",
  "InformationalVersion":"0.1.0-beta.1+2.Branch.release/0.1.0.Sha.0eabeb44abe4b64d35cb09c569c01f8b93c52a50",
  "BranchName":"release/0.1.0",
  "Sha":"0eabeb44abe4b64d35cb09c569c01f8b93c52a50",
  "NuGetVersionV2":"0.1.0-beta0001",
  "NuGetVersion":"0.1.0-beta0001",
  "CommitDate":"2015-06-09"
}
```
Any idea what's going on? Could it be a setup issue on my side?

Thanks!

Jonathan

**Comment by JakeGinnivan** [comment] 2015-06-09 10:29
More likely I have broken the task :disappointed: 

Will see if I can get beta.4 out tonight which fixes this issue.

**Comment by jonathannaim** [comment] 2015-06-09 10:33
Wow Thanks! 

I take the opportunity to tell you guys that GitVersion is GOLD!

**Comment by Sacrelicious** [comment] 2015-06-12 14:59
Is there any update on getting an updated beta out?

**Comment by JakeGinnivan** [comment] 2015-06-12 15:00
Sorry, I have not had a chance to fix this. Any help/pr's appreciated, otherwise will get to it as soon as I can (probably tomorrow)

**Comment by Sacrelicious** [comment] 2015-06-12 15:48
I may have time to try to get a PR for this. It sounded like you had an idea of what was going on, if so, could you point me in the direction of a good place to start debugging?

**Comment by JakeGinnivan** [comment] 2015-06-12 16:23
I don't know what the issue is, but I made a lot of changes around that area and we don't have that many tests.

**Comment by JakeGinnivan** [comment] 2015-06-17 17:51
Will be fixed in beta4

**Closed** 2015-06-25 21:46 UTC
