### ISSUE TITLE
Could not determine assembly version: System.Runtime.InteropServices.MarshalDirectiveException: StrictFilePathMarshaler must be used on a FilePath.

### ISSUE THREAD

**Issue by oSilas** [GitTools/GitVersion#899] opened 2016-06-12 04:26 UTC
2>MSBUILD : warning : WARN [06/12/16 12:22:11:71] Could not determine assembly version: System.Runtime.InteropServices.MarshalDirectiveException: StrictFilePathMarshaler must be used on a FilePath.
2>MSBUILD : warning :    在 LibGit2Sharp.Core.StrictFilePathMarshaler.MarshalManagedToNative(Object managedObj)
2>MSBUILD : warning :    在 System.StubHelpers.MngdRefCustomMarshaler.ConvertContentsToNative(IntPtr pMarshalState, Object& pManagedHome, IntPtr pNativeHome)
2>MSBUILD : warning :    在 LibGit2Sharp.Core.NativeMethods.git_repository_discover(GitBuf buf, FilePath start_path, Boolean across_fs, FilePath ceiling_dirs)
2>MSBUILD : warning :    在 LibGit2Sharp.Core.Proxy.<>c__DisplayClass39.<git_repository_discover>b__38(GitBuf buf)
2>MSBUILD : warning :    在 LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)
2>MSBUILD : warning :    在 LibGit2Sharp.Core.Proxy.git_repository_discover(FilePath start_path)
2>MSBUILD : warning :    在 LibGit2Sharp.Repository.Discover(String startingPath)
2>MSBUILD : warning :    在 GitVersion.GitPreparer.GetDotGitDirectory()
2>MSBUILD : warning :    在 GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig)
2>MSBUILD : warning :    在 GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication)
2>MSBUILD : warning : WARN [06/12/16 12:22:11:72] Could not determine assembly version: System.Runtime.InteropServices.MarshalDirectiveException: StrictFilePathMarshaler must be used on a FilePath.
2>MSBUILD : warning :    在 LibGit2Sharp.Core.StrictFilePathMarshaler.MarshalManagedToNative(Object managedObj)
2>MSBUILD : warning :    在 System.StubHelpers.MngdRefCustomMarshaler.ConvertContentsToNative(IntPtr pMarshalState, Object& pManagedHome, IntPtr pNativeHome)
2>MSBUILD : warning :    在 LibGit2Sharp.Core.NativeMethods.git_repository_discover(GitBuf buf, FilePath start_path, Boolean across_fs, FilePath ceiling_dirs)
2>MSBUILD : warning :    在 LibGit2Sharp.Core.Proxy.<>c__DisplayClass39.<git_repository_discover>b__38(GitBuf buf)
2>MSBUILD : warning :    在 LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)
2>MSBUILD : warning :    在 LibGit2Sharp.Core.Proxy.git_repository_discover(FilePath start_path)
2>MSBUILD : warning :    在 LibGit2Sharp.Repository.Discover(String startingPath)
2>MSBUILD : warning :    在 GitVersion.GitPreparer.GetDotGitDirectory()
2>MSBUILD : warning :    在 GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig)
2>MSBUILD : warning :    在 GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication)
2>MSBUILD : warning : WARN [06/12/16 12:22:11:72] Could not determine assembly version: System.Runtime.InteropServices.MarshalDirectiveException: StrictFilePathMarshaler must be used on a FilePath.
2>MSBUILD : warning :    在 LibGit2Sharp.Core.StrictFilePathMarshaler.MarshalManagedToNative(Object managedObj)
2>MSBUILD : warning :    在 System.StubHelpers.MngdRefCustomMarshaler.ConvertContentsToNative(IntPtr pMarshalState, Object& pManagedHome, IntPtr pNativeHome)
2>MSBUILD : warning :    在 LibGit2Sharp.Core.NativeMethods.git_repository_discover(GitBuf buf, FilePath start_path, Boolean across_fs, FilePath ceiling_dirs)
2>MSBUILD : warning :    在 LibGit2Sharp.Core.Proxy.<>c__DisplayClass39.<git_repository_discover>b__38(GitBuf buf)
2>MSBUILD : warning :    在 LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)
2>MSBUILD : warning :    在 LibGit2Sharp.Core.Proxy.git_repository_discover(FilePath start_path)
2>MSBUILD : warning :    在 LibGit2Sharp.Repository.Discover(String startingPath)
2>MSBUILD : warning :    在 GitVersion.GitPreparer.GetDotGitDirectory()
2>MSBUILD : warning :    在 GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig)
2>MSBUILD : warning :    在 GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication)

**Comment by asbjornu** [comment] 2016-06-15 09:39
Duplicate of #720.

**Closed by asbjornu** 2016-06-15 09:39 UTC
Labels: duplicate

**Comment by asbjornu** [comment] 2016-06-15 09:43
@oSilas Which version of GitVersion are you using?

**Comment by oSilas** [comment] 2016-06-15 12:22
@asbjornu  GitVersionTask.3.5.4

**Comment by asbjornu** [comment] 2016-06-15 12:26
@oSilas Ok, thanks. Then we have confirmation that this is still occurring. We're tracking this in #720.

**Comment by pkiers** [comment] 2016-07-15 07:32
Hi,

I wanted to tell you how much our friendship means to me and to show you some things that ainspire me, take a look here, please <http://effort.rddevelopmentpartners.com/e2rqeci>

Rushing, p.kiers@home.nl
