### ISSUE TITLE
[Bug] Nullreference exception trying to run it in Azure Devops

### ISSUE THREAD

**Issue by mpalmujoki** [GitTools/GitVersion#3199] opened 2022-09-19 13:23 UTC
**Describe the bug**
When I try to run the build using an new azure-pipelines.yml file, the build crashes in the GitVersion phase.

## Expected Behavior
I expect that GitVersion would calculate the version correctly and not crash.

## Actual Behavior
All steps up to Determine Version work fine, but then running GitVersion crashes.

Due to difficulty to make it readable in the Preview, I opted to put it into a Gist. Here:
https://gist.github.com/mpalmujoki/fdd58d9a49c1f6d4bacaa620c7d88cd6

## Possible Fix
I have tried different versions but I end up in the same result. Maybe a prerelease could help...

## Steps to Reproduce
This azure-pipeline.yml definition seems to reproduce it constantly: 
`# Variable Group 'xxxx' was defined in the Variables tab

trigger:
  branches:
    include:
    - refs/heads/develop

variables:
- name: 'xxxx'
  value: '**\*.sln'

jobs:
- job: BuildPublish
  displayName: 'Build and publish'
  pool:
    vmImage: windows-2022
  workspace:
    clean: all
  timeoutInMinutes: 120

  steps:
  - checkout: self

### Use NuGet
  - task: NuGetToolInstaller@0
    displayName: Use NuGet 6.0a
    inputs:
      versionSpec: 6.0

### NuGet restore
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: $(BuildParameters.solution)

### Use .Net 6.0.x SDK 
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 6.0.x
    inputs:
      version: 6.0.x

### GitVersion
  - task: gitversion/setup@0
    displayName: Install GitVersion
    inputs:
      versionSpec: '5.10.x'

  - task: gitversion/execute@0
    displayName: Determine Version

### App.config file transform
  - task: FileTransform@1
    displayName: Replace values in app.config
    inputs:
      folderPath: src/xxxx
      enableXmlTransform: true
      fileType: xml

### .Net Build
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: xxxx.sln

### Publish symbols path
  - task: PublishSymbols@2
    displayName: Publish symbols path
    continueOnError: True
    inputs:
      SearchPattern: '**\bin\**\*.pdb'
      PublishSymbols: false
      SymbolServerType: TeamServices

### Publish Artifact
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop_qa'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: src/xxxx.Installer/Release
      ArtifactName: drop_qa
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'`

## Context
I want to migrate from visual Azure pipelines to .yml based ones, but failing due to GitVersion behaving abnormalry.

## Your Environment
Azure Devops Windows-2022 image.
Cannot give direct link to customer project, sorry.

**Comment by asbjornu** [comment] 2022-09-19 14:23
Pretty sure this is a duplicate of #3188. Please report back and I'll reopen if it isn't.

**Closed by asbjornu** 2022-09-19 14:23 UTC
Labels: bug

**Comment by mpalmujoki** [comment] 2022-09-20 07:43
This fixed it.

  steps:
  - checkout: self
    fetchDepth: 0
    clean: true
