### ISSUE TITLE
RC tags trigger incorrect increments.

### ISSUE THREAD

**Issue by JimBobSquarePants** [GitTools/GitVersion#2329] opened 2020-06-16 11:01 UTC
**Describe the bug**
Following an RC release tag version, e.g.`v1.0.0-rc.2` incremented prerelease values are reset and appear to be based upon only the commit count since the release.  This breaks the upgrade path for users. 

I've looked at #1600 which appears to be related but only contains tests without fixes. #1844 may be related but was closed as stale.

## Expected Behavior

I would expect the version to take into consideration the new RC tag and not reset.

## Actual Behavior

Calculated increments are reset which leads to version numbers that are lower than previous builds.

## Steps to Reproduce

Using the following GitVersion.yml

```yaml
continuous-delivery-fallback-tag: ci
branches:
    master:
        tag: unstable
        mode: ContinuousDeployment
    pull-request:
        tag: pr

```
- Build (version increments)
- Create Tag
- Build (version resets)

An example of such appears at the following [Github Action](https://github.com/SixLabors/ImageSharp/runs/776136432?check_suite_focus=true#step:8:85)

## Context

It's rendered my nightly builds effectively useless for consumers.

## Your Environment

- Version Used: Action 0.9.3, GitVersion 5.3.6
- Operating System and version (Windows 10, Ubuntu 18.04): All 
- Link to your project: https://github.com/SixLabors/ImageSharp
- Link to your CI build (if appropriate): https://github.com/SixLabors/ImageSharp/runs/776136432?check_suite_focus=true#step:8:85

**Comment by asbjornu** [comment] 2020-06-18 21:28
I would love to snap my fingers and have this problem fixed, but it doesn't affect me and I have more than enough other things to do, so I neither have the incentive nor time to fix this. If you are able to invest time into figuring why this is occurring and fixing it, I would be very greatful and would of course review and merge your PR.

**Comment by asbjornu** [comment] 2022-09-03 23:06
You may be affected by #3041. Please have a look and let me know.

**Comment by HHobeck** [comment] 2023-03-18 18:46
May I ask you to provide an integration test please? I have no clue what you are expecting and I have no idea if this issue is already solved. I can tell you it is really hard to get into such issues and answer the question: Has it already been solved or not with the actual refactoring initiative!? Please provide integration tests any time. It makes live easier for the people who wants to make GitVersion stable. Thank you very much. BTW the web link in the description is broken.

Cheers

**Comment by HHobeck** [comment] 2023-03-20 06:42
Okay no problem. Because of missing steps to reproduce I'm going to close this issue.

**Closed by HHobeck** 2023-03-20 06:42 UTC
Labels: bug
