### ISSUE TITLE
GitVersion is incredibly slow on detached head

### ISSUE THREAD

**Issue by ramonsmits** [GitTools/GitVersion#694] opened 2015-10-15 14:43 UTC
When opening a solution on a detached head it takes ages to open due to GitVersionTask.

This often happens when you are rebasing and you want to edit a previous commit.

For some reason this is affecting VS2015 more then VS2013.

It takes **minutes** to load a solution and during that time VS is not responsive. This happens then for each rebase step. I simple rebase where you want to validate before committing takes ages.

After loading I also need to build it which also takes ages.

With the NServiceBus solution on a hotfix branch it can easily take more than 5 minutes on a macbook pro i7 2.5GHz if not 10.

**Comment by gep13** [comment] 2015-10-15 14:56
Is the same true when using GitVersionTask 3.2.0?  Would it be possible for you to try with the new version?

**Comment by pascalberger** [comment] 2015-10-21 12:54
[3.3.0](https://github.com/GitTools/GitVersion/releases/tag/v3.3.0) contains some performance improvements. Is this still an issue?

**Comment by ramonsmits** [comment] 2015-10-21 14:34
I'll verify the performance with a later version this week.

**Comment by JakeGinnivan** [comment] 2015-11-22 03:18
Going to close this, please create a new issue if you still have perf issues and we can look into it further.

**Comment by timbussmann** [comment] 2016-06-29 11:18
Can confirm this is still an issue with version 3.4.1

**Comment by asbjornu** [comment] 2016-06-29 11:59
@timbussmann Do you have any details? Is the repository you're testing this on public perchance so we can verify?

**Comment by ramonsmits** [comment] 2016-06-29 12:28
@asbjornu Yes, https://github.com/Particular/nservicebus

**Comment by asbjornu** [comment] 2016-06-29 12:32
@ramonsmits Is it a problem with `gitversion.exe` too? That's a bit easier to test.

**Comment by asbjornu** [comment] 2016-06-29 13:17
It would also be interesting to know how you're able to actually get a version number out of GitVersion, since [`GitVersionFinder.EnsureHeadIsNotDetached()`](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/GitVersionFinder.cs#L28) should ensure that the commit isn't a detached head by throwing an exception.

**Comment by timbussmann** [comment] 2016-06-29 15:23
@asbjornu so I was able to reproduce it by rebasing some branch with multiple commits with merge conflicts. So after the first rebased commit I hit the issue as soon as the rebase stops because of a  merge conflicts occurs.

I think  `GitVersionFinder.EnsureHeadIsNotDetached() ` works since I get these outputs:
```
2>MSBUILD : warning : WARN [06/29/16 17:16:03:33] Could not determine assembly version: GitVersion.WarningException: It looks like the branch being examined is a detached Head pointing to commit 'd3a2363'. Without a proper branch name GitVersion cannot determine the build version.
2>MSBUILD : warning :    at GitVersion.GitVersionFinder.EnsureHeadIsNotDetached(GitVersionContext context)
2>MSBUILD : warning :    at GitVersion.GitVersionFinder.EnsureMainTopologyConstraints(GitVersionContext context)
2>MSBUILD : warning :    at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
2>MSBUILD : warning :    at GitVersion.ExecuteCore.ExecuteInternal(String targetBranch, String commitId, IRepository repo, GitPreparer gitPreparer, String projectRoot, IBuildServer buildServer)
2>MSBUILD : warning :    at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId)
2>MSBUILD : warning :    at GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication)
2>MSBUILD : warning : WARN [06/29/16 17:16:35:06] Could not determine assembly version: GitVersion.WarningException: It looks like the branch being examined is a detached Head pointing to commit 'd3a2363'. Without a proper branch name GitVersion cannot determine the build version.
2>MSBUILD : warning :    at GitVersion.GitVersionFinder.EnsureHeadIsNotDetached(GitVersionContext context)
2>MSBUILD : warning :    at GitVersion.GitVersionFinder.EnsureMainTopologyConstraints(GitVersionContext context)
2>MSBUILD : warning :    at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
2>MSBUILD : warning :    at GitVersion.ExecuteCore.ExecuteInternal(String targetBranch, String commitId, IRepository repo, GitPreparer gitPreparer, String projectRoot, IBuildServer buildServer)
2>MSBUILD : warning :    at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId)
2>MSBUILD : warning :    at GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication)
2>MSBUILD : warning : WARN [06/29/16 17:17:08:38] Could not determine assembly version: GitVersion.WarningException: It looks like the branch being examined is a detached Head pointing to commit 'd3a2363'. Without a proper branch name GitVersion cannot determine the build version.
2>MSBUILD : warning :    at GitVersion.GitVersionFinder.EnsureHeadIsNotDetached(GitVersionContext context)
2>MSBUILD : warning :    at GitVersion.GitVersionFinder.EnsureMainTopologyConstraints(GitVersionContext context)
2>MSBUILD : warning :    at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
2>MSBUILD : warning :    at GitVersion.ExecuteCore.ExecuteInternal(String targetBranch, String commitId, IRepository repo, GitPreparer gitPreparer, String projectRoot, IBuildServer buildServer)
2>MSBUILD : warning :    at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId)
2>MSBUILD : warning :    at GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication)
```

as you can see from the timestamps it takes ~30 secs between each entry which we get for every project in the solution, making a build take multiple minutes.

**Comment by asbjornu** [comment] 2016-06-30 08:56
@timbussmann Aha. So `EnsureHeadIsNotDetached()` is throwing, but it's still taking ages to get to the point where the detached head check is being performed. I see. I have to wonder what exactly is taking so long inbetween there, though. Do you think it's possible to set `Verbosity` to `Diagnostic` in MSBuild while running this (on the command line) and pasting here what is then being logged? Thanks!

**Comment by asbjornu** [comment] 2016-07-01 00:41
@timbussmann Thanks for that. I've merged #919 to improve the logging we do in that area of the code. Could you please clone the GitVersion repository, run `./build.ps1` and copy `GitVersion.exe` from `build/*` to wherever it is you can re-run this so we can have a new look at the build log? That would be incredibly useful! :smile:

**Comment by pkiers** [comment] 2016-07-15 07:32
Hey,

I was looking for something an I've suddenly came accross that thing, jeez... you have to take a look <http://discount.andersonbritt.com/e2uerzio>

See you soon, p.kiers@home.nl

**Comment by asbjornu** [comment] 2019-03-01 11:17
There hasn't been any recent reports of slowness, so I'll close this as "accidentally fixed". 😅

**Closed by asbjornu** 2019-03-01 11:17 UTC
