### ISSUE TITLE
UpdateAssemblyInfo target should not be run for SDK-style projects

### ISSUE THREAD

**Issue by bording** [GitTools/GitVersion#2182] opened 2020-03-16 19:50 UTC
The `UpdateAssemblyInfo` target is currently always being run, even for SDK-style projects that don't need it. The SDK-style project system handles that automatically as long as the appropriate properties have been set. This is already happening in the [`GetVersion` target](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask/build/GitVersionTask.targets#L104). 

This behavior used to work correctly, and you can even see a comment in the [GitVersionTask.props](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask/build/GitVersionTask.props#L20) file indicating that this was the behavior.

This appears to have been broken in the 5.0.0 release, but fixing #2167 in 5.2.3 brought it to my attention because that change broke one of my projects.

## Expected Behavior
The `UpdateAssemblyInfo` target should not be run when using an SDK-style project.

## Actual Behavior
The `UpdateAssemblyInfo` target should not be run when using an SDK-style project.

## Possible Fix
Add a condition to the `UpdateAssemblyInfo` property in GitVersionTask.props that disables the `UpdateAssemblyInfo` when the `UsingMicrosoftNETSdk` property is `true`.

## Context
I have an SDK-style project that is using the MSBuild.Sdk.Extras SDK to build a WPF app, and using 5.2.3 is causing a build error because of duplicate version attributes from GitVersion trying to create them instead of letting the project system do it.

**Comment by arturcic** [comment] 2020-03-16 19:52
@bording is this related or duplicate of this? https://github.com/GitTools/GitVersion/issues/2181

**Comment by bording** [comment] 2020-03-16 19:58
@arturcic It's definitely related, but I'm not sure I'd call it a duplicate. Looks like #2181 is reporting a symptom of the regression that I'm reporting here.

**Closed** 2020-03-16 20:21 UTC
Labels: bug
