### ISSUE TITLE
VSTS fails when calling the GitVersion task (System.DllNotFoundException: Unable to load DLL 'git2-381caf5')

### ISSUE THREAD

**Issue by mabead** [GitTools/GitVersion#841] opened 2016-04-26 10:31 UTC
All my VSTS builds use the GitVersion tasks. In fact, the first step of my build is the GitVersion step. Unfortunately, starting today all my builds fail with the following error:

```
2016-04-26T10:18:07.7033600Z INFO [04/26/16 10:18:06:74] Applicable build agent found: 'VsoAgent'.
2016-04-26T10:18:07.7033600Z ERROR [04/26/16 10:18:06:80] An unexpected error occurred:
2016-04-26T10:18:07.7043779Z System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-381caf5': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
2016-04-26T10:18:07.7053771Z    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
2016-04-26T10:18:07.7053771Z    at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor()
2016-04-26T10:18:07.7063804Z    at LibGit2Sharp.Core.NativeMethods..cctor()
2016-04-26T10:18:07.7063804Z    --- End of inner exception stack trace ---
2016-04-26T10:18:07.7173757Z    at LibGit2Sharp.Core.NativeMethods.git_buf_free(GitBuf buf)
2016-04-26T10:18:07.7173757Z    at LibGit2Sharp.Core.Proxy.git_buf_free(GitBuf buf)
2016-04-26T10:18:07.7183756Z    at LibGit2Sharp.Core.Handles.GitBuf.Dispose()
2016-04-26T10:18:07.7183756Z    at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)
2016-04-26T10:18:07.7193758Z    at LibGit2Sharp.Core.Proxy.git_repository_discover(FilePath start_path)
2016-04-26T10:18:07.7193758Z    at LibGit2Sharp.Repository.Discover(String startingPath)
2016-04-26T10:18:07.7203751Z    at GitVersion.GitPreparer.GetDotGitDirectory()
2016-04-26T10:18:07.7203751Z    at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig)
2016-04-26T10:18:07.7213753Z    at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
2016-04-26T10:18:07.7213753Z    at GitVersion.Program.VerifyArgumentsAndRun()
2016-04-26T10:18:07.7223751Z INFO [04/26/16 10:18:06:80] 
2016-04-26T10:18:07.7223751Z INFO [04/26/16 10:18:06:80] Here is the current git graph (please include in issue): 
2016-04-26T10:18:07.7233775Z INFO [04/26/16 10:18:06:80] Showing max of 100 commits
2016-04-26T10:18:07.7233775Z INFO [04/26/16 10:18:07:30] * c1ac14a 10 hours ago  (HEAD, origin/features/sonarqube-failure)
2016-04-26T10:18:07.7243753Z * c6a2b70 21 hours ago 
2016-04-26T10:18:07.7243753Z * 5aa2cbb 24 hours ago 
2016-04-26T10:18:07.7253758Z | *   00f5cba 13 hours ago  (origin/develop)
2016-04-26T10:18:07.7253758Z | |\  
2016-04-26T10:18:07.7263776Z | | * e0df8ca 14 hours ago  (origin/features/ship-to-store)
2016-04-26T10:18:07.7263776Z | | | *   8bb0150 15 hours ago  (origin/bugs/5371-validation-no-inventory)
2016-04-26T10:18:07.7273768Z | | | |\  
2016-04-26T10:18:07.7273768Z | | |_|/  
2016-04-26T10:18:07.7283769Z | |/| |   
2016-04-26T10:18:07.7283769Z | * | |   6f7f516 15 hours ago  (origin/features/get-products-by-skus)
2016-04-26T10:18:07.7283769Z | |\ \ \  
2016-04-26T10:18:07.7293764Z | | |/ /  
2016-04-26T10:18:07.7293764Z | | * |   2d5a845 16 hours ago  (origin/features/migrate-feature3-from-tfs-to-git)
2016-04-26T10:18:07.7303770Z | | |\ \  
2016-04-26T10:18:07.7303770Z | | | * | f08d0b9 16 hours ago 
2016-04-26T10:18:07.7313768Z | | | * | df63e5d 16 hours ago 
2016-04-26T10:18:07.7323767Z | | | * | f2fd828 17 hours ago 
2016-04-26T10:18:07.7323767Z | | | * |   ea8f525 17 hours ago 
2016-04-26T10:18:07.7323767Z | | | |\ \  
2016-04-26T10:18:07.7333773Z | | | * | | 67fde22 17 hours ago 
2016-04-26T10:18:07.7343774Z | | | * | | bbb13df 17 hours ago 
2016-04-26T10:18:07.7343774Z | | | * | | 5412d90 17 hours ago 
2016-04-26T10:18:07.7354750Z | | | * | |   60c136c 18 hours ago 
2016-04-26T10:18:07.7354750Z | | | |\ \ \  
2016-04-26T10:18:07.7364896Z | | | * | | | 9957f1f 18 hours ago 
2016-04-26T10:18:07.7374844Z | | | * | | |   7ff7333 19 hours ago 
2016-04-26T10:18:07.7374844Z | | | |\ \ \ \  
2016-04-26T10:18:07.7384845Z | | | * | | | | 525201b 19 hours ago 
2016-04-26T10:18:07.7384845Z | | * | | | | | e49881a 16 hours ago 
2016-04-26T10:18:07.7394838Z | | | |_|_|/ /  
2016-04-26T10:18:07.7394838Z | | |/| | | |   
2016-04-26T10:18:07.7404839Z | | * | | | | b7af6d1 17 hours ago 
2016-04-26T10:18:07.7404839Z | | | |_|/ /  
2016-04-26T10:18:07.7414843Z | | |/| | |   
2016-04-26T10:18:07.7414843Z | | * | | | 80a5ed7 18 hours ago 
2016-04-26T10:18:07.7424840Z | | | |/ /  
2016-04-26T10:18:07.7424840Z | | |/| |   
2016-04-26T10:18:07.7434832Z | | * | | 15d340a 19 hours ago 
2016-04-26T10:18:07.7434832Z | | |/ /  
2016-04-26T10:18:07.7444843Z | | * | 3d12d68 21 hours ago 
2016-04-26T10:18:07.7444843Z | | * | 0c7cac6 21 hours ago 
2016-04-26T10:18:07.7444843Z | | * | b255077 3 days ago 
2016-04-26T10:18:07.7454857Z | | * |   4aaff79 4 days ago 
2016-04-26T10:18:07.7454857Z | | |\ \  
2016-04-26T10:18:07.7464866Z | |/ / /  
2016-04-26T10:18:07.7474838Z |/| | |   
2016-04-26T10:18:07.7474838Z | | * | d76d321 5 days ago  (origin/features/tfs-main-branch-replication)
2016-04-26T10:18:07.7484843Z | | | *   bdc862e 16 hours ago 
2016-04-26T10:18:07.7484843Z | | | |\  
2016-04-26T10:18:07.7494842Z | | |_|/  
2016-04-26T10:18:07.7494842Z | |/| |   
2016-04-26T10:18:07.7494842Z | * | | 5de51ca 22 hours ago 
2016-04-26T10:18:07.7504840Z |/ / /  
2016-04-26T10:18:07.7504840Z | | * b2bbc25 16 hours ago 
2016-04-26T10:18:07.7514918Z | | * 21b2e31 16 hours ago 
2016-04-26T10:18:07.7520966Z | | * 5ace221 5 days ago 
2016-04-26T10:18:07.7526553Z | | | *   1621371 4 days ago  (origin/features/dynamics-ax-2)
2016-04-26T10:18:07.7533705Z | | | |\  
2016-04-26T10:18:07.7533705Z | | | | *   d8e758c 4 days ago 
2016-04-26T10:18:07.7543866Z | | | | |\  
2016-04-26T10:18:07.7553854Z | | | | * | b091618 4 days ago 
2016-04-26T10:18:07.7553854Z | | | * | | 7758a93 4 days ago 
2016-04-26T10:18:07.7563883Z | | | | |/  
2016-04-26T10:18:07.7563883Z | | | |/|   
2016-04-26T10:18:07.7573863Z | | | * | 1e4ad08 4 days ago 
2016-04-26T10:18:07.7573863Z | | | * | af156e7 4 days ago 
2016-04-26T10:18:07.7583865Z | | | * | dfd5a1c 6 days ago 
2016-04-26T10:18:07.7583865Z | | | * | 02b0978 6 days ago 
2016-04-26T10:18:07.7583865Z | | | * |   babd4b8 6 days ago 
2016-04-26T10:18:07.7593864Z | | | |\ \  
2016-04-26T10:18:07.7593864Z | | | | * | 71731ca 7 days ago 
2016-04-26T10:18:07.7603873Z | | | | |/  
2016-04-26T10:18:07.7603873Z | | | * | f37ce6d 6 days ago 
2016-04-26T10:18:07.7613874Z | | | |/  
2016-04-26T10:18:07.7613874Z | | | * 9994baf 7 days ago 
2016-04-26T10:18:07.7623870Z | | | * 8be9b80 7 days ago 
2016-04-26T10:18:07.7623870Z | | | * e8cc161 7 days ago 
2016-04-26T10:18:07.7633860Z | | | * c602276 7 days ago 
2016-04-26T10:18:07.7633860Z | | | * 438a408 7 days ago 
2016-04-26T10:18:07.7643892Z | | | * 0f58835 7 days ago 
2016-04-26T10:18:07.7643892Z | | | * 6d4c9e3 7 days ago 
2016-04-26T10:18:07.7653856Z | | | * 3dd1269 7 days ago 
2016-04-26T10:18:07.7653856Z | | | * 498b40f 7 days ago 
2016-04-26T10:18:07.7663876Z | | | *   4e12fa0 7 days ago 
2016-04-26T10:18:07.7663876Z | | | |\  
2016-04-26T10:18:07.7663876Z | | | * \   c53b1e8 11 days ago  (origin/features/Dynamics-AX)
2016-04-26T10:18:07.7673868Z | | | |\ \  
2016-04-26T10:18:07.7673868Z | | | | * | 1726872 11 days ago 
2016-04-26T10:18:07.7683868Z | | | | * | 26dc32a 11 days ago 
2016-04-26T10:18:07.7683868Z | | | * | | 7fa6bb8 11 days ago 
2016-04-26T10:18:07.7693876Z | | | |/ /  
2016-04-26T10:18:07.7693876Z | | | * | 3270b90 12 days ago 
2016-04-26T10:18:07.7703863Z | | | * | 99ca179 12 days ago 
2016-04-26T10:18:07.7703863Z | | | * | 4aeb839 13 days ago 
2016-04-26T10:18:07.7713989Z | | | * |   65eef76 13 days ago 
2016-04-26T10:18:07.7713989Z | | | |\ \  
2016-04-26T10:18:07.7713989Z | | | | * | 6de5d43 13 days ago 
2016-04-26T10:18:07.7723864Z | | | * | | 30b2b2c 13 days ago 
2016-04-26T10:18:07.7723864Z | | | |/ /  
2016-04-26T10:18:07.7733898Z | | | * | f23c155 2 weeks ago 
2016-04-26T10:18:07.7733898Z | | | * | dd6a534 2 weeks ago 
2016-04-26T10:18:07.7743862Z | | | * |   0dac2c9 2 weeks ago 
2016-04-26T10:18:07.7753854Z | | | |\ \  
2016-04-26T10:18:07.7753854Z | | | * \ \   20883a8 2 weeks ago 
2016-04-26T10:18:07.7763871Z | | | |\ \ \  
2016-04-26T10:18:07.7763871Z | | | | * | | 4729746 2 weeks ago 
2016-04-26T10:18:07.7763871Z | | | * | | |   cf1212a 2 weeks ago 
2016-04-26T10:18:07.7773865Z | | | |\ \ \ \  
2016-04-26T10:18:07.7793885Z | | | | |/ / /  
2016-04-26T10:18:07.7793885Z | | | | * | | 965eb15 2 weeks ago 
2016-04-26T10:18:07.7803857Z | | | * | | | 2cdd634 2 weeks ago 
2016-04-26T10:18:07.7803857Z | | | |/ / /  
2016-04-26T10:18:07.7813865Z | | | * | | 49d91db 2 weeks ago 
2016-04-26T10:18:07.7813865Z | | | * | | 858afef 2 weeks ago 
2016-04-26T10:18:07.7813865Z | | | * | |   475969d 2 weeks ago 
2016-04-26T10:18:07.7823860Z | | | |\ \ \  
2016-04-26T10:18:07.7823860Z | | | | * | | 81d4f4f 3 weeks ago 
2016-04-26T10:18:07.7833867Z | | | | * | | a40ab03 3 weeks ago 
2016-04-26T10:18:07.7833867Z | | | | * | |   a934d2f 3 weeks ago 
2016-04-26T10:18:07.7843863Z | | | | |\ \ \  
2016-04-26T10:18:07.7843863Z | | | | * | | | 44a3275 3 weeks ago 
2016-04-26T10:18:07.7853859Z | | | * | | | | 305771e 2 weeks ago 
2016-04-26T10:18:07.7853859Z | | | | |/ / /  
2016-04-26T10:18:07.7863857Z | | | |/| | |   
2016-04-26T10:18:07.7863857Z | | | * | | | afb9774 3 weeks ago 
2016-04-26T10:18:07.7873861Z | | | * | | | 26bdb63 3 weeks ago 
2016-04-26T10:18:07.7873861Z | | | * | | | 77ae71e 3 weeks ago 
2016-04-26T10:18:07.7873861Z | | | |/ / /  
2016-04-26T10:18:07.7883863Z | | | * | | b6cc318 3 weeks ago 
2016-04-26T10:18:07.7883863Z | | | * | |   1d55269 3 weeks ago 
2016-04-26T10:18:07.7893857Z | | | |\ \ \  
2016-04-26T10:18:07.7893857Z | | | | * | | 8fb5250 3 weeks ago 
2016-04-26T10:18:07.7903854Z | | | | * | |   d7e8c72 3 weeks ago 
2016-04-26T10:18:07.7903854Z | | | | |\ \ \  
2016-04-26T10:18:07.7913862Z | | | | | * | | 1298724 3 weeks ago 
2016-04-26T10:18:07.7913862Z | | | | * | | | b7bd332 3 weeks ago 
2016-04-26T10:18:07.7923861Z | | | | |/ / /  
2016-04-26T10:18:07.7923861Z | | | | * | | e83d24b 3 weeks ago 
2016-04-26T10:18:07.7933862Z | | | | * | | ea28e4a 3 weeks ago 
2016-04-26T10:18:07.7933862Z | | | | * | | 85bbf06 3 weeks ago 
2016-04-26T10:18:07.7968615Z | | | | * | | df94686 3 weeks ago 
2016-04-26T10:18:07.7973884Z | | | | * | | 99cb22b 3 weeks ago 
2016-04-26T10:18:07.7973884Z | | | * | | | 31786cc 3 weeks ago 
2016-04-26T10:18:07.7983858Z | | | * | | | 5251d97 3 weeks ago 
2016-04-26T10:18:07.7983858Z | | | |/ / /  
2016-04-26T10:18:07.7993850Z | | | * | | 6c5960c 3 weeks ago 
2016-04-26T10:18:07.7993850Z | | | * | | 8357bf5 4 weeks ago 
2016-04-26T10:18:07.7993850Z | | | * | | 27b0bd1 4 weeks ago 
2016-04-26T10:18:07.8003863Z | | | | | | *   eeca0cf 4 days ago  (origin/bugs/bug-fix-1828)
2016-04-26T10:18:07.8003863Z | | | | | | |\  
2016-04-26T10:18:07.8013863Z | |_|_|_|_|_|/  
2016-04-26T10:18:07.8013863Z |/| | | | | |   
```
I saw that a new version of GitVersion was released today. I suspect this is related...

Could you please validate this as soon as possible as this is blocking all our builds.

Thanks,
Maxime

**Comment by pascalberger** [comment] 2016-04-26 10:41
This should already be fixed by #840. 

@JakeGinnivan Is in the process of releasing an update to the extension.

**Comment by JakeGinnivan** [comment] 2016-04-26 11:31
3.5.1 is released. Sorry guys!

**Comment by JakeGinnivan** [comment] 2016-04-26 11:32
@mabead let me know if this doesn't fix the issue.

**Closed by JakeGinnivan** 2016-04-26 11:31 UTC

**Comment by mabead** [comment] 2016-04-26 12:29
@JakeGinnivan It does fix this issue. Thanks for the fast turn around!

**Comment by eatdrinksleepcode** [comment] 2016-04-27 07:21
I'm getting this exact same error using 3.5.2 (GitVersion.CommandLine) on OSX using Mono 4.3.2. Is there another cause I should be looking at?

**Comment by asbjornu** [comment] 2016-04-27 16:30
@eatdrinksleepcode, make sure you have version 0.23.0-pre of LibGit2Sharp. Do you?

**Comment by eatdrinksleepcode** [comment] 2016-04-27 18:30
@asbjornu When you say I should "have" it, what do you mean? Where should it be located? I can install version 0.23.0-pre20150419160303 of LibGit2Sharp into my packages directory (where GitVersion.CommandLine also is), but that doesn't help GitVersion.exe any.

It think the issue is that I am trying to use the GitVersion.CommandLine package instead of the Chocolatey package, both because I want the version of GitVersion used to be specific to this project, and because I am building this project "mono first" and Chocolatey doesn't help me on OSX. But the GitVersion.CommandLine package seems to be unsupported, so I am wondering if there is a better option.

Happy to move this to another issue or to Gitter if it makes sense.

**Comment by pascalberger** [comment] 2016-04-27 18:38
@eatdrinksleepcode Since this issue was about the Visual Studio Team System task (where the LibGit DLLs were completely missing), I would suggest that you open a new issue to track / discuss it.
