### ISSUE TITLE
.NET Standard 2.0: dotnet build fails

### ISSUE THREAD

**Issue by roeb** [GitTools/GitVersion#1307] opened 2017-10-09 09:58 UTC
Hi all,

I have a problem to use GitVersionTask (Version="4.0.0-beta0012") in a new simple and clean .netstandard2.0 library. The project has only a User class with some properties and a nuget reference to GitversionTask in version 4.0.0-beta0012.

If i run the rebuild command from Visual Studio 2017, it works fine. But when I try to run "dotnet build" in the console, it throws the following error:

```C:\Users\rme\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.targets(49,5): error MSB4062: The "GitVersionTask.WriteVersionInfoToBuildLog" task could not be loaded from the assembly C:\Users\rme\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Learning\GitHub\GitVersionTaskBuildIssue\GitVersionTaskBuildIssue\GitVersionTaskBuildIssue.csproj]```

You can find the simple project on [GitHub](https://github.com/roeb/GitVersionTaskBuildIssue). Has anyone any idea or solution for the problem?

**Comment by dazinator** [comment] 2017-10-11 08:34
Adding support for dotnet cli builds is currently in progress. Follow pr #1269 for updates.

**Comment by dazinator** [comment] 2017-10-24 18:48
If you want too, you could always base a branch from my branch, and try and get the msbuild task to run. I am trying an approach using UtilPack (which allows the task to run under dotnet core, and desktop msbuild) but it's going slowly as there are a few remaining issues to overcome. But anyone reading this could probably hack together a simpler solution to this to allow the task to run. The rest of the hard work is already done in the branch.

**Comment by dazinator** [comment] 2017-11-02 11:38
Closing as dupe of #1175

**Closed by dazinator** 2017-11-02 11:38 UTC
