### ISSUE TITLE
Updating GitVersionTask to 5.0.1 casuses InvalidProjectFileException

### ISSUE THREAD

**Issue by SteveLockeUK** [GitTools/GitVersion#1776] opened 2019-08-13 15:07 UTC
When attempting to update the GitVersionTask nuget package to 5.0.1 I get the following exception: 
Microsoft.Build.Exceptions.InvalidProjectFileException: The result "" of evaluating the value "$(GitVersionAssemblyFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  SOLUTION_PATH\packages\GitVersionTask.5.0.0\build\GitVersionTask.targets.

This exception is also thrown if I attempt to uninstall 5.0.0.

Output during the update process is below:
Attempting to gather dependency information for package 'GitVersionTask.5.0.1' with respect to project 'PROJECT_NAME', targeting '.NETFramework,Version=v4.8'
Gathering dependency information took 84.75 ms
Attempting to resolve dependencies for package 'GitVersionTask.5.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'GitVersionTask.5.0.1'
Resolved actions to install package 'GitVersionTask.5.0.1'
Removed package 'GitVersionTask.5.0.0' from 'packages.config'
Install failed. Rolling back...
Package 'GitVersionTask.5.0.0' already exists in folder 'SOLUTION_PATH\packages'
Added package 'GitVersionTask.5.0.0' to 'packages.config'
Executing nuget actions took 369.8 ms

**Comment by grappachu** [comment] 2019-09-30 09:43
In my case i solved this by batch replacing all references from 5.0.0 to 5.0.1 in all *.config and *.csproj files using notepad++.

**Comment by keithrowe** [comment] 2019-12-19 23:51
This still happens when trying to uninstall GitVersionTask.5.1.2.

It only occurs for me when the solution uses package.config. Under PackageReferences, it uninstalls without incident.

**Comment by KiLLeRRaT** [comment] 2019-12-24 00:12
I'm also running into this, I use package.config too. 
I get it when trying to upgrade from 5.1.2 to 5.1.3

**Comment by asbjornu** [comment] 2020-01-02 14:36
@KiLLeRRaT, does changing from `package.config` to `PackageReferences` fix the problem for you as well?

**Comment by KiLLeRRaT** [comment] 2020-01-02 19:00
@asbjornu, At this stage I can't easily update from `package.config` to `PackageReferences` to test this because of a lot of other NuGet packages.  I will try to keep an eye out and see if I can test this out when I run into problems again.

**Comment by ThomasBarnekow** [comment] 2020-01-05 20:49
I can confirm that the issue does **not** appear when using `PackageReference`. It only happens with projects using `packages.config`.

I have a solution with a larger number of projects, most of which use `PackageReference`. However, two projects, which are VSTO add-ins, can't use `PackageReference` and must, unfortunately, use `packages.config`. When updating the `PackageReference` projects, there is no issue whatsoever. However, for the two projects that are still using `packages.config`, GitVersionTask can't be uninstalled or updated without running into that issue. The only way around that is to manually edit the `packages.config` and `.csproj` files as described by @grappachu.

I ran into the issue again when trying to update to `GitVersionTask.5.1.4-beta1.19` (to test the results of my PR which had just been merged). Here is the full stack trace with some context:

```
Attempting to gather dependency information for package 'GitVersionTask.5.1.4-beta1.19' with respect to project 'DokuMate.WordAddIn', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 10,69 ms
Attempting to resolve dependencies for package 'GitVersionTask.5.1.4-beta1.19' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'GitVersionTask.5.1.4-beta1.19'
Resolved actions to install package 'GitVersionTask.5.1.4-beta1.19'
Restoring packages for C:\Users\ThomasBarnekow\source\repos\DokuMate\DokuMate.Core\DokuMate.Core.csproj...
Restoring packages for C:\Users\ThomasBarnekow\source\repos\DokuMate\DokuMate.Office\DokuMate.Office.csproj...
Removed package 'GitVersionTask.5.1.3' from 'packages.config'
Install failed. Rolling back...
Package 'GitVersionTask.5.1.3' already exists in folder 'C:\Users\ThomasBarnekow\source\repos\DokuMate\packages'
Executing nuget actions took 882,3 ms
Microsoft.Build.Exceptions.InvalidProjectFileException: The result "" of evaluating the value "$(GitVersionAssemblyFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  C:\Users\ThomasBarnekow\source\repos\DokuMate\packages\GitVersionTask.5.1.3\build\GitVersionTask.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject[T1,T2,T3,T4](Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1, T3 arg2, T4 arg3)
   at Microsoft.Build.Execution.TaskRegistry.RegisterTasksFromUsingTaskElement[P,I](ILoggingService loggingService, BuildEventContext buildEventContext, String directoryOfImportingFile, ProjectUsingTaskElement projectUsingTaskXml, TaskRegistry taskRegistry, Expander`2 expander, ExpanderOptions expanderOptions, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateUsingTaskElement(String directoryOfImportingFile, ProjectUsingTaskElement projectUsingTaskElement)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at NuGet.PackageManagement.VisualStudio.MicrosoftBuildEvaluationProjectUtility.RemoveImportStatement(Project msBuildProject, String targetsPath)
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.RemoveImportStatement(String targetsPath)
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.<>c__DisplayClass43_0.<<RemoveImport>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.RemoveImport(String targetFullPath)
   at NuGet.ProjectManagement.MSBuildNuGetProject.<UninstallPackageAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteUninstallAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass12_0.<<PerformActionImplAsync>b__0>d.MoveNext()
```

**Comment by asbjornu** [comment] 2020-01-06 09:57
Since this seems to only relate to `GitVersionTask`, I wonder whether https://github.com/GitTools/GitVersion/issues/1031#issuecomment-561285533 is relevant and might fix this problem. 🤔

**Comment by KiLLeRRaT** [comment] 2020-04-05 18:53
Unstale! Go away bot! :)

**Comment by Tognolo** [comment] 2020-11-25 15:51
Any news since May 17th? I'm having the same issue, I'm going to fix manually my packages.config.

Is this project slowly dying?

**Comment by asbjornu** [comment] 2020-11-25 23:37
@Tognolo

> Any news since May 17th? I'm having the same issue, I'm going to fix manually my packages.config.

The maintenance of this project is done by very few people on our free time. Few of us use GitVersionTask anymore so none of us have any incentive to spend hours to hunt down and fix bugs that may exist within it.

If you have the time and energy to invest in fixing this issue, we more than welcome pull requests. But without anyone putting the required amount of time into fixing this, it won't be fixed. It's as simple as that.

> Is this project slowly dying?

The last commit was made a couple of days ago, so the obvious answer to that question is: No.

**Comment by v-karbovnichy** [comment] 2021-07-22 11:50
Is a duplicate of #2106

**Comment by v-karbovnichy** [comment] 2021-07-22 11:50
I can reproduce this when `GitVersion.MsBuild` v5.6.10 installed and I am trying to migrate the project from `packages.config` format to `PackageReference`. So, essentially, VS cannot uninstall the `GitVersion.MsBuild`package and rolls back the migration.

**Closed** 2023-04-13 15:37 UTC
Labels: bug
