### ISSUE TITLE
nuget sorting

### ISSUE THREAD

**Issue by tofutim** [GitTools/GitVersion#934] opened 2016-07-11 00:39 UTC
Hi, for my nuget, I am using %GitVersion.NuGetVersionV2%- in general this works fine, but today I ran into an issue where I wanted to get the latest prerelease, and it turns out that

Blahblah.1.4.0-unstable4

shows itself as a higher version than

Blahblah.1.4.0-unstable24

Probably I needed to use .24?

**Comment by JakeGinnivan** [comment] 2016-07-11 01:36
Hrrm, the NuGet version should always be padded. i.e unstable0024

NuGet doesn't support . delimeters in pre-release tags so we pad instead. How are you getting that variable, using the exe or MSBuild task?

**Comment by tofutim** [comment] 2016-07-11 02:36
I'm just using %GitVersion.NuGetVersionV2% - here's a sample:

{
  "Major":1,
  "Minor":4,
  "Patch":0,
  "PreReleaseTag":"unstable.18",
  "PreReleaseTagWithDash":"-unstable.18",
  "PreReleaseLabel":"unstable",
  "PreReleaseNumber":18,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.develop.Sha.3b7e9714014e4d33113141817117bebf27ea1964",
  "MajorMinorPatch":"1.4.0",
  "SemVer":"1.4.0-unstable.18",
  "LegacySemVer":"1.4.0-unstable18",
  "LegacySemVerPadded":"1.4.0-unstable18",
  "AssemblySemVer":"1.4.0.0",
  "FullSemVer":"1.4.0-unstable.18",
  "InformationalVersion":"1.4.0-unstable.18+Branch.develop.Sha.3b7e9714014e4d33113141817117bebf27ea1964",
  "BranchName":"develop",
  "Sha":"3b7e9714014e4d33113141817117bebf27ea1964",
  "NuGetVersionV2":"1.4.0-unstable18",
  "NuGetVersion":"1.4.0-unstable18",
  "CommitsSinceVersionSource":18,
  "CommitsSinceVersionSourcePadded":"0018",
  "CommitDate":"2016-07-11"
}

**Comment by tofutim** [comment] 2016-07-11 02:37
Here is a version with a 3, no padding...

{
  "Major":8,
  "Minor":4,
  "Patch":0,
  "PreReleaseTag":"unstable.3",
  "PreReleaseTagWithDash":"-unstable.3",
  "PreReleaseLabel":"unstable",
  "PreReleaseNumber":3,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.develop.Sha.fd790c12f18b6cfe1b9d555578b804410152d6b3",
  "MajorMinorPatch":"8.4.0",
  "SemVer":"8.4.0-unstable.3",
  "LegacySemVer":"8.4.0-unstable3",
  "LegacySemVerPadded":"8.4.0-unstable3",
  "AssemblySemVer":"8.4.0.0",
  "FullSemVer":"8.4.0-unstable.3",
  "InformationalVersion":"8.4.0-unstable.3+Branch.develop.Sha.fd790c12f18b6cfe1b9d555578b804410152d6b3",
  "BranchName":"develop",
  "Sha":"fd790c12f18b6cfe1b9d555578b804410152d6b3",
  "NuGetVersionV2":"8.4.0-unstable3",
  "NuGetVersion":"8.4.0-unstable3",
  "CommitsSinceVersionSource":3,
  "CommitsSinceVersionSourcePadded":"0003",
  "CommitDate":"2016-07-10"
}

**Comment by JakeGinnivan** [comment] 2016-07-11 04:10
Yep, that looks like a bug on develop

**Comment by tofutim** [comment] 2016-07-11 04:23
you mean develop of GitVersion, or the develop branch? here's master

{
  "Major":8,
  "Minor":3,
  "Patch":1,
  "PreReleaseTag":"alpha.3",
  "PreReleaseTagWithDash":"-alpha.3",
  "PreReleaseLabel":"alpha",
  "PreReleaseNumber":3,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.master.Sha.ce89128ceba826c7d7f855ef90f77456cbf237b5",
  "MajorMinorPatch":"8.3.1",
  "SemVer":"8.3.1-alpha.3",
  "LegacySemVer":"8.3.1-alpha3",
  "LegacySemVerPadded":"8.3.1-alpha3",
  "AssemblySemVer":"8.3.1.0",
  "FullSemVer":"8.3.1-alpha.3",
  "InformationalVersion":"8.3.1-alpha.3+Branch.master.Sha.ce89128ceba826c7d7f855ef90f77456cbf237b5",
  "BranchName":"master",
  "Sha":"ce89128ceba826c7d7f855ef90f77456cbf237b5",
  "NuGetVersionV2":"8.3.1-alpha3",
  "NuGetVersion":"8.3.1-alpha3",
  "CommitsSinceVersionSource":3,
  "CommitsSinceVersionSourcePadded":"0003",
  "CommitDate":"2016-07-10"
}

**Comment by JakeGinnivan** [comment] 2016-08-13 02:23
What version of GitVersion are you using. There are tests against this stuff so am unsure how it can happen. Can you create a test which reproduces the error?

**Comment by tofutim** [comment] 2016-08-13 04:07
I think if you just run gitversion from the command line you should see
what I mean.

gitversion


D:\Loqu8\Projects\jaffa>gitversion
{
  "Major":1,
  "Minor":4,
  "Patch":0,
  "PreReleaseTag":"unstable.47",
  "PreReleaseTagWithDash":"-unstable.47",
  "PreReleaseLabel":"unstable",
  "PreReleaseNumber":47,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",

"FullBuildMetaData":"Branch.develop.Sha.d81ac18f0649f811c710a286f2e6b98e7240dd01",
  "MajorMinorPatch":"1.4.0",
  "SemVer":"1.4.0-unstable.47",
  "LegacySemVer":"1.4.0-unstable47",
  "LegacySemVerPadded":"1.4.0-unstable47",
  "AssemblySemVer":"1.4.0.0",
  "FullSemVer":"1.4.0-unstable.47",

"InformationalVersion":"1.4.0-unstable.47+Branch.develop.Sha.d81ac18f0649f811c710a286f2e6b98e7240dd01",
  "BranchName":"develop",
  "Sha":"d81ac18f0649f811c710a286f2e6b98e7240dd01",
  "NuGetVersionV2":"1.4.0-unstable47", <-----
  "NuGetVersion":"1.4.0-unstable47", <----
  "CommitsSinceVersionSource":47,
  "CommitsSinceVersionSourcePadded":"0047",
  "CommitDate":"2016-08-13"
}

**Comment by tofutim** [comment] 2016-08-13 04:08
Sorry not sure what to write in command line to get the gitversion version,
but it was the latest when I wrote.

**Comment by JakeGinnivan** [comment] 2016-08-14 01:33
Can you right click on your gitversion exe and go to details and get the version. Also, can you post your GitVersion.yml file?

When I run locally:

```
C:\Users\jake\_code\test [develop]                                                                   
λ ..\GitVersion\src\GitVersionExe\bin\Debug\GitVersion.exe                                           
{                                                                                                    
  "Major":0,                                                                                         
  "Minor":1,                                                                                         
  "Patch":0,                                                                                         
  "PreReleaseTag":"alpha.2",                                                                         
  "PreReleaseTagWithDash":"-alpha.2",                                                                
  "PreReleaseLabel":"alpha",                                                                         
  "PreReleaseNumber":2,                                                                              
  "BuildMetaData":"",                                                                                
  "BuildMetaDataPadded":"",                                                                          
  "FullBuildMetaData":"Branch.develop.Sha.40ba9a24633452789651ef81a132ab609128a255",                 
  "MajorMinorPatch":"0.1.0",                                                                         
  "SemVer":"0.1.0-alpha.2",                                                                          
  "LegacySemVer":"0.1.0-alpha2",                                                                     
  "LegacySemVerPadded":"0.1.0-alpha0002",                                                            
  "AssemblySemVer":"0.1.0.0",                                                                        
  "FullSemVer":"0.1.0-alpha.2",                                                                      
  "InformationalVersion":"0.1.0-alpha.2+Branch.develop.Sha.40ba9a24633452789651ef81a132ab609128a255",
  "BranchName":"develop",                                                                            
  "Sha":"40ba9a24633452789651ef81a132ab609128a255",                                                  
  "NuGetVersionV2":"0.1.0-alpha0002",                                                                
  "NuGetVersion":"0.1.0-alpha0002",                                                                  
  "NuGetPreReleaseTagV2":"alpha0002",                                                                
  "NuGetPreReleaseTag":"alpha0002",                                                                  
  "CommitsSinceVersionSource":2,                                                                     
  "CommitsSinceVersionSourcePadded":"0002",                                                          
  "CommitDate":"2016-08-14"                                                                          
}                                                                                                    
```

**Comment by JakeGinnivan** [comment] 2016-10-02 02:21
@tofutim any more info you can provide, I am having trouble reproducing

**Comment by arturcic** [comment] 2019-02-20 12:57
Closing as not reproducible

**Closed by arturcic** 2019-02-20 12:57 UTC
Labels: more-info-needed
