### ISSUE TITLE
Visual Basic My Project\AssemblyInfo.vb supported?

### ISSUE THREAD

**Issue by Pitterling** [GitTools/GitVersion#633] opened 2015-09-04 08:17 UTC
The documentation just talkes about the C# AssemblyInfo file - Properties\AssemblyInfo.cs
http://gitversion.readthedocs.org/en/latest/usage/#msbuild-task

VisualBasic has this information here - My Project\AssemblyInfo.vb

**Comment by JakeGinnivan** [comment] 2015-09-06 23:46
We actually do support AssemblyInfo.vb in the .exe, but not the Task it seems. Happy to receive a PR

**Comment by Pitterling** [comment] 2015-10-04 16:08
It also works for the VB AssemblyInfo file.

**Comment by pascalberger** [comment] 2015-10-11 21:05
This seems like a duplicate of #138. I propose to close this issue and continue discussion in #138.

**Comment by JakeGinnivan** [comment] 2015-10-11 23:22
Agreed

**Closed by JakeGinnivan** 2015-10-11 23:22 UTC
Labels: enhancement, up-for-grabs
