### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by odalet** [GitTools/GitVersion#2315] opened 2020-06-07 16:34 UTC
I am not sure if this is a bug or by design, but I noticed that a project that imports the MSBuild task and that is not part of a local git repository or is part of a git repository with no commits yet has the build fail.

## Expected Behavior

In both cases, the task should default to generate a 0.1.0 version and not fail

## Actual Behavior

In both cases, the build fails.

## Possible Fix

I didn't bother to come up with a fix. Waiting for confirmation this is a bug and not intended behavior. If this is indeed a bug, I'll have a look!

### Case 1 - no git repository

* Create a new solution with a new console application (let's say a C# .NET Core 3.1 app).
* Add the GitVersionTask v5.3.5 nuget package
* Build
* We end up with a buld error `DirectoryNotFoundException: Cannot find the .git directory`
* Here is the build output:

```
1>------ Build started: Project: GitVersionNoRepoTest, Configuration: Debug Any CPU ------
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error : DirectoryNotFoundException: Cannot find the .git directory
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at GitVersion.Extensions.GitVersionOptionsExtensions.GetDotGitDirectory(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Extensions\GitVersionOptionsExtensions.cs:line 18
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at System.Lazy`1.CreateValue()
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at System.Lazy`1.LazyInitValue()
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at System.Lazy`1.get_Value()
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at GitVersion.GitPreparer.Prepare() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 35
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at GitVersion.GitVersionTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitVersionTool.cs:line 59
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at GitVersion.MSBuildTask.GitVersionTaskExecutor..ctor(IGitVersionTool gitVersionTool, IOptions`1 options) in D:\a\GitVersion\GitVersion\src\GitVersionTask\GitVersionTaskExecutor.cs:line 19
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error : --- End of stack trace from previous location where exception was thrown ---
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\GitVersion\GitVersion\src\GitVersionTask\GitVersionTasks.cs:line 24
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :
1>Done building project "GitVersionNoRepoTest.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```
### Case 2 - no commits

* Initialize a git repository in the solution folder with `git init`
* Build again
* The error is now `GitVersionException: No commits found on the current branch.`
* And the log:

```
1>------ Build started: Project: GitVersionNoRepoTest, Configuration: Debug Any CPU ------
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error : GitVersionException: No commits found on the current branch.
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at GitVersion.VersionCalculation.FallbackVersionStrategy.<GetVersions>d__2.MoveNext() in D:\a\GitVersion\GitVersion\src\GitVersionCore\VersionCalculation\BaseVersionCalculators\FallbackVersionStrategy.cs:line 27
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion() in D:\a\GitVersion\GitVersion\src\GitVersionCore\VersionCalculation\BaseVersionCalculator.cs:line 30
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersionCore\VersionCalculation\NextVersionCalculator.cs:line 55
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at GitVersion.GitVersionTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitVersionTool.cs:line 68
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at GitVersion.MSBuildTask.GitVersionTaskExecutor..ctor(IGitVersionTool gitVersionTool, IOptions`1 options) in D:\a\GitVersion\GitVersion\src\GitVersionTask\GitVersionTaskExecutor.cs:line 19
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error : --- End of stack trace from previous location where exception was thrown ---
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\GitVersion\GitVersion\src\GitVersionTask\GitVersionTasks.cs:line 24
1>C:\Users\odalet\.nuget\packages\gitversiontask\5.3.5\build\GitVersionTask.targets(46,9): error :
1>Done building project "GitVersionNoRepoTest.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

## Context

I suppose it would make sense that even if the project is importing GitVersion, it could be built out of a git repository. A classical use case would be a zip of the sources folder excluding `.git`.

## Your Environment

I've reproduced this behavior on;

* Windows 10
* Visual Studio 2019 16.6.1
* Using a C# .NET Core 3.1 Sdk-style project with no modification save for the inclusion of the GitVersion task:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GitVersionTask" Version="5.3.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

**Comment by arturcic** [comment] 2020-06-09 07:22
@odalet, the idea of GitVersion is to obtain a version from the git history, that means you **need** to have a git repository in place (meaning a .git folder) - that's your case 1, and you need to have at least one commit in order for the gitversion be able to compute a version - that's case 2. There is no reason to use GitVersion on a folder that is not versioned with git, and also you need to have at least one commit. That is by design of GitVersion. Closing

**Closed by arturcic** 2020-06-09 07:22 UTC
Labels: bug

**Comment by odalet** [comment] 2020-06-09 12:40
Thanks for the explanations. If that's by design, closed it is!
