### ISSUE TITLE
When running GitVersion on buildserver /output json is ignored

### ISSUE THREAD

**Issue by Philo** [GitTools/GitVersion#675] opened 2015-10-07 15:31 UTC
When running GitVersion on a build server (tested with teamcity), the:

```
/output json
```

parameter is ignored in favour of

```
/output buildserver
```

If an output type is explicitly specified it should be honoured?

**Comment by JakeGinnivan** [comment] 2015-10-07 23:38
It can only be one or the other. /output buildserver writes lots of stuff to stdout, which makes it impossible to output a json file. 

The pull requests relating to the command line changes talk about this.

**Comment by Philo** [comment] 2015-10-08 10:55
I'm not looking to be able to have mulitple output types, but if for example I am running a build on appveyor, but have a custom build process (via gulp) and I am calling gitversion from a gulp task I want gitversion to return the json output via 

```
/output json
```

However when appveyor is detected the json flag is ignored so my gulp task never receives the expected json output from stdout.

**Comment by gep13** [comment] 2015-10-08 11:11
@Philo how exactly are you triggering GitVersion on AppVeyor?

AppVeyor immediately makes the asserted version number available via Environment Variables as you can see here:

https://github.com/chocolatey/ChocolateyGUI/blob/develop/BuildScripts/default.ps1#L440

In my build for ChocolateyGUI.  I call GitVersion using `/output buildserver` and then consume the environment variable for later processing.

Would that work for you?

**Comment by pascalberger** [comment] 2015-10-11 20:32
Calling `/output buildserver` and consuming the environment variables might be best practice in most cases, but shouldn't it still be possible to call `GitVersion.exe /output json` from a gulp task and get the json output to stdout? I don't see why this shouldn't be possible and assume this is a bug, since on buildserver we explicitely call `/output buildserver` which would be useless otherwise.

**Comment by gep13** [comment] 2015-10-12 06:47
@pascalberger oh yeah, I don't disagree on that score.  The request for a json output should definitely be respected.

**Comment by Choc13** [comment] 2015-12-10 16:39
Is there any chance of this issue getting fixed. I'd also like to use `/output json` on a build server from within a gulp task.

**Comment by JakeGinnivan** [comment] 2016-01-17 12:45
This seems to work for me. if I set a environmental variable which triggers the normal service messages then instead do `/output json` then I get the json string.

Can someone let me know how to reproduce

**Comment by JakeGinnivan** [comment] 2016-01-23 04:24
Going to close this, I can only assume it got fixed

The only caviet which may be the source of the issue. If you pass `/project` or `/exec` to gitversion it will always use `/output buildserver`. Not sure why that is, but that logic exists. But there is nothing in there that I can see which would cause the issue. Also a fresh clone of a repo and `$env:APPVEYOR=1` to trigger build server mode still outputs json.

**Closed by JakeGinnivan** 2016-01-23 04:24 UTC

**Comment by JakeGinnivan** [comment] 2016-01-30 00:22
Just a follow up, adding a test in to make sure that it is actually fixed. Which it is :)
