### ISSUE TITLE
[Bug]? NullReferenceException when shallow fetch has been done

### ISSUE THREAD

**Issue by gamblen** [GitTools/GitVersion#3193] opened 2022-09-12 08:53 UTC
**Describe the bug**
Whilst setting up a new Azure DevOps build I was having an issue generating the version using either GitVersion.Tool or the dotnet tool.  Below is the output from GitVersion.Tool.

If I follow the checkout commands on my local machine the error also occurs there.

## Expected Behavior
Possibly an error message that describes the problem.

## Actual Behavior
This is the output from gitversion step

[command]/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/da019c9c-ba14-4306-ab06-9199a5e2c568.sh
INFO [09/09/22 13:54:54:45] Working directory: /home/vsts/work/1/s
INFO [09/09/22 13:54:54:47] Project root is: /home/vsts/work/1/s/
INFO [09/09/22 13:54:54:47] DotGit directory is: /home/vsts/work/1/s/.git
INFO [09/09/22 13:54:54:47] Branch from build environment: refs/heads/feature/Initial
INFO [09/09/22 13:54:54:47] Begin: Normalizing git directory for branch 'refs/heads/feature/Initial'
  INFO [09/09/22 13:54:54:50] One remote found (origin -> 'https://xxxxx@dev.azure.com/xxxx....').
  INFO [09/09/22 13:54:54:51] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [09/09/22 13:54:54:51] Creating local branch feature/Initial
  INFO [09/09/22 13:54:54:57] Creating local branch from remote tracking 'refs/remotes/origin/77abffde6b96a071000e5194052bec43782a4d6b'.
  INFO [09/09/22 13:54:54:58] HEAD points at branch 'refs/heads/feature/Initial'.
  INFO [09/09/22 13:54:54:58] End: Normalizing git directory for branch 'refs/heads/feature/Initial' (Took: 113.34ms)
  INFO [09/09/22 13:54:54:59] Begin: Loading version variables from disk cache
    INFO [09/09/22 13:54:54:59] Cache file /home/vsts/work/1/s/.git/gitversion_cache/08E69C915899EF1F56E6AC3AC025AC81CB27BA3C.yml not found.
  INFO [09/09/22 13:54:54:59] End: Loading version variables from disk cache (Took: 0.33ms)
  INFO [09/09/22 13:54:54:60] Using latest commit on specified branch
  INFO [09/09/22 13:54:54:69] Begin: Attempting to inherit branch configuration from parent branch
  INFO [09/09/22 13:54:54:70] End: Attempting to inherit branch configuration from parent branch (Took: 5.48ms)
  ERROR [09/09/22 13:54:54:74] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle) in /_/LibGit2Sharp/Core/Handles/Objects.cs:line 509
   at LibGit2Sharp.Core.Proxy.git_commit_author(ObjectHandle obj) in /_/LibGit2Sharp/Core/Proxy.cs:line 289
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.LibGit2Sharp.Core.LazyGroup<T>.IEvaluator<TInput>.Evaluate(TInput input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 88
   at LibGit2Sharp.Core.LazyGroup`1.<Evaluate>b__6_0(T input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 36
   at LibGit2Sharp.Core.GitObjectLazyGroup.EvaluateInternal(Action`1 evaluator) in /_/LibGit2Sharp/Core/GitObjectLazyGroup.cs:line 20
   at LibGit2Sharp.Core.LazyGroup`1.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 34
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 80
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.get_Value() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 73
   at LibGit2Sharp.Commit.get_Committer() in /_/LibGit2Sharp/Commit.cs:line 87
   at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 17
   at GitVersion.Commit.<>c.<.ctor>b__3_0(Commit parent) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 16
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Int32 recursions, IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 77
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfigurationInternal(Int32 recursions, IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 54
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 28
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 39
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 37
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 15
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 30
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
  INFO [09/09/22 13:54:54:74] Attempting to show the current git graph (please include in issue): 
  INFO [09/09/22 13:54:54:74] Showing max of 100 commits
  INFO [09/09/22 13:54:54:79] * 77abffd 24 seconds ago  (grafted, HEAD -> feature/Initial, origin/77abffde6b96a071000e5194052bec43782a4d6b, 77abffde6b96a071000e5194052bec43782a4d6b)
* 796f698 5 months ago  (grafted, tag: 0.0.1)

## Steps to Reproduce
The problem stems from the --depth=1
This is the output from the Azure DevOps pipeline checkout step

[command]git version
git version 2.37.3
[command]git lfs version
git-lfs/3.2.0 (GitHub; linux amd64; go 1.18.2)
[command]git init "/home/vsts/work/1/s"
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /home/vsts/work/1/s/.git/
[command]git remote add origin https://xxxx@dev.azure.com/xxxx....
[command]git config gc.auto 0
[command]git config --get-all http.https://xxxx@dev.azure.com/xxxxx.extraheader
[command]git config --get-all http.extraheader
[command]git config --get-regexp .*extraheader
[command]git config --get-all http.proxy
[command]git config http.version HTTP/1.1
[command]git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin --depth=1 +77abffde6b96a071000e5194052bec43782a4d6b:refs/remotes/origin/77abffde6b96a071000e5194052bec43782a4d6b
remote: Azure Repos        
remote: 
remote: Found 549 objects to send. (140 ms)        
Receiving objects: 100% (549/549), 4.41 MiB | 56.49 MiB/s, done.
Resolving deltas: 100% (80/80), done.
From https://dev.azure.com/xxxxx...
 * [new ref]         77abffde6b96a071000e5194052bec43782a4d6b -> origin/77abffde6b96a071000e5194052bec43782a4d6b
 * [new tag]         0.0.1      -> 0.0.1
[command]git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin --depth=1 +77abffde6b96a071000e5194052bec43782a4d6b

this is setup by the hard (by me at least) to find settings.
![AzureDevOps_Shallow-fetch](https://user-images.githubusercontent.com/2478227/189612127-57c0420b-92d2-438d-8ac6-ae0d7a118493.png)

The default seems to be shallow fetch of 1.  Once unselected the build works fine.

## Context
The build stops due to the error.  If it reported that the fetch was too shallow to work, or something along those lines it would have been easier to correct.

## Your Environment
Azure DevOps 
- Version Used: 5.10.3
- Operating System and version Ubuntu 20.04

**Comment by asbjornu** [comment] 2022-09-12 09:18
If you figure out a way we can discover this with LibGit2Sharp, I would warmly welcome a pull request that provides a better exception.

**Comment by gamblen** [comment] 2022-09-12 09:20
@asbjornu I will try.  I just wanted this issue available for any others that might have the same problem.

**Comment by s-krawczyk** [comment] 2022-09-12 20:36
@gamblen thank you! Just had the same issue!

**Comment by BjoernHund** [comment] 2022-09-14 06:31
We have a similar error in our build pipeline. We use a multistage pipeline and the `checkout self` task, without the input parameter `fetchDepth`, to fetch the files from the repository.

Does anyone have an idea how I can override the default behavior?

```
git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin --depth=1 +c4b01c719ea953ffb1bc0e98b8dceb58084a1a70:refs/remotes/origin/c4b01c719ea953ffb1bc0e98b8dceb58084a1a70
```

**Comment by BjoernHund** [comment] 2022-09-14 07:10
> We have a similar error in our build pipeline. We use a multistage pipeline and the `checkout self` task, without the input parameter `fetchDepth`, to fetch the files from the repository.
> 
> Does anyone have an idea how I can override the default behavior?
> 
> ```
> git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin --depth=1 +c4b01c719ea953ffb1bc0e98b8dceb58084a1a70:refs/remotes/origin/c4b01c719ea953ffb1bc0e98b8dceb58084a1a70
> ```

I resolved the problem by setting the `checkout` task in Azure DevOps as followed:

```
- checkout: self
  fetchDepth: 0
```

Maybe you can update your documentation similar to GitHub in your **Requirements** section.

**Comment by michelefa1988** [comment] 2022-09-20 12:55
I had the same issue and the issue below worked for me

It has been very weird since all old pipelines were working but creating a new pipeline seemed to have caused this issue. :(

Troubleshooting has been very painful 
```
- checkout: self
  fetchDepth: 0
```

**Comment by asbjornu** [comment] 2022-09-20 13:22
This is discussed in https://github.com/GitTools/GitVersion/issues/3188#issuecomment-1242358374 and is a change AzDO has done for new repositories. Closing as duplicate of #3188.

**Closed by asbjornu** 2022-09-20 13:22 UTC
Labels: bug
