### ISSUE TITLE
Tasks.json not being updated in build

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#941] opened 2016-07-14 01:24 UTC
It seems the task.json for the VSTS Task is not being updated properly in the build.

The major, minor, patch fields were empty. Putting this here as I don't have time right now to investigate and track it down. If someone wants to look into it and sort it out that would be awesome :smile:

**Comment by pascalberger** [comment] 2016-07-14 08:23
The problem is that `Update-GitVersionTfsTaskVersion.ps1` is not called in the `AfterBuild` target of the GitVersionExe project. This due to `$(GitVersion_SemVer)` not being defined:

```
Task "Exec" skipped, due to false condition; ('$(GitVersion_SemVer)' != '') was evaluated as ('' != '').
```

**Comment by pascalberger** [comment] 2016-07-14 19:35
Ah, I just found out that running `build.ps1` locally and on AppVeyor are different regarding passing version numbers (See [here](https://github.com/GitTools/GitVersion/blob/fd34b7e103c274480a4a4468751a91253c61be1f/build.cake#L37)). 

@gep13 Any reason why we are not passing version info if `build.ps1` is run locally?

**Comment by gep13** [comment] 2016-07-14 20:15
@pascalberger at the end of the day, setting the semantic version of the application is really only **important** when it is on it's way to getting released, i.e. running on AppVeyor.  When running locally it can just be enough to compile and run tests, etc.

**Comment by pascalberger** [comment] 2016-07-15 06:16
@gep13 While applying version is not necessary on local builds, I would prefer to have local and CI builds as equal as possible. Especially for debugging issues like this it would make it much more easy to debug (otherwise you need to adopt the Cake script to be equal to the AppVeyor version)

**Comment by gep13** [comment] 2016-07-15 12:55
@pascalberger yes, I agree, that we want them to be as close as possible, however...

If we updated the version numbers locally, this will result in changes made to the various assemblyinfo, and json files.  How would you want to handle this, as we wouldn't want these files committed as part of any PR's etc.  Would these be placed in the .gitignore file?  This seems wrong to me.

**Comment by pascalberger** [comment] 2016-07-15 18:40
@gep13 Fair point about the changed files. I don't have any better solution at the moment, so probably it's the best way to keep it like it is atm.

**Comment by gep13** [comment] 2016-07-15 20:56
@pascalberger I would love to come up with something better, so happy to discuss further.  Ignoring those files feels wrong to me though, so unless we revert the changes to those files at the end of the build process.

**Closed** 2016-07-16 04:16 UTC
Labels: pr-open
