### ISSUE TITLE
[Bug] DirectoryNotFoundException: Cannot find the .git directory on subst mapped git repo

### ISSUE THREAD

**Issue by ramonsmits** [GitTools/GitVersion#2425] opened 2020-10-14 16:55 UTC
**Describe the bug**

A git repo mapped to a folder the following results in a **DirectoryNotFoundException: Cannot find the .git directory** during compilation:

    subst X: C:\mygitrepo

## Expected Behavior

As the `.git` folder is present in the mapped drive I would not expect this error.

## Actual Behavior

Unexpected exception.

## Context

Unable to work a mapped folder.

## Your Environment

- Version Used: 5.3.5
- Operating System and version (Windows 10, Ubuntu 18.04): Win 10 version 2004
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by asbjornu** [comment] 2020-10-14 21:47
Are "junctions", "`subst` mapped directories" and "symbolic links" different names for the same thing on Windows? If so, this is a duplicate of #2086 and what I wrote there applies here as well: https://github.com/GitTools/GitVersion/issues/2086#issuecomment-626392511

>How are junctions discovered in `System.IO.*`? The only information I can find regarding this deals with the win32 APIs directly, which are out of the question. If you figure out a way to detect junctions in a cross-platform way, we are happy to review and merge a pull request.

**Comment by ramonsmits** [comment] 2020-10-14 21:53
Junctions and symbolic links are I think NTFS features, subst isn't a file-system feature. Also, it is a different error. I don't know, but I'm assuming gitversion tries to travert UP in in the directory hierarchy until it finds a `.git` folder? Maybe its a bigger than 0 vs bigger or equal than 0? I'll check if it works if I map it one folder higher.

**Comment by asbjornu** [comment] 2022-03-08 16:00
Did you find a solution to this, @ramonsmits?

**Comment by ramonsmits** [comment] 2022-03-09 12:47
@asbjornu No, I didn't continue my research and just not subst a git folder :-)

**Comment by asbjornu** [comment] 2022-03-09 13:47
Ok, closing as "workaround found", then. 😃 👍🏼

**Closed by asbjornu** 2022-03-09 13:47 UTC
Labels: bug
