### ISSUE TITLE
Compatibility with TFS 2015 Update 3 RC

### ISSUE THREAD

**Issue by gregpakes** [GitTools/GitVersion#907] opened 2016-06-15 06:05 UTC
I have installed the TFS extension into TFS 2015 Update 3, but it does not appear in the list when I try to add a build step.

Is this a known issue?

**Comment by nZeus** [comment] 2016-06-21 23:12
I have the same problem with VisualStudio Online. It says that extension is installed, but there is no corresponding task available

**Comment by gregpakes** [comment] 2016-06-22 00:44
I fixed this by installing it manually.

**Comment by JakeGinnivan** [comment] 2016-06-22 00:47
As far as I understand it is a two step process. You install it into the collection from the marketplace, then it becomes available to install into the project through the extensions settings on the project.

**Comment by JakeGinnivan** [comment] 2016-06-22 00:47
// @pascalberger

**Comment by gregpakes** [comment] 2016-06-22 00:48
I am aware of this,  I have installed many extensions.  This is not the issue.

**Comment by nZeus** [comment] 2016-06-22 22:17
Sorry guys, but I cannot agree with you. It is an issue.
You can install it mannually on TFS, but not on VisualStudio Online.

In VS Online I could _install_ it (I see it in the list of installed extensions, see screenshot below),
but I cannot find it in the list of available tasks.

![image](https://cloud.githubusercontent.com/assets/2727326/16285658/bda7f296-38d7-11e6-869d-a19dd5162681.png)

![image](https://cloud.githubusercontent.com/assets/2727326/16285672/d22967d6-38d7-11e6-95fb-671361a96f48.png)

If you know how to use it in VS Online, please tell me... :(

**Comment by gep13** [comment] 2016-06-23 06:54
@nZeus assuming I am understanding the issue correctly, I have just installed the extension into my Visual Studio Online account, and I can see that GitVersion Task as follows:

![image](https://cloud.githubusercontent.com/assets/1271146/16294281/a735ff72-3917-11e6-852e-9885dcfb9d63.png)

I didn't previously have the extension installed.

**Comment by pascalberger** [comment] 2016-06-23 07:01
Mmh, strange. I've also successfully running it in different VSTS accounts. I'll try to ping some people at Microsoft to have a look, maybe there is a problem with the specific tenants.

As a workaround see [Manually installing/updating the custom build step](http://gitversion.readthedocs.io/en/latest/build-server-support/build-server/tfs-build-vnext/#manually-installingupdating-the-custom-build-step) using the tfx-cli tool.

**Comment by gregpakes** [comment] 2016-06-23 07:14
The original issue still stands - I cant get it to work in TFS 2015 RC3.

**Comment by pascalberger** [comment] 2016-06-23 07:26
@gregpakes Have you tried installing it manually using the `tfx-cli` tool, as described in the  [Manually installing/updating the custom build step](http://gitversion.readthedocs.io/en/latest/build-server-support/build-server/tfs-build-vnext/#manually-installingupdating-the-custom-build-step) article?

**Comment by nZeus** [comment] 2016-06-23 08:13
@pascalberger, thank you for your help. I can provide all the required information, if necessary

**Comment by gregpakes** [comment] 2016-06-23 08:37
@pascalberger As per my original comment - yes it works with manual upload.

**Comment by pascalberger** [comment] 2016-07-03 19:58
@gregpakes @nZeus This seemed to be an issue in VSTS which [should be fixed by now in VSTS](https://twitter.com/DonovanBrown/status/749683634932633604). Checking if this was also included in TFS Update 3

**Comment by pascalberger** [comment] 2016-07-04 06:09
Unfortunately the fix isn't included in TFS Update 3. I assume it will be included in the next on-prem update, but there's no date confirmed for this yet. I close this issue here, since it seems to be an issue with TFS and not with GitVersion.

**Closed by pascalberger** 2016-07-04 06:09 UTC

**Comment by nZeus** [comment] 2016-07-04 08:22
@pascalberger, I've just tried to uninstall and install it again - **that worked**! Thank you for the help :)
