### ISSUE TITLE
An unexpected error occurred:End: Attempting to inherit branch configuration from parent branch

### ISSUE THREAD

**Issue by IbrahimUmar** [GitTools/GitVersion#3203] opened 2022-09-22 09:22 UTC
Greetings!
                     I moved my project from on prem ADS 2020 to Azure Cloud. The pipeline is not working. The issue with GitVersion Task.

**On prem GitVerison Task:**

- task: GitVersion@5
  inputs:
    runtime: 'core'
    configFilePath: 'GitVersion.yml'

this is working fine.

**Azure Cloud:**

It failed.

Even if i edit this task a little bit accoring to the cloud configs. It failed.

- task: GitVersion@5
  inputs:
    versionSpec: '5.0.0'
    useConfigFile: true
    configFilePath: 'GitVersion.yml'

_Error:End: Attempting to inherit branch configuration from parent branch
  An unexpected error occurred:_

On some sited , it asked me to update GitVerison.Yml file. But what to update. Nothing properly guided.
Even i tried to use the alternative tasks for this verison.
**The setup and Execute:**

- task: gitversion/setup@0
  inputs:
    versionSpec: '5.x.x'

- task: gitversion/execute@0
 
**It failed**.
_INFO [09/22/22 11:18:40:16] End: Attempting to inherit branch configuration from parent branch (Took: 3.81ms)
  ERROR [09/22/22 11:18:40:18] An unexpected error occurred:_

_##[error]SyntaxError: Unexpected end of JSON input_

I have been struggling from last week and unable to found the solution.

I even changed Build agents and go with fresh build machines.
**Why the same build pipeline i working fine on prem and failing on cloud.**

I am unbale to find proper documentation for this.

Can you please guild me how to fix this.

Let me know what the best i can provide you on this.

Regards,
WS

**Comment by asbjornu** [comment] 2022-09-22 09:23
Closing as duplicate of #3188.

**Closed by asbjornu** 2022-09-22 09:23 UTC
Labels: bug
