### ISSUE TITLE
[ISSUE]: GitVersion.MsBuild.targets uses the wrong path for gitversion.dll

### ISSUE THREAD

**Issue by jeroenlandheer** [GitTools/GitVersion#4115] opened 2024-07-24 18:58 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.MsBuild

### GitVersion version

6.0.0

### Operating system

Windows

### What are you seeing?

When I use `GitVersion.MsBuild` v6.0.0 I'm getting this error message:

```
20:48:06 [ERR] C:\Users\****\.nuget\packages\gitversion.msbuild\6.0.0\tools\GitVersion.MsBuild.targets(21,9): error MSB3073: The command "dotnet --roll-forward Major "C:\Users\****\.nuget\packages\gitversion.msbuild\6.0.0\tools\netstandard2.0\gitversion.dll" "[REDACTED]"  -output file -outputfile "[REDACTED]\gitversion.json"" exited with code 1. 
``` 

A quick look in the folder `C:\Users\****\.nuget\packages\gitversion.msbuild\6.0.0\tools` reveals there's no `netstandard2.0` folder in there. (There is `net6.0` and `net8.0`)

### What is expected?

An unbroken build ;)

### Steps to Reproduce

N/A

### RepositoryFixture Test

N/A

**Comment by arturcic** [comment] 2024-07-24 19:00
Duplicate of https://github.com/GitTools/GitVersion/issues/4075

**Closed by arturcic** 2024-07-24 19:00 UTC
Labels: needs triage
