### ISSUE TITLE
appveyor does not test?

### ISSUE THREAD

**Issue by tofutim** [GitTools/GitVersion#970] opened 2016-07-24 13:54 UTC
Hi, looks like appveyor is not testing the support/3.6.0 branch

**Comment by JakeGinnivan** [comment] 2016-07-25 03:05
I suspect this is because it is pointing at the same ref as the 3.6.1 tag. It should build properly once the cache fix PR is merged (that PR built fine)

**Comment by tofutim** [comment] 2016-07-25 16:57
Sorry I mean, it looks like it is  building fine, but does not run the
tests.

**Comment by JakeGinnivan** [comment] 2016-07-26 13:59
It does run the tests I think looking at the logs, the problem is it seems the test results are not being uploaded to AppVeyor so they are not being reported properly.

**Comment by gep13** [comment] 2016-07-26 19:43
@JakeGinnivan there is a bug in Cake with regard to uploading artifacts.  It will be fixed in the upcoming 0.15.0 release, which I am working on just now.

**Comment by asbjornu** [comment] 2019-06-28 00:25
I highly doubt this is relevant anymore. Closing.

**Closed by asbjornu** 2019-06-28 00:25 UTC
