### ISSUE TITLE
AssemblyInfoBuilder namespace should use default namespace as defined in project

### ISSUE THREAD

**Issue by o-o00o-o** [GitTools/GitVersion#558] opened 2015-08-07 10:34 UTC
The namespace generation part of AssemblyInfoBuilder indicates it uses the assembly name by the variable name  assemblyName but actually it uses the project file name. 

Project files can have spaces and other characters that aren't allowed in a namespace. In my project called "Blah Db" the build fails as it tries to create a namespace called "Blah Db" and a namespace cannot have spaces

In fact it shouldn't use either the assemblyName or the project file name it should be using the default namespace as defined in the project.

Please change this to use the actual Default namespace as configured in the project rather than the assembly name. E.g. This is defined in the project file as property RootNamespace

**Comment by JakeGinnivan** [comment] 2015-08-16 06:38
Duplicate of #540 and now fixed via #574 

Will be released in 3.1

**Closed by JakeGinnivan** 2015-08-16 06:38 UTC
