### ISSUE TITLE
[Feature] Unknown language detected: 'wix'

### ISSUE THREAD

**Issue by RDUser-dev** [GitTools/GitVersion#3432] opened 2023-03-09 10:16 UTC
Unable to build a Wix V4 project that uses GitVersion.MSBuild

## Expected Behavior
The project should compile

## Actual Behavior
Compiling generates an error "Unknown language detected: 'wix'"

## Steps to Reproduce

- Install "HeatWave for VS2022", the extension provides templates to create a new Visualstudio Wix V4 project
- Create a new Wix V4 project by going to File>New Project>MSI Package (Wix V4)
- From NuGet install GitVersion.MSBuild 5.12.0
- Commit the project to a Git repository
- Compile the project

## Your Environment 

- Windows 10
- GitVersion.MSBuild 5.12.0
- VS Professional 2022
- HeatWave for VS2022 (VisualStudio extension)

**Comment by arturcic** [comment] 2023-03-09 11:15
I would say this is more like a feature request than a bug, I will change the label

**Comment by RDUser-dev** [comment] 2023-03-09 11:49
> I would say this is more like a feature request than a bug, I will change the label

I thought build of wix projects is currently supported. But maybe I misunderstood.
@arturcic  is it supported only for wix v3?
Thank you

**Comment by arturcic** [comment] 2023-03-09 11:56
Well as far as I can understand this is a new sdk project format, so we cannot support every possible new sdk projects. What I'm aware is we just define as part of MsBuild a couple of `define `, so I suppose custom wix project format we do not support.

To be honest in a v7 version we plan to move out ot the main core project the `support` for different output formats, in this case wix, and make it possible for the community to add support for any format they need, we just provide as input the version variables.

For us it's taking too much time to support every possible outputs, so we would rather offer the community the support of those outputs

**Comment by RDUser-dev** [comment] 2023-03-09 12:03
> Well as far as I can understand this is a new sdk project format, so we cannot support every possible new sdk projects. What I'm aware is we just define as part of MsBuild a couple of `define `, so I suppose custom wix project format we do not support.

I honestly didn't think it was a custom SDK format, but a standard SDK project.

this is the wixproj file 
`<Project Sdk="WixToolset.Sdk/4.0.0-rc.3">
  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Version="5.12.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>`

and this is the Package.Wxs from the generated template
`<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Package Name="Package2" Manufacturer="TODO Manufacturer" Version="1.0.0.0" UpgradeCode="fe4e5214-b5bc-40c4-b233-02ddbe0ac319">
    <MajorUpgrade DowngradeErrorMessage="!(loc.DowngradeError)" />

    <Feature Id="Main">
      <ComponentGroupRef Id="ExampleComponents" />
    </Feature>
  </Package>
</Wix>
`
> 
> To be honest in a v7 version we plan to move out ot the main core project the `support` for different output formats, in this case wix, and make it possible for the community to add support for any format they need, we just provide as input the version variables.
> 
I think it's a good choice

**Comment by arturcic** [comment] 2023-03-09 12:05
> Project Sdk="WixToolset.Sdk/4.0.0-rc.3">

This is what I mean by `custom`. It might introduce new properties/ targets that are not compatible

**Comment by arturcic** [comment] 2023-04-07 11:48
Duplicate of https://github.com/GitTools/GitVersion/issues/2595

**Closed by arturcic** 2023-04-07 11:48 UTC
Labels: improvement
