### ISSUE TITLE
'Version from merge commit' may consider ip from remote-url

### ISSUE THREAD

**Issue by mkoertgen** [GitTools/GitVersion#659] opened 2015-10-02 11:50 UTC
Funny. A merge commit resulting from a standard pull for a remote url specified by ip resulted in a version derived from the ip.

The message of the merge commit was something like

    Merge branch 'develop' of http://10.0.6.3/gitblit/r/.... into develop

This resulted in version `10.1.0` reported on a feature branch.

Interestingly, i tagged with `v1.1.0` two commits behind ans was expecting this version to be reported. I was clearly not aware of the merge commit specified above which was 330 commits behind. 

So this took me a while to figure out. The buildserver output helped then and made it crystal clear where this was coming from.

**Comment by mkoertgen** [comment] 2015-10-02 12:01
Unfortunately, it don't know how to make gitversion prefer the tag instead of the commit message. Because version `10.0.6` wins over the lower versions specified in the tags as documented in [Version source](http://gitversion.readthedocs.org/en/latest/more-info/version-sources/)

I thought i read something about being able to configure the RegExp used for merge messages. But from [looking at the source](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/VersionCalculation/BaseVersionCalculators/MergeMessageBaseVersionStrategy.cs#L45) it seems to be kind of hard-coded in `MergeMessageBaseVersionStrategy.Inner(...)`

I found a `TODO`-comment in the code for configuring the RegExp.

I would love to grab this up unless somebody had an alternative idea or a workaround - other than rewriting my history ;-)

**Comment by asbjornu** [comment] 2015-10-02 12:17
Duplicate of #538, no?

**Comment by mkoertgen** [comment] 2015-10-02 12:25
Yeah, it seems this a perfect match. Thx for pointing that out.

One solution would clearly be to configure a max commit count or an ignore date as [suggested by Jake](https://github.com/GitTools/GitVersion/issues/538#issue-97612595). I think a sensible default will also help bounding the time spent on version calculating when traversing back the history.

Another solution could be to support configuring the RegExp.

**Comment by mkoertgen** [comment] 2015-10-02 12:35
Ok, since #538 is up for grabs i will try to go about this.

**Comment by mkoertgen** [comment] 2015-10-02 12:43
Is it possible to configure the strategies to use? Or how to prioritize them?

**Comment by mkoertgen** [comment] 2015-10-04 12:17
Since i do not want to change the remote-url the solution proposed in #538 won't fix the problem stated here, i.e. ignoring commits before some date. 

Instead i would want to go for making the version RegExp configurable first.

I now start working on adding a failing test for this issue #659

**Comment by mkoertgen** [comment] 2015-10-04 12:37
I added a failing testcase in `MergeMessageBaseVersionStrategyTests.MergeMessagesThatIsNotRelatedToGitVersion` with commit https://github.com/awesome-inc/GitVersion/commit/58dc799b9adcdf01f3beaddf39e035d8f3bfdf4a

If no objections i will try to include a fix before making a pull request. If it cannot be fixed without additional configuration i will add a specific test

**Comment by mkoertgen** [comment] 2015-10-04 12:52
The used regexp is quite involved. The test basically fails because of the leading '/' of 'http://10....'

**Comment by mkoertgen** [comment] 2015-10-04 13:24
In fact, the fix was quite easy to do using a negative lookbehind for '://'.

However, negative lookbehinds are known to be quite costly. 

I saw `gitversion /output buildserver` logging out timing for calculating the version number. 

Anyone some experience with benchmark testing in gitversion?

**Comment by mkoertgen** [comment] 2015-10-04 13:24
Duplicate, of #557 so should fix this as well

**Comment by mkoertgen** [comment] 2015-10-04 13:41
Sadly, the fix here won't fix #443, too since this is related to a different strategy, namely [TaggedCommitVersionStrategy](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/VersionCalculation/BaseVersionCalculators/TrackMergeTargetBaseVersionStrategy.cs).

**Comment by mkoertgen** [comment] 2015-10-04 13:42
Verified that #557 is fixed, too.

Also, https://github.com/GitTools/GitVersion/issues/538#issuecomment-141526150 as well.

**Closed** 2015-10-04 23:10 UTC
