### ISSUE TITLE
[Bug] Not all feature brances are incremented correctly

### ISSUE THREAD

**Issue by amid0** [GitTools/GitVersion#3732] opened 2023-10-23 10:56 UTC
**Describe the bug**
Using gitversion in gitlab pipelines with default configuration.
For some of the branches, versions are not incremented.
For the experiment, I've created two feature branches from the same revision of the main.
Names are 'abc-123-1' and 'abc-123-a'
For the 'abc-123-a' versions are incremented correctly on each commit
For the 'abc-123-1' on first commit in generated version 'v0.1.6-abc-123-1-0001' and that is it. On every next commit version remains the same despite the fact that 'gitversion /updateassemblyinfo' shows the correct branch name and commits count 

{
  "Major": 0,
  "Minor": 1,
  "Patch": 6,
  "PreReleaseTag": "abc-123-1.1",
  "PreReleaseTagWithDash": "-abc-123-1.1",
  "PreReleaseLabel": "abc-123-1",
  "PreReleaseLabelWithDash": "-abc-123-1",
  "PreReleaseNumber": 1,
  "WeightedPreReleaseNumber": 30001,
  "BuildMetaData": 4,
  "BuildMetaDataPadded": "0004",
  "FullBuildMetaData": "4.Branch.feature-abc-123-1.Sha.df2c378a1064d95a3",
  "MajorMinorPatch": "0.1.6",
  "SemVer": "0.1.6-abc-123-1.1",
  "LegacySemVer": "0.1.6-abc-123-1-1",
  "LegacySemVerPadded": "0.1.6-abc-123-1-0001",
  "AssemblySemVer": "0.1.6.0",
  "AssemblySemFileVer": "0.1.6.0",
  "FullSemVer": "0.1.6-abc-123-1.1+4",
  "InformationalVersion": "0.1.6-abc-123-1.1+4.Branch.feature-abc-123-1.Sha.df2c378a1064d95a3",
  "BranchName": "feature/abc-123-1",
  "EscapedBranchName": "feature-abc-123-1",
  "Sha": "df2c378a1064d95a31678bfd785eee101903928d",
  "ShortSha": "df2c378",
  "NuGetVersionV2": "0.1.6-abc-123-1-0001",
  "NuGetVersion": "0.1.6-abc-123-1-0001",
  "NuGetPreReleaseTagV2": "abc-123-1-0001",
  "NuGetPreReleaseTag": abc-123-1-0001",
  "VersionSourceSha": "37510f02ce31ab70dbe8ca81f1d8adf40f6c6d1e",
  "CommitsSinceVersionSource": 4,
  "CommitsSinceVersionSourcePadded": "0004",
  "UncommittedChanges": 0,
  "CommitDate": "2023-10-23"
}

## Expected Behavior
Versions for the feature branch names ending with a number - incremented correctly

## Actual Behavior
Versions for the feature branch names ending with a number - not incremented

## Your Environment
Running in gitlab pipeline under dotnet 

- Version Used: 5.11.1+Branch.support-5.x.Sha.82cbf2c587897ed9906624f3b55f200ac99f084e

**Comment by HHobeck** [comment] 2023-10-24 06:39
Does this happen also in the 6.0.0-beta-3 version?

**Comment by amid0** [comment] 2023-10-24 08:50
> Does this happen also in the 6.0.0-beta-3 version?

Tried it.
And with default configuration, it behaves really strange with feature branches 

What I've done:
 - create a feature branch 
 - made a couple of commits with some changes

Here are outputs of the last pipeline runs

Branch name **feature/abc-123** 
![image](https://github.com/GitTools/GitVersion/assets/6542910/9c1f65fb-d6a0-43fc-bb20-865b11e22634)

Branch name **features/abc-123** 
![image](https://github.com/GitTools/GitVersion/assets/6542910/87f92c1d-60ed-4c77-afb2-e730ddba81e3)

**Comment by HHobeck** [comment] 2023-10-24 09:19
Have you a custom cunfiguration?

If I execute our scenario I got a different result:

```csharp
    [Test]
    public void __Just_A_Test__()
    {
        var configuration = GitFlowConfigurationBuilder.New.Build();

        using EmptyRepositoryFixture fixture = new("main");

        fixture.MakeACommit();

        fixture.BranchTo("feature/abc-123-a");
        fixture.MakeACommit();
        fixture.MakeACommit();

        // ✅ succeeds as expected
        fixture.AssertFullSemver("0.0.1-abc-123-a.1+3", configuration);
    }
```

**Comment by amid0** [comment] 2023-10-24 09:27
Some magic happening
Will try to experiment more on this...

Nothing custom.
here is a output from **dotnet-gitversion /showconfig**

assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
tag-prefix: '[vV]?'
version-in-branch-pattern: (?<version>[vV]?\d+(\.\d+)?(\.\d+)?).*
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
tag-pre-release-weight: 60000
commit-date-format: yyyy-MM-dd
merge-message-formats: {}
update-build-number: true
semantic-version-format: Strict
branches:
  develop:
    label: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    regex: ^dev(elop)?(ment)?$
    source-branches: []
    is-source-branch-for: []
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 0
  main:
    label: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^master$|^main$
    source-branches:
    - develop
    - release
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 5[50](https://gitlab.com/temabit/cap/document-processor-shared/-/jobs/5360155320#L50)00
  release:
    mode: ContinuousDelivery
    label: beta
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^releases?[/-]
    source-branches:
    - develop
    - main
    - support
    - release
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
    pre-release-weight: 30000
  feature:
    mode: ContinuousDelivery
    label: '{BranchName}'
    increment: Inherit
    regex: ^features?[/-]
    source-branches:
    - develop
    - main
    - release
    - feature
    - support
    - hotfix
    is-source-branch-for: []
    pre-release-weight: 30000
  pull-request:
    mode: ContinuousDeployment
    label: PullRequest
    increment: Inherit
    label-number-pattern: '[/-](?<number>\d+)'
    regex: ^(pull|pull\-requests|pr)[/-]
    source-branches:
    - develop
    - main
    - release
    - feature
    - support
    - hotfix
    is-source-branch-for: []
    pre-release-weight: 30000
  hotfix:
    mode: ContinuousDelivery
    label: beta
    increment: Inherit
    regex: ^hotfix(es)?[/-]
    source-branches:
    - release
    - main
    - support
    - hotfix
    is-source-branch-for: []
    is-release-branch: true
    pre-release-weight: 30000
  support:
    label: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^support[/-]
    source-branches:
    - main
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: [55](https://gitlab.com/temabit/cap/document-processor-shared/-/jobs/5360155320#L55)000
  unknown:
    mode: ContinuousDelivery
    label: '{BranchName}'
    increment: Inherit
    regex: .*
    source-branches:
    - main
    - develop
    - release
    - feature
    - pull-request
    - hotfix
    - support
    is-source-branch-for: []
ignore:
  sha: []
mode: ContinuousDeployment
label: '{BranchName}'
increment: Inherit
prevent-increment-of-merged-branch-version: false
track-merge-target: false
track-merge-message: true
commit-message-incrementing: Enabled
regex: ''
source-branches: []
is-source-branch-for: []
tracks-release-branches: false
is-release-branch: false
is-mainline: false

**Comment by amid0** [comment] 2023-10-24 10:18
By the way. 
I see that in version 6.0.0 
NuGetVersion property is missing.
And in my current scenario, with version 5.1.11 we are using NuGetVersion property.
But  FullSemVer always incremented
Maybe we need to think about to switch to the FullSemVer property

**Comment by HHobeck** [comment] 2023-10-24 10:56
Yes correct. NuGetVersion properties are gone in the new version of GitVersion. ;)

**Comment by HHobeck** [comment] 2023-10-24 10:57
Please close this issue if you not mind.

**Closed** 2023-10-24 11:00 UTC
Labels: bug

**Comment by vaceslav** [comment] 2023-11-13 09:28
I have the same problem.

@HHobeck will it be solved in the next beta version or it is just a misconfiguration?

**Comment by amid0** [comment] 2023-11-13 10:44
> I have the same problem.
> 
> @HHobeck will it be solved in the next beta version or it is just a misconfiguration?

As I understand NuGetVersion property will not be present anymore. And need to switch to SemVer or FullSemVer

**Comment by vaceslav** [comment] 2023-11-13 20:19
My question points to the original (first) post on that issue.
The problem is that in all my feature branches (like feature/name-of-the-brach) the property **PreReleaseNumber** has always the value 1.
And because of that the property **SemVer** has always "1" at the end. Independent of how many commits I do in that branch.
Like the author of that issue with his **SemVer** --> **0.1.6-abc-123-1.1**

So the problem is if I create a new commit and push to my feature branch I got always the same SemVer and can't create a new build in the docker registry.

**Comment by HHobeck** [comment] 2023-11-14 07:03
> My question points to the original (first) post on that issue. The problem is that in all my feature branches (like feature/name-of-the-brach) the property **PreReleaseNumber** has always the value 1. And because of that the property **SemVer** has always "1" at the end. Independent of how many commits I do in that branch. Like the author of that issue with his **SemVer** --> **0.1.6-abc-123-1.1**
> 
> So the problem is if I create a new commit and push to my feature branch I got always the same SemVer and can't create a new build in the docker registry.
> 
> The used version is gitversion as docker in version _gittools/gitversion:6.0.0-beta.3-alpine.3.16-6.0_

Hello @vaceslav ,

for your use case the mode property needs to be set to `ContinuousDeployment` (see Reference[1]):

![image](https://github.com/GitTools/GitVersion/assets/56404113/137bb363-0ac4-4f2e-b469-47516a12510b)

Please keep in mind that we have agreed on redefining the meaning of this enum. This change will come soon or later. https://github.com/GitTools/GitVersion/discussions/3601#discussioncomment-7389954

Happy Branching!

Reference[1]: https://gitversion.net/docs/reference/version-increments

**Comment by vaceslav** [comment] 2023-11-14 07:37
That is exactly what I need.
Thank you for your support.
