### ISSUE TITLE
Minor increment on develop branch

### ISSUE THREAD

**Issue by jeusdi** [GitTools/GitVersion#1064] opened 2016-10-07 12:45 UTC
I'm an absolutly newbie using gitVersion. According to default branch configuration: 

``` yaml
develop:
    regex: dev(elop)?(ment)?$
    mode: ContinuousDeployment
    tag: unstable
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    is-develop: true
    is-release-branch: false
```

I don't quite to figure out what `increment: Minor` means.

I've just created a repository, I've just tagged first master commit with v0.1 and then I've branched it off to develop and I've created 4 commits. `GitVersion` information is telling me:

``` json
{
  "Major":0,
  "Minor":1,
  "Patch":0,
  "PreReleaseTag":"unstable.4",
  "PreReleaseTagWithDash":"-unstable.4",
  "PreReleaseLabel":"unstable",
  "PreReleaseNumber":4,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.develop.Sha.9b952d58f746cb47e7589a07da65c79ed87fae88",
  "MajorMinorPatch":"0.1.0",
  "SemVer":"0.1.0-unstable.4",
  "LegacySemVer":"0.1.0-unstable4",
  "LegacySemVerPadded":"0.1.0-unstable0004",
  "AssemblySemVer":"0.1.0.0",
  "FullSemVer":"0.1.0-unstable.4",
  "InformationalVersion":"0.1.0-unstable.4+Branch.develop.Sha.9b952d58f746cb47e7589a07da65c79ed87fae88",
  "BranchName":"develop",
  "Sha":"9b952d58f746cb47e7589a07da65c79ed87fae88",
  "NuGetVersionV2":"0.1.0-unstable0004",
  "NuGetVersion":"0.1.0-unstable0004",
  "CommitsSinceVersionSource":4,
  "CommitsSinceVersionSourcePadded":"0004",
  "CommitDate":"2016-10-07"
}
```

According to last default configuration, develop branch must to increment `Minor` field, mustn't it?

**Comment by AGBrown** [comment] 2016-10-11 12:04
@jeusdi out of interest what was the exact tag you used? `v0.1` or `v0.1.0`?

_Sidebar: I don't suppose it really matters but your `regex: dev(elop)?(ment)?$` will match [quite a few more things](http://regexr.com/3edqu) than you probably intended._

**Comment by NickMoores** [comment] 2016-11-29 18:19
Is this expected behaviour?

I was expecting the "Minor" variable to increment from 1 to 2 with the above configuration.  Specifically, I thought the combination of ContinuousDeployment mode (which would bump the version on every commit) and Minor increment (which would increment the _minor_ version every time it is bumped) would do this.

I'm able to reproduce the above behaviour, but it wasn't what I was expecting.

**Comment by gep13** [comment] 2016-11-29 18:28
>@NickMoores said...
I'm able to reproduce the above behaviour, but it wasn't what I was expecting.

Is this a public repo that you can point us at?

**Comment by NickMoores** [comment] 2016-11-29 21:35
Yep: https://github.com/NickMoores/gitversion-test

My steps were:

1.  Create repository in GitHub with Visual Studio .gitignore.
2.  Clone via Visual Studio.
3.  Go to root folder of cloned repository, and run "gitversion init"
- Run getting started wizard.
- Choose GitFlow (or similar).
- Choose continuous delivery mode.
- Save changes and exit.
4.  Create empty Visual Studio solution file.
5.  Commit changes to master branch.
6.  Create dev branch from master, and checked out dev branch.
7.  Added console app to solution.
8.  Checked in changes to dev branch.
9.  Installed GitVersionTask from nuget package to console project.
10.  Checked in changes to dev branch.
11. Ran GitVersion from command line to view output variables, and observed that Minor version was still "1".

**Comment by gep13** [comment] 2016-11-30 10:35
@NickMoores so, just so we are clear... what are you expecting the Minor version to be?

The branch structure you have suggests that you want to use GitFlow, but then you have set the mode to be ContinuousDelivery.  Have you read this:

http://gitversion.readthedocs.io/en/latest/reference/continuous-delivery/

>Continuous delivery does not work well with GitFlow. The reason is that you are required to merge to master to do a release, triggering a rebuild and a new set of artifacts to go through your pipeline. Depending on how long your pipeline is, this could be a while.

**Comment by NickMoores** [comment] 2016-11-30 11:01
@gep13 I was expecting it to be 3, because I had performed two commits on the dev branch.

I have read that URL, but my main point of reference was this:

http://gitversion.readthedocs.io/en/latest/more-info/version-increments/

> If you are using GitFlow then builds off the develop branch will actually increment on every commit. This is known in GitVersion as continuous deployment mode. By default develop builds are tagged with the alpha pre-release tag. This is so they are sorted higher than release branches.

I actually just tried changing the mode in my GitVersion.yml to ContinuousDeployment, but the Minor version stayed at 1 on the dev branch (even after subsequent commits).

**Comment by gep13** [comment] 2016-11-30 11:04
@NickMoores depending on the version of GitVersion you are using, the GitVersion cache isn't cleared out after making changes to your configuration file.  I would suggest clearing out the `.git\gitversion_cache` folder, and trying running it again.

**Comment by gep13** [comment] 2016-11-30 11:09
@NickMoores also, perhaps the wording in that quote isn't the best.  The semantic version number of each commit is incrementing, in the sense that: 0.1.0-alpha.1, will go to 0.1.0-alpha.2, and then 0.1.0-alpha.3, however, the minor version number will not change until a tag is applied to the master branch, after a release has happened.

**Comment by NickMoores** [comment] 2016-11-30 11:35
@gep13 Thanks.  I've just tried merging to master, applying a "v0.2.0" to the merged commit, and then going back to dev and committing, but no change to the minor version.

Also bizarrely, the SemVer is still 0.1.0 despite applying the v0.2.0 tag.  I've updated the repo @ https://github.com/NickMoores/gitversion-test to demonstrate.

I'm using gitversion from chocolatey (installed yesterday), and have cleared out my gitversion cache.

**Comment by gep13** [comment] 2016-11-30 11:42
The issue you are seeing is due to the tag name you have chosen.

You are using `v.0.2.0` and GitVersion doesn't recognise that as valid.  If you instead switch the tag to `v0.2.0` and switch to the dev branch, you should see:

![image](https://cloud.githubusercontent.com/assets/1271146/20751140/1dc4641e-b6f2-11e6-944e-23113a1156b7.png)

**Comment by gep13** [comment] 2016-11-30 11:43
@NickMoores which is what I "think" you are after, right?

**Comment by NickMoores** [comment] 2016-11-30 12:01
@gep13 Ah, silly mistake with the tag name, thanks for pointing out!

Re-reading your comments, I think this makes sense now.  I was expecting the minor version number to increment on every commit to the dev branch, instead of after a tag is applied to the master branch, but that wouldn't really make sense as a workflow.  I understand that it's the **semantic version** that's increasing with each commit, not the minor version number.

Thanks, Gary!

**Comment by gep13** [comment] 2016-11-30 12:07
@NickMoores not a problem at all.  There are configuration options to allow the bumping of the patch number on each commit, but that isn't something that I tend to do.  I almost always use GitFlow, and OOTB, GitVersion handles this really well.

**Comment by asbjornu** [comment] 2019-06-28 00:46
This looks like an answered question to me. Closing.

**Closed by asbjornu** 2019-06-28 00:46 UTC
