### ISSUE TITLE
Version in develop branch is ahead of master?

### ISSUE THREAD

**Issue by mhchristensen** [GitTools/GitVersion#1346] opened 2017-12-11 20:22 UTC
Really liking this tool.  Great work!

Using the GitVersion.3.6.5 nuget package, running builds with GitLabCI, GitLab Runner on a windows server, and MSBuild.

The version was initialized by applying a tag in the develop branch 'v4.1.3'  

We have a pipeline to deploy the develop branch to a develop site, and the master branch to a qa site.

Everything works great and the versions were being incremented.

When we merged develop into master and let the deploy take place we found that the version seems to have gone backwards.  Develop is at 4.2.0 and Master is deployed as 4.1.4

Is this a configuration problem or a bug in GitVersion?  It seems that if master has everything develop has, the version should be equal or higher?  Or is this default behavior  that it assumes develop will be a minor version higher?

**Comment by JakeGinnivan** [comment] 2017-12-12 03:09
Can you try v4 beta. It's actually quite stable and hopefully will be released over the christmas break when i have some time to write up the release notes for the really long extended beta period :)

**Comment by mhchristensen** [comment] 2017-12-12 06:51
@JakeGinnivan  thanks for reply!  So you think this is a bug?  Or v4 beta has a new feature to address this?

**Comment by asbjornu** [comment] 2018-03-09 22:20
@mhchristensen: `develop` being at `4.2.0` when `master` is at `4.1.4` is not a bug, it's how GitVersion is supposed to work. Unstable branches should always mint version numbers that are higher than the latest `master`. The version numbers on other branches are sort of "predicting" the next version number that `master` is going to produce. So this is the correct behavior.

You can change what part of the version number each branch changes (`Major`, `Minor` or `Patch`) with the [`increment` configuration property](http://gitversion.readthedocs.io/en/latest/configuration/#increment).

**Closed by asbjornu** 2018-03-09 22:20 UTC
