### ISSUE TITLE
[Bug] #2167 breaks building WPF applications

### ISSUE THREAD

**Issue by batzen** [GitTools/GitVersion#2181] opened 2020-03-15 01:11 UTC
**Describe the bug**
The fixes made for #2167 seem to break building WPF applications because version attributes are added as duplicates.

## Expected Behavior
Build should work and assembly info should not have duplicate attributes.

## Actual Behavior
Assemblyinfo has duplicate version attributes.

## Possible Fix
`MarkupCompilePass1DependsOn` should not be modified to contain `UpdateAssemblyInfo`.

## Steps to Reproduce
- Clone https://github.com/snoopwpf/snoopwpf
- Compile

## Context
Tried to compile with the latest gitversiontask version.
Version 5.2.2 works fine. Only 5.2.3 shows this issue.

## Your Environment
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

- Version Used: 5.2.3
- Operating System and version (Windows 10): 1909
- Link to your project: https://github.com/snoopwpf/snoopwpf
- Link to your CI build (if appropriate):

**Comment by arturcic** [comment] 2020-03-15 06:09
@tpaxatb can you check this bug?

**Comment by tpaxatb** [comment] 2020-03-16 15:57
Yeah I realized after the fact that netcore apps seem to build slightly different (i didn't have netcore 3 sdk until friday). I think maybe on the .net core that the UpdateAssemblyInfo should be turned off in the props file or something.  I'll see about taking a look later if/when I get a chance, as our office is in the process of transforming to mandatory work at home due to government directives yesterday and today.

**Comment by arturcic** [comment] 2020-03-16 16:15
Sure, take your time, any help is welcomed

**Comment by bording** [comment] 2020-03-16 19:59
Looks like the PR I just opened should fix this: #2183

**Comment by arturcic** [comment] 2020-03-16 20:02
@bording, ok then, after we merge your PR we will validate it here

**Comment by arturcic** [comment] 2020-04-18 14:28
closing, please reopen if still reproduces

**Closed by arturcic** 2020-04-18 14:28 UTC
Labels: bug
