### ISSUE TITLE
[Bug] Version is not incrementing after updating

### ISSUE THREAD

**Issue by PatrickBig** [GitTools/GitVersion#2694] opened 2021-05-17 19:17 UTC
**Describe the bug**
Currently have my repo configured as follows:

```yaml
mode: Mainline
next-version: 0.2.1
branches: {}
ignore:
  sha: []
merge-message-formats: {}
```

I recently updated my GitVersion tool from **5.3.7** to **5.6.9**

Here is the output from `dotnet-gitversion`

```json
{
  "Major": 0,
  "Minor": 2,
  "Patch": 1,
  "PreReleaseTag": "751",
  "PreReleaseTagWithDash": "",
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": null,
  "WeightedPreReleaseNumber": 60000,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.main.Sha.8e4422fa08dafca389e35409b667968cbdebd972",
  "MajorMinorPatch": "0.2.1",
  "SemVer": "0.2.1",
  "LegacySemVer": "0.2.1",
  "LegacySemVerPadded": "0.2.1",
  "AssemblySemVer": "0.2.1.0",
  "AssemblySemFileVer": "0.2.1.0",
  "FullSemVer": "0.2.1",
  "InformationalVersion": "0.2.1+Branch.main.Sha.8e4422fa08dafca389e35409b667968cbdebd972",
  "BranchName": "main",
  "EscapedBranchName": "main",
  "Sha": "8e4422fa08dafca389e35409b667968cbdebd972",
  "ShortSha": "8e4422f",
  "NuGetVersionV2": "0.2.1",
  "NuGetVersion": "0.2.1",
  "NuGetPreReleaseTagV2": "",
  "NuGetPreReleaseTag": "",
  "VersionSourceSha": "5ff1ca8733e4fcc1ad09dff89908bfd9ad485451",
  "CommitsSinceVersionSource": 751,
  "CommitsSinceVersionSourcePadded": "0751",
  "UncommittedChanges": 0,
  "CommitDate": "2021-05-17"
}
```

The pre-release tag is pretty big

## Expected Behavior
I expect the GitVersion to be outputting **0.4.14**

## Actual Behavior
After updating is is reporting as **0.2.1**, which is the option set in `next-version`

## Possible Fix
It looks like the pre-release tag is incrementing but merges to master are no longer counted.

## Steps to Reproduce
Unsure how to re-produce.

## Context
I can no longer version my application. It's stuck at the configured `next-version`

## Your Environment
Using `dotnet-gitversion` on both windows workstations and linux build servers. Output is the same.

- Version Used:
- **5.3.7** 
- **5.6.9**

**Comment by asbjornu** [comment] 2021-05-18 12:14
Duplicate of #2441. Please remove `next-version` and add a `git tag` with the same version number, on the appropriate tag.

**Closed by asbjornu** 2021-05-18 12:14 UTC
Labels: bug

**Comment by PatrickBig** [comment] 2021-05-18 13:41
Thanks! That solved it for me!
