### ISSUE TITLE
[Bug] GitVersion.GitVersionException: Cannot find commit

### ISSUE THREAD

**Issue by fabricesemti80** [GitTools/GitVersion#3204] opened 2022-09-23 09:53 UTC
**Describe the bug**

Hi there!

I have imported this repo into Azure Devops <https://github.com/dsccommunity/DscWorkshop> , following the instructions in this. 
While I appreciate this repo is not your work, the error that I am observing is from `Gitvesion` .

```yaml
          - pwsh: |
              dotnet tool install --global GitVersion.Tool

              Write-Output "dotnet version ->"
              dotnet-gitversion
              Write-Output "<- dotnet version"

              $gitVersionObject = dotnet-gitversion | ConvertFrom-Json
              $gitVersionObject.PSObject.Properties.ForEach{
                  Write-Host -Object "Setting Task Variable '$($_.Name)' with value '$($_.Value)'."
                  Write-Host -Object "##vso[task.setvariable variable=$($_.Name);]$($_.Value)"
              }
              Write-Host -Object "##vso[build.updatebuildnumber]$($gitVersionObject.FullSemVer)"
            displayName: Calculate ModuleVersion (GitVersion)
```

(I just added the `Write-Output` sections to see what dotnet-gitversion actually does, otherwise the code is as per https://github.com/dsccommunity/DscWorkshop/blob/main/azure-pipelines.yml )

## Expected Behavior

output of `dotnet-gitversion` is piped to powershell for `| ConvertFrom-JSON`

## Actual Behavior

output is not passed. I am observing this error:

```

  INFO [09/23/22 9:26:50:55] One remote found (origin -> 'https://ABL-Windows-Sandbox@dev.azure.com/ABL-Windows-Sandbox/dsc-workshop/_git/dsc-workshop').
  INFO [09/23/22 9:26:50:55] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [09/23/22 9:26:50:56] Creating local branch main
  INFO [09/23/22 9:26:50:62] Creating local branch from remote tracking 'refs/remotes/origin/360b621d9d45db5b05acc094cd67672461afad26'.
  INFO [09/23/22 9:26:50:63] HEAD points at branch 'refs/heads/main'.
  INFO [09/23/22 9:26:50:63] End: Normalizing git directory for branch 'refs/heads/main' (Took: 122.46ms)
  INFO [09/23/22 9:26:50:65] Begin: Loading version variables from disk cache
    INFO [09/23/22 9:26:50:65] Cache file D:\a\1\s\.git\gitversion_cache\C5FDD9B82DAE4F2FAAE360991B27B798CA3C5063.yml not found.
  INFO [09/23/22 9:26:50:65] End: Loading version variables from disk cache (Took: 0.39ms)
  INFO [09/23/22 9:26:50:65] Using latest commit on specified branch
  INFO [09/23/22 9:26:50:77] Running against branch: main (360b621 Updated azure-pipelines.yml)
  INFO [09/23/22 9:26:50:77] Begin: Calculating base versions
    INFO [09/23/22 9:26:50:79] NextVersion in GitVersion configuration file: 0.0.1 with commit count source External Source
  INFO [09/23/22 9:26:50:80] End: Calculating base versions (Took: 26.88ms)
  ERROR [09/23/22 9:26:51:03] An unexpected error occurred:
GitVersion.GitVersionException: Cannot find commit 360b621 Updated azure-pipelines.yml. Please ensure that the repository is an unshallow clone with `git fetch --unshallow`.
 ---> LibGit2Sharp.NotFoundException: object not found - no match for id (8d07377738cf579ba4d686c201453f41b68d1310)
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_revwalk_next(RevWalkerHandle walker) in /_/LibGit2Sharp/Core/Proxy.cs:line 2774
   at LibGit2Sharp.CommitLog.CommitEnumerator.MoveNext() in /_/LibGit2Sharp/CommitLog.cs:line 140
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitVersion.RepositoryStore.GetBaseVersionSource(ICommit currentBranchTip) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 67
   --- End of inner exception stack trace ---
   at GitVersion.RepositoryStore.GetBaseVersionSource(ICommit currentBranchTip) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 71
   at GitVersion.VersionCalculation.FallbackVersionStrategy.GetVersions()+MoveNext() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculators\FallbackVersionStrategy.cs:line 23
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersions(IVersionStrategy strategy)+MoveNext() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculator.cs:line 102
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculator.cs:line 31
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 52
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
  INFO [09/23/22 9:26:51:03] Attempting to show the current git graph (please include in issue): 
  INFO [09/23/22 9:26:51:03] Showing max of 100 commits
  INFO [09/23/22 9:26:51:09] * 360b621 49 seconds ago  (grafted, HEAD -> main, origin/360b621d9d45db5b05acc094cd67672461afad26, 360b621d9d45db5b05acc094cd67672461afad26)

<- dotnet version
```

## Steps to Reproduce

Follow steps documented here: https://github.com/dsccommunity/DscWorkshop/blob/main/Exercises/Task3/Exercise2.md

## Your Environment

Azure Devops (tried with `windows-2019`, `windows-2022` and `ubuntu` runners

- Version Used:
- Operating System and version (Windows 10, Ubuntu 18.04):
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by asbjornu** [comment] 2022-09-23 10:24
Closing as duplicate of #3188.

**Closed by asbjornu** 2022-09-23 10:24 UTC
Labels: bug
