### ISSUE TITLE
Per-folder configuration for monorepo support

### ISSUE THREAD

**Issue by AndreiMarukovich** [GitTools/GitVersion#1268] opened 2017-07-27 18:57 UTC
One way of using Git repository is to put multiple projects in the subfolders of one repository (monorepo). In this case it is desirable to version these projects independently, based on the commits in the corresponding folders. 

How feasible is to introduce a additional mode for GitVersion to track not only the branches, but folders as well?

**Comment by asbjornu** [comment] 2017-08-02 07:49
I highly doubt this is a use-case we want to support in GitVersion. First, it would be very hard and probably introduce loads of bugs. Second, it's kind of a worst-practice use of Git and something you should avoid at all cost.

**Comment by asbjornu** [comment] 2017-08-02 07:54
Duplicate of #1170.

**Closed by asbjornu** 2017-08-02 07:54 UTC

**Comment by Jaykul** [comment] 2022-01-07 17:50
This is **not** a duplicate of #1170 because it's not enough to support multiple gitversion.yml files

**Comment by Nakzz** [comment] 2022-02-08 01:06
Any update on this?

**Comment by asbjornu** [comment] 2022-02-09 12:41
Nope, @Nakzz. I don't understand or need the use-case and no one else who does have contributed code to implement it.

**Comment by ichbestimmtnicht** [comment] 2022-07-01 07:24
Well I have a use case for you: The https://moleculer.services Framework. It has a monorepo structure by default and you build services within folders that then get bundled together. So it makes little sense to split up the repo but helps to have different internal versions from a development side for a compatibility matrix when working with multiple teams at the same time for example.

**Comment by asbjornu** [comment] 2022-07-01 09:46
It’s not the lack of use-cases that is the limiting factor in this being implemented and supported by GitVersion, it’s the lack of code contributions from people like you who are using monorepos, @ichbestimmtnicht. 

The current maintainers of GitVersion does not use, nor recommend the use, of monorepos. Personally, I view it as an anti-pattern. Therefore, we have no incentive to implement support for monorepos. As a matter of fact, since we aren’t using monorepo ourselves, the incentive to **not** support monorepo is much greater than to support it.

However, if someone who wants to champion monorepo support into GitVersion steps up, contributes the necessary code and tests as well as future maintenance of said feature, I’m not against merging it. 

But so far, no such code have been contributed and therefore GitVersion does not support it.

**Comment by jwittner** [comment] 2022-11-10 17:31
As a follow up, I was able to version multiple things out of a single repository by having separate GitVersion-<API>.yml files and running the tools with explicit references to which API I was computing. Working out well in several repositories that have multiple versioned _things_ in them. I also add prefixes to the version tags, e.g. <API>-v1.0.0.

I think this achieves the goal of what you propose, though I have to admit I expected to be able to do it in the repository's configuration file as well. It would have probably saved me a bunch of time. =)

**Comment by cmeyertons** [comment] 2022-11-10 21:53
@jwittner do you mind specifying _how_ you made the explicit references to `API`?

I can't get it to work w/ `tag-prefix` and am unsure of after reading and re-reading the docs, am unsure of how you did so.

Here's my config:

```yml
next-version: 0.1.0
increment: Inherit
# continuous-delivery-fallback-tag: ci
tag-prefix: 'MyAPI'
commit-message-incrementing: Disabled
update-build-number: true
```

**Comment by jwittner** [comment] 2022-11-11 01:24
For a version tagged e.g. `MyApi-v1.0.0`, you'd want something like the below. I've added customized bump messages for the `api` as well, though I see you have it disabled in your config. 

I'm invoking the tooling in PowerShell through the dotnet cli and using the JSON output rather than the `/output buildServer` flag to do my own setup (due to conversion from legacy system). 

> Note: I've seen bad behavior from `next-version`.
> Note: I've seen bad behavior if you create tags with versions containing 'prerelease' strings.

```yaml
tag-prefix: 'MyAPI-v'
major-version-bump-message: '\+myapi-semver:\s?(breaking|major)'
minor-version-bump-message: '\+myapi-semver:\s?(feature|minor)'
patch-version-bump-message: '\+myapi-semver:\s?(fix|patch)'
no-bump-message: '\+myapi-semver:\s?(none|skip)'
```

**Comment by jwittner** [comment] 2022-11-11 01:34
The commit message incrementing is awesome for having your feature branches predict the next version. 

Our projects also have slightly different message regex than above, which checks for specific strings known to be in the Pull Request template so that we can control the final version through the Pull Request description itself which has made thing so easy now!

```yaml
major-version-bump-message: '(\+myapi-semver:\s?(breaking|major)|\[x\] an API breaking change in MyAPI)'
minor-version-bump-message: '(\+myapi-semver:\s?(feature|minor)|\[x\] an API addition to MyAPI)'
```

**Comment by AlexeyRaga** [comment] 2023-06-14 12:17
@jwittner has it been already implemented somewhere?

**Comment by jwittner** [comment] 2023-06-15 15:57
> @jwittner has it been already implemented somewhere?

Sorry, has what been implemented? I don't think per folder configuration in a single GitVersion.yaml has been added, but my work around above details how to support different versions from a single repo via different GitVersion-<api>.yaml files. This is working well for us in several repos in practice.

**Comment by tkrafael** [comment] 2023-07-04 17:06
What I understood is:
1. Every folder has a project and a GitVersion.yml file
2. Inside GitVersion, there's a configuration which tells gitversion to assume tags containing a prefix (eg: myapi-*)
3. When it's time to get correct version, a call is made to GitVersion.exe telling where the file is. Gitversion is smart to account tags prefixed with the name that's configured in GitVersion.yml file and correctly calculate next version.
I don't think that will cover all scenarios like feature branching, because once you create a feature branch to change another folder, when running CI/CD against all folders, gitversion will increment the prerelease value.

I think @jwittner would add more information.

**Comment by pratik98** [comment] 2024-12-29 11:34
@jwittner did you document your setup somewhere on the internet? i think it would be of great help to the people in similar situation.

**Comment by raffidahmad** [comment] 2025-01-14 08:56
Looking for a solution to this as well

**Comment by FACOLOMBANI** [comment] 2025-01-17 09:06
Is it possible to have a working example?

**Comment by jwittner** [comment] 2025-01-21 20:39
No documentation I can share unfortunately - but the concept is straightforward. Use a different gitversion config file for each configuration you need. Use scripts to pass the right config to gitversion (using /config argument documented here: https://gitversion.net/docs/usage/cli/arguments) whenever you need to invoke it.

**Comment by julealgon** [comment] 2025-07-25 22:44
@jwittner what about the issue of considering only commits inside of the component's subfolder for automatic version increments? Is there any way to achieve that without having to create completely custom detection rules per component via specific `major-version-bump-message` and `minor-version-bump-message` overrides?

I have a repo with dozens of individually versioned components that I'd like to apply this to but having to create distinct prefixes for custom `*-bump-message` overrides would make writing the commit messages a very cumbersome and error-prone process.

Is there any way to achieve this by doing a "partial checkout" of some sort, so that only a component's subfolder is retrieved (or something similar), while keeping a unified `*-bump-message` pattern?

**Comment by jwittner** [comment] 2025-08-21 17:44
That definitely seems hard to measure and you might need to make code changes to GitVersion to enable that. No easy wins for checking what subfolders were involved in each commit and counting differently come to mind for me.
