### ISSUE TITLE
The commit-message-incrementing option doesn't seem to be respected on mainline

### ISSUE THREAD

**Issue by KwiatkowKamil** [GitTools/GitVersion#2926] opened 2021-11-30 09:35 UTC
This is my GitVersion file:

```yml
mode: Mainline
commit-message-incrementing: Disabled
branches:
  develop:
    tag: alpha
    increment: Patch
  release:
    tag: beta
  feature:
    tag: useBranchName
  hotfix:
    increment: None
    tag: hotfix
ignore:
  sha: []
```
This is the output of the gitversion-diag on master:
[gitversion_diag.txt](https://github.com/GitTools/GitVersion/files/7624549/gitversion_diag.txt)

I don't understand the line 
`INFO [11/30/21 10:28:32:43] Merge commit 8bb4346 Merge branch 'release/1.1.0' incremented base versions Patch, now 1.1.1`
Why is a commit message +semver: Patch respected if the option for it is Disabled?

## Expected Behavior
The version number should not be manually incremented with the setting `commit-message-incrementing: Disabled`.

## Actual Behavior
It is possible to increment manually even though it should be prohibited by the setting.

## Your Environment
I'm using the CLI from choco, version 5.8.1.

**Comment by HHobeck** [comment] 2023-03-20 10:27
It's a good question actually but we have done alot of work and it's not clear for me if this issue persists. I'm going to close it because there are no steps to reproduce. Please use the latest pre-release version and verify your scenario again... it might be solved. If not please re-open this issue or create a new bug. Thank you very much.

**Closed by HHobeck** 2023-03-20 10:27 UTC
Labels: bug
