### ISSUE TITLE
GitVersionTask uses the project name as the namespace name in GitVersionTaskAssemblyInfo instead of default namespace value

### ISSUE THREAD

**Issue by wasabii** [GitTools/GitVersion#597] opened 2015-08-20 19:11 UTC
When using GitVersionTask in a project named 'foo-bar', the GitVersionTaskAssemblyInfo.g.cs file contains a namespace declaration:

`namespace foo-bar
{
`

This fails because - is apparently not allowed in namespace names.

**Comment by wasabii** [comment] 2015-08-20 19:14
Problem is it's not using the default namespace of the project, and is instead just using the project name.

**Comment by gep13** [comment] 2015-08-21 06:22
@wasabii I believe that this is a duplicate of this issue https://github.com/GitTools/GitVersion/issues/558

Which has been resolved and will be released in 3.1.  If you wanted to give it a try, you should be able to compile the application manually, and run the exe.

**Closed** 2015-08-21 08:00 UTC
