### ISSUE TITLE
[ISSUE] Error: system.AggregateException: One or more errors occurred. (GitVersion: Process returned an error (exit code -532462766).) in Azure devops pipeline (Microsoft host agent))

### ISSUE THREAD

**Issue by PraveenRsys** [GitTools/GitVersion#4270] opened 2024-10-24 11:24 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task, GitVersion.Tool, GitVersion.MsBuild

### GitVersion version

Git 2.39.1 and 2.45.2

### Operating system

Windows

### What are you seeing?

I'm getting Error: System.AggregateException: One or more errors occurred. (GitVersion: Process returned an error (exit code -532462766).) in Azure devops build pipeline (Microsoft host agent). The same build was working fine but we are getting error as the git version is changes from 2.39.1 to 2.45.2 in Microsoft host agent windows image.

Please help us to get the build issue resolved

### What is expected?

Please help us to get the issue resolved caused by changing the gitversion in Microsoft host agent 

### Steps to Reproduce

same build worked with gitversion git 2.39.1 used by Microsoft host agent "Windows-2019" but gitversion is upgraded to git 2.45.2 in same Microsoft host agent Windows-2019 image which causing the issue

**Comment by HHobeck** [comment] 2024-10-25 07:01
Please analyze you problem in more detail and find the root cause. `System.AggregateException: One or more errors occurred.` is not very expressive. I'm going to close this issue.

Thank you for your understanding.

**Closed by HHobeck** 2024-10-25 07:01 UTC
Labels: needs triage
