### ISSUE TITLE
Unable to update package from 5.1.0 to 5.1.3

### ISSUE THREAD

**Issue by NameOfTheDragon** [GitTools/GitVersion#2106] opened 2020-02-15 20:21 UTC
When I try to do a NuGet update from 5.1.0 to 5.1.3, I get the following output:

```lang=txt
Attempting to gather dependency information for package 'GitVersionTask.5.1.3' with respect to project 'TA.SnapCap.Aspects', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 297.68 ms
Attempting to resolve dependencies for package 'GitVersionTask.5.1.3' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'GitVersionTask.5.1.3'
Resolved actions to install package 'GitVersionTask.5.1.3'
Removed package 'GitVersionTask.5.1.0' from 'packages.config'
Install failed. Rolling back...
Package 'GitVersionTask.5.1.0' already exists in folder 'C:\Users\Tim\source\repos\ta.snapcap\packages'
Added package 'GitVersionTask.5.1.0' to 'packages.config'
Executing nuget actions took 2.02 sec
Microsoft.Build.Exceptions.InvalidProjectFileException: The result "" of evaluating the value "$(GitVersionAssemblyFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  C:\Users\Tim\source\repos\ta.snapcap\packages\GitVersionTask.5.1.3\build\GitVersionTask.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject[T1,T2,T3,T4](Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1, T3 arg2, T4 arg3)
   at Microsoft.Build.Execution.TaskRegistry.RegisterTasksFromUsingTaskElement[P,I](ILoggingService loggingService, BuildEventContext buildEventContext, String directoryOfImportingFile, ProjectUsingTaskElement projectUsingTaskXml, TaskRegistry taskRegistry, Expander`2 expander, ExpanderOptions expanderOptions, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateUsingTaskElement(String directoryOfImportingFile, ProjectUsingTaskElement projectUsingTaskElement)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at NuGet.PackageManagement.VisualStudio.MicrosoftBuildEvaluationProjectUtility.RemoveImportStatement(Project msBuildProject, String targetsPath)
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.RemoveImportStatement(String targetsPath)
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.<>c__DisplayClass43_0.<<RemoveImport>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.RemoveImport(String targetFullPath)
   at NuGet.ProjectManagement.MSBuildNuGetProject.<UninstallPackageAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteUninstallAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass12_0.<<PerformActionImplAsync>b__0>d.MoveNext()
Time Elapsed: 00:00:06.5849877
========== Finished ==========
```

I tried to troubleshoot this by completely removing GitVersionTask from my solution, then I was able to cleanly install 5.1.0. Then attempting to upgrade to 5.1.3 failed with the above output, even after restarting Visual Studio.

**Comment by KiLLeRRaT** [comment] 2020-02-16 22:46
Hi,

I get the same problem and it's quite annoying.

I comment out the GitVersion related stuff from my `.csproj` file manually, and then click update for it to work.

It's be nice to have a fix for this at some point.

Related to https://github.com/GitTools/GitVersion/issues/1776

**Comment by tmwoods** [comment] 2020-03-19 22:43
I have the same issue and just want to add my vote to get it fixed. At this point I'll probably have to take the references entirely out manually as this is causing such a headache :(

**Comment by RufusJWB** [comment] 2020-09-07 12:53
Yes, please fix it. It's annoying!

**Comment by gcapnias** [comment] 2021-07-16 07:29
Any updates on this issue?

I still cannot upgrade NuGet package from Visual Studio 2019.

Is there an alternative way to update the package?


Regards,
George J.

**Comment by asbjornu** [comment] 2021-07-16 10:09
Why are you upgrading to version 5.1.3? Have you tried upgrading to the latest version 5.6.10?

**Comment by gcapnias** [comment] 2021-07-21 09:37
I am using v5.6.8 and trying to update to v5.6.10

**Comment by v-karbovnichy** [comment] 2021-07-22 11:48
Duplicate of #1776

**Comment by v-karbovnichy** [comment] 2021-07-22 11:49
I can reproduce this when `GitVersion.MsBuild` v5.6.10 installed and I am trying to migrate the project from `packages.config` format to `PackageReference`. So, essentially, VS cannot uninstall the `GitVersion.MsBuild`package and rolls back the migration.

**Comment by norigeist** [comment] 2023-01-23 15:02
Any news or an alternative solution to this issue? This issue occurred when I tried to upgrade from 5.8.2 to 5.11.0 and now from 5.11.0 to 5.12.0.
The workaround I did was to remove all GitVersion.MsBuild related references in `.csproj` and `packages.config` and install GitVersion in a newer version again. Now, this become a bit tedious...

**Comment by asbjornu** [comment] 2023-01-23 23:53
Closing as duplicate of #1776. Please continue the discussion in that issue.

**Closed by asbjornu** 2023-01-23 23:53 UTC
Labels: bug
