### ISSUE TITLE
[ISSUE]: Newly released GitVersion task for Azure DevOps doesn't work with newly released GitVersion.Tool

### ISSUE THREAD

**Issue by mtaylorfsmb** [GitTools/GitVersion#4345] opened 2024-12-10 15:42 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### GitVersion version

3.1.0

### Operating system

N/A

### What are you seeing?

When we tried to run our CI pipeline in Azure DevOps using GitVersion task@3.0 it fails because of the new GitVersion.Tool 6.1 release. 

##[error]Version spec '6.*' resolved as '6.1.0' does not satisfy the range '>=5.2.0 <6.1.0'.See https://github.com/GitTools/actions/blob/main/docs/versions.md for more information.

```yaml
- task: gitversion/setup@3.0.0
  displayName: Install GitVersion
  inputs:
    versionSpec: '6.*'
```

The Gitversion tooling was updated on our server to 3.1.0 today. We adjusted our YAML task to use @3.1.0 instead. However it still fails because GitVersion.Tool 6.1.0 is still outside the range allowed by the tooling.

### What is expected?

Minor version changes to tooling should not break CI pipelines. We should not be required to manually update all our pipelines to use the latest Gitversion task because of a minor update to Gitversion.Tool. Isn't this the entire purpose of semantic versioning (quote: MINOR version when you add functionality in a backward compatible manner)?

Expectation 1 - The latest Gitversion task should support the latest version of the tooling it relies on.
Expectation 2 - Breaking changes that require us to modify our pipelines should only be made on major version changes.

### Steps to Reproduce

Use the YAML I posted in an Azure Devops pipeline and try to build.

### Output log or link to your CI build (if appropriate).

```shell

```

**Comment by asbjornu** [comment] 2024-12-10 15:52
Duplicate of https://github.com/GitTools/actions/issues/1378.

**Closed by asbjornu** 2024-12-10 15:52 UTC
Labels: needs triage
