### ISSUE TITLE
[Bug] PreReleaseNumber for release branch uses diff to remote instead of commit count

### ISSUE THREAD

**Issue by chrbkr** [GitTools/GitVersion#2636] opened 2021-03-30 12:13 UTC
On my release branch, PreReleaseNumber is calculated wrong: instead of the number of commits since branching off of the develop branch, it shows how far ahead of the remote branch I am.

Suppose this situation:
* locally, the release branch has 3 commits
* 2 of these commits have been pushed to remote

## Expected Behavior

PreReleaseNumber = 3

## Actual Behavior

PreReleaseNumber = 1
Once all commits are pushed, PreReleaseNumber = 0

## Config

```yaml
  release:
    regex: release(s)?[/-]
    mode: ContinuousDeployment
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
    pre-release-weight: 900
```

## Version Used:
* Command line: 5.5.6
* GitVersion.MsBuild: 5.6.7

**Comment by asbjornu** [comment] 2021-04-06 15:45
Sounds like this should be possible to reproduce in a test. Can you please submit a PR with a failing test? 🙏🏼  If you're able to fix this in the PR as well, all the better. 😃

**Comment by HHobeck** [comment] 2023-03-21 07:05
It's a good question actually but we have done alot of work and it's not clear for me if this issue persists. I'm going to close it because there are no steps to reproduce. Please use the latest pre-release version and verify your scenario again... it might be solved. If not please re-open this issue or create a new bug. Thank you very much.

**Closed by HHobeck** 2023-03-21 07:05 UTC
Labels: bug, missing-steps-to-reproduce
