### ISSUE TITLE
[ISSUE]: GitLab CI tag pipelines result in an incorrect version

### ISSUE THREAD

**Issue by AlphaYankee** [GitTools/GitVersion#4186] opened 2024-08-29 21:47 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.0.2

### Operating system

Linux

### What are you seeing?

When running a tag pipeline, the tag is incorrectly detected as a branch. GitVersion gets its branch name from the environment variable CI_COMMIT_REF_NAME, but this variable is set to the tag when it's running a tag pipeline.

Example:
- Tag a commit as v1.1.2
- This executes a tag pipeline in GitLab CI
- The resulting SemVer will be 1.1.3-v1-1-2.1

### What is expected?

A SemVer of 1.1.2 (in this example)

### Steps to Reproduce

See example in the issue description.
More details in the discussion #4183

**Comment by asbjornu** [comment] 2024-08-29 21:55
Duplicate of #4015.

**Closed by asbjornu** 2024-08-29 21:55 UTC
Labels: needs triage

**Comment by AlphaYankee** [comment] 2024-08-29 22:36
The two issues are basically the same, yes. But this issue is about the incorrect usage of a GitLab CI specific environment variable, the other issue is about Azure Pipelines.

It might be better if there's a universal fix, as you said. But I believe this is a quick fix and it mirrors the fix for GitHub Actions which seems to have had a very similar problem, so it might still be a good idea to apply it for now.
