### ISSUE TITLE
[Bug] {UncommittedChanges} variable returning always 0 even when the repo has uncommitted changes.

### ISSUE THREAD

**Issue by LazaroOnline** [GitTools/GitVersion#2526] opened 2021-01-10 17:43 UTC
`{UncommittedChanges}` variable is returning always 0 even when the repo has uncommitted changes.

In my `GitVersion.yml` file:
```yml
assembly-informational-format: 'git-{ShortSha}-{BranchName}--{CommitDate}--pending-{UncommittedChanges}'
```

## Expected Behavior
The assembly informational version's `{UncommittedChanges}` variable should not be "0" when I have uncommitted changes in the repository.

## Actual Behavior
GitVersion.MsBuild is writing `"UncommittedChanges": 0,` in the `obj/gitversion.json` file.

## Your Environment
- Windows 10 (up-to-date in 2021)
- dotnet 5.0
- VisualStudio 2019
- GitVersion.MsBuild v5.6.3

**Comment by RichardJFoster** [comment] 2021-05-07 12:28
Came here to enter the same concern with released version 5.6.9.

**Comment by maloo** [comment] 2021-09-25 12:00
I have the same issue with 5.7.0. Did anyone find a solution to this?

**Comment by maloo** [comment] 2021-09-25 15:55
I found another package GitInfo that was much easier to use and returned valid dirty info

**Comment by arturcic** [comment] 2022-11-17 16:22
As far as I know there is no pr fixing this at the moment, so if you have the time to spend on this we accept prs

**Comment by HHobeck** [comment] 2023-03-21 07:23
Alot of work has been done and it's not clear for me if this issue persists. I have tested it locally and got the correct  UncommittedChanges number back. I'm going to close it because there are no steps to reproduce. Please use the latest pre-release version and verify your scenario again... it might be solved. If not please re-open this issue or create a new bug. Thank you very much.

**Closed by HHobeck** 2023-03-21 07:23 UTC
Labels: bug, missing-steps-to-reproduce
