### ISSUE TITLE
[Bug] Master build is incrementing latest tagged version

### ISSUE THREAD

**Issue by jjwilliams42** [GitTools/GitVersion#2239] opened 2020-04-22 16:44 UTC
**Describe the bug**
GitVersion is calculating the version out of master from a non-existent tag. It's "Incrementing" for some reason (according to /diag). The latest tag in my repository is 5.5.1.

## Expected Behavior
Output version is 5.5.1

## Actual Behavior
Output version is 5.5.2

I see it is also calculating the last version (in diag output) that should have been 5.5.0, it is adding a "(Incremented: 5.5.1)" to that message as well. Is this is a bug or a misunderstanding on my part?

## Possible Fix
I'm not sure why this is happening. GitVersion has always versioned master builds based on the last tag (ContinuousDelivery mode).

## Steps to Reproduce
While I can't link to my  repo, I have included the GitVersion /diag output. The latest tag is 5.5.1. 
The only odd thing that I can think of that might throw it off is that there was one commit directly to master after 5.5.1, but this should (from my understanding of GitVersion), produce a FullSemVer build of 5.5.1+1, with a SemVer of 5.5.1 still.

/diag output

```
git checkout master
GitVersion /diag
INFO [04/22/20 11:36:01:95] Dumping commit graph: 
INFO [04/22/20 11:36:02:11] * d94609499 2 hours ago  (origin/feature/RESP-1231)
| * b0b9ab075 23 hours ago  (origin/feature/BAFRIMP-167)
| | *   207aed4c8 26 hours ago  (feature/RESP-1231)
| | |\  
| |/ /  
| | /   
| |/    
|/|     
* | 4f27456f7 7 days ago 
* | 7e4749454 9 days ago 
| * b8b8601e8 26 hours ago  (origin/develop, feature/BAFRIMP-169, develop)
| * 71cbaef8a 2 days ago 
| | * 54501720e 26 hours ago  (origin/feature/RESP-1255, feature/RESP-1255)
| | * 42f72412f 2 days ago 
| | * 890fe6b08 2 days ago 
| | * cb64874e5 7 days ago 
| | | * a09c49957 2 days ago  (origin/feature/RESP-1304)
| | | * 863da6ca5 2 days ago 
| | |/  
| |/|   
| * |   062898adb 5 days ago 
| |\ \  
| | * | a6f3a8d8a 5 days ago  (HEAD -> master, origin/master, origin/HEAD)
| | * |   0a87f6666 6 days ago  (tag: 5.5.1)
| | |\ \  
| | | * | 6e829eec0 6 days ago 
| | | * | 791b5d331 7 days ago 
| | |/ /  
| * | | 876ed88f0 6 days ago 
| * | | 0e9a19c44 6 days ago 
| | | | * ac6a48821 5 days ago  (origin/feature/RESP-1105)
| | | | * a8f44a908 5 days ago 
| | |_|/  
| |/| |   
| * | |   ec9999eca 6 days ago 
| |\ \ \  
| | * | | f7cf1e5d5 7 days ago  (origin/feature/BAFRIMP-143)
| | * | | 471d91885 8 days ago 
| | * | |   608ca214f 8 days ago 
| | |\ \ \  
| | * | | | dfaab6547 2 weeks ago 
| * | | | |   13f1583b5 6 days ago 
| |\ \ \ \ \  
| | |_|_|_|/  
| |/| | | |   
| | * | | | 9075ea4c9 7 days ago 
| | * | | | e9bb0da32 7 days ago 
| |/ / / /  
| | | | | * ffdad0979 6 days ago  (origin/feature/BAFRIMP-165)
| | | | | * 9a39faffa 6 days ago 
| | |_|_|/  
| |/| | |   
| * | | |   2f9e9e194 8 days ago 
| |\ \ \ \  
| | | |_|/  
| | |/| |   
| | * | |   61d46174f 8 days ago  (tag: 5.5.0)
| | |\ \ \  
| | | * | | a27773a2f 8 days ago 
| | |/ / /  
| |/| | |   
| * | | |   0c56e7261 8 days ago 
| |\ \ \ \  
| | |_|_|/  
| |/| | |   
| | * | | 9c93555be 8 days ago 
| |/ / /  
| * | |   45092206e 8 days ago 
| |\ \ \  
| | * | | 8dcb65699 8 days ago  (origin/feature/BAFRIMP-153)
| | * | | ce36f91e6 2 weeks ago 
| |/ / /  
|/| | |   
| | | | * 528bc1cd7 8 days ago  (origin/feature/RESP-1245)
| | |_|/  
| |/| |   
| * | |   32e2d6974 8 days ago 
| |\ \ \  
|/ / / /  
| * | | 00a750a46 8 days ago  (origin/feature/BAFRIMP-142, feature/BAFRIMP-142)
| * | | 41b4e0f17 9 days ago 
|/ / /  
| | | * d179fab82 8 days ago  (feature/BAFRIMP-165)
| | | * dd2e83848 8 days ago 
| |_|/  
|/| |   
| | | * 3b0fe4329 8 days ago  (origin/feature/RESP-1293)
| | | * b3624d44e 9 days ago 
| |_|/  
|/| |   
* | |   3c9c501b9 2 weeks ago 
|\ \ \  
| |_|/  
|/| |   
| * | 1b1f91e60 2 weeks ago 
| * | 22f7697dd 2 weeks ago  (origin/feature/RESP-1283)
| * | ad7923862 2 weeks ago 
| * | 5d92c8627 2 weeks ago 
|/ /  
| | * 5d44179fe 9 days ago  (feature/SPJST-340)
| |/  
|/|   
* | ba860d66f 2 weeks ago 
* |   eff03306f 3 weeks ago 
|\ \  
| * | 2e641494e 3 weeks ago  (origin/feature/BAFRIMP-71)
| * | 957ddfb3d 3 weeks ago 
| * | a95367c96 3 weeks ago 
| * | 776fc35e1 3 weeks ago 
| * | 35c75c9cc 3 weeks ago 
| * | db7fa37b8 3 weeks ago 
| * | ba1ef6650 3 weeks ago 
| * | aeff65fd0 4 weeks ago 
* | |   20659e22b 3 weeks ago  (feature/RESP-1105)
|\ \ \  
| | |/  
| |/|   
| | | * 3f68da267 2 weeks ago  (origin/hotfix/5.4.25)
| | |/  
| |/|   
| * |   795753a33 3 weeks ago  (tag: 5.4.24)
| |\ \  
| | * | a9163e963 3 weeks ago  (origin/hotfix/5.4.24)
| |/ /  
| | | * e7111deaf 3 weeks ago  (origin/feature/addGitVersion, feature/addGitVersion)
| | | * e3b7f8ea7 3 weeks ago 
| | | * e28f9acfd 3 weeks ago 
| | | * c255abb89 3 weeks ago 
| | | * b3067f7ac 3 weeks ago 
| | | * f4b31141c 3 weeks ago 
| | | * c6b556449 3 weeks ago 
| | | * 2a7614ba8 3 weeks ago 
| | | * 76948406e 3 weeks ago 
| | | * 5411d0bf5 3 weeks ago 
| | | * 6b731534d 3 weeks ago 
| | | * d776a54c8 3 weeks ago 
| | | * 26648c069 3 weeks ago 
| | | * b808e53c0 3 weeks ago 
| | | * e9e719fdf 3 weeks ago 
| | | * fa9233c86 3 weeks ago 
| | | * 523d3d420 3 weeks ago 
| | | * 0e2dcf007 3 weeks ago 
| | | * 1932d20c1 3 weeks ago 
| | | * d9df5fb3c 3 weeks ago 
| | | * 9e6733ec3 3 weeks ago 
| | | * 28554ced9 3 weeks ago 
| | | * 9aa3c85c9 3 weeks ago 
| | | * 9e392e680 3 weeks ago 
| | | | * 32b164d5b 3 weeks ago  (origin/feature/RESP-1279)
| |_|_|/  
|/| | |   
* | | |   4dda207d9 3 weeks ago 
|\ \ \ \  
| * \ \ \   bfb719712 3 weeks ago 
| |\ \ \ \  
| |/ / / /  
|/| | | |   
| * | | | a4f258a8a 4 weeks ago  (origin/feature/RESP-1094, origin/feature/RESP-1086-1094)
| | | | | * 3789d2e20 3 weeks ago  (origin/feature/BAFRIMP-138)
| |_|_|_|/  
|/| | | |   
* | | | |   66bd0e73c 3 weeks ago 
|\ \ \ \ \  
| | |/ / /  
| |/| | |   
| * | | |   55d9a83e7 3 weeks ago  (tag: 5.4.23)
| |\ \ \ \  
| | * | | | fc5d04c51 3 weeks ago 
| |/ / / /  
|/| | | |   

INFO [04/22/20 11:36:02:11] Working directory: C:\Projects\Work\Respond5\mobile
INFO [04/22/20 11:36:02:12] Project root is: C:\Projects\Work\Respond5\
INFO [04/22/20 11:36:02:12] DotGit directory is: C:\Projects\Work\Respond5\.git
INFO [04/22/20 11:36:02:25] Using latest commit on specified branch
INFO [04/22/20 11:36:02:30] Running against branch: master (a6f3a8d8aaff11939b8b1b77756a4b44a0086ea1)
INFO [04/22/20 11:36:02:30] Begin: Calculating base versions
  INFO [04/22/20 11:36:02:38] Fallback base version: 0.1.0 with commit count source ba332556eae44b0601f75a3c6502748717622749 (Incremented: None)
  INFO [04/22/20 11:36:02:57] Found commit [a6f3a8d8aaff11939b8b1b77756a4b44a0086ea1] matching merge message format: Default
  INFO [04/22/20 11:36:02:59] Found commit [a6f3a8d8aaff11939b8b1b77756a4b44a0086ea1] matching merge message format: Default
  INFO [04/22/20 11:36:02:59] Found commit [a6f3a8d8aaff11939b8b1b77756a4b44a0086ea1] matching merge message format: Default
  INFO [04/22/20 11:36:02:59] Found commit [a6f3a8d8aaff11939b8b1b77756a4b44a0086ea1] matching merge message format: Default
  INFO [04/22/20 11:36:02:59] Found commit [a6f3a8d8aaff11939b8b1b77756a4b44a0086ea1] matching merge message format: Default
  INFO [04/22/20 11:36:02:59] Merge message 'Merge branch 'release/5.5.0'': 5.5.0 with commit count source 61d46174fbeab904fbbac0f4a93528a9f280de45 (Incremented: None)
  INFO [04/22/20 11:36:02:59] Merge message 'Merge branch 'release/5.4.23'': 5.4.23 with commit count source 55d9a83e7055ddb1bde002c23994ce840659dcaf (Incremented: None)
  INFO [04/22/20 11:36:02:59] Merge message 'Merge branch 'release/5.4.20'': 5.4.20 with commit count source 105dbdf74bd760986a7752e964c31df6bbe47ea1 (Incremented: None)
  INFO [04/22/20 11:36:02:59] Merge message 'Merge branch 'release/5.4.18'': 5.4.18 with commit count source e9f162a0dc03f13b4aafa22315683e309a5cf407 (Incremented: None)
  INFO [04/22/20 11:36:02:59] Merge message 'Merge branch 'release/5.4.14'': 5.4.14 with commit count source 41c4b8de52bdefc950af5203fd64cc2d6365630b (Incremented: None)
  INFO [04/22/20 11:36:02:69] Git tag '5.5.1': 5.5.1 with commit count source 0a87f66662ee265d5000f2273ebddd78471731d7 (Incremented: 5.5.2)
  INFO [04/22/20 11:36:02:69] Git tag '5.5.0': 5.5.0 with commit count source 61d46174fbeab904fbbac0f4a93528a9f280de45 (Incremented: 5.5.1)
  INFO [04/22/20 11:36:02:69] Git tag '5.4.24': 5.4.24 with commit count source 795753a33aedae560b7815151750ae5f3b8f087a (Incremented: 5.4.25)
  INFO [04/22/20 11:36:02:69] Git tag '5.4.23': 5.4.23 with commit count source 55d9a83e7055ddb1bde002c23994ce840659dcaf (Incremented: 5.4.24)
  INFO [04/22/20 11:36:02:69] Git tag '5.4.22': 5.4.22 with commit count source 204ed911a6fe00ee7b30058062723054ea86ae9d (Incremented: 5.4.23)
  INFO [04/22/20 11:36:02:72] Found multiple base versions which will produce the same SemVer (5.5.2), taking oldest source for commit counting (Git tag '5.5.1')
  INFO [04/22/20 11:36:02:72] Base version used: Git tag '5.5.1': 5.5.1 with commit count source 0a87f66662ee265d5000f2273ebddd78471731d7 (Incremented: 5.5.2)
  INFO [04/22/20 11:36:02:72] End: Calculating base versions (Took: 417.16ms)
  INFO [04/22/20 11:36:02:72] 1 commits found between 0a87f66662ee265d5000f2273ebddd78471731d7 and a6f3a8d8aaff11939b8b1b77756a4b44a0086ea1
  INFO [04/22/20 11:36:02:73] Running on Windows.
{
  "Major":5,
  "Minor":5,
  "Patch":2,
  "PreReleaseTag":"",
  "PreReleaseTagWithDash":"",
  "PreReleaseLabel":"",
  "PreReleaseNumber":"",
  "WeightedPreReleaseNumber":"",
  "BuildMetaData":1,
  "BuildMetaDataPadded":"0001",
  "FullBuildMetaData":"1.Branch.master.Sha.a6f3a8d8aaff11939b8b1b77756a4b44a0086ea1",
  "MajorMinorPatch":"5.5.2",
  "SemVer":"5.5.2",
  "LegacySemVer":"5.5.2",
  "LegacySemVerPadded":"5.5.2",
  "AssemblySemVer":"5.5.2.0",
  "AssemblySemFileVer":"5.5.2.0",
  "FullSemVer":"5.5.2+1",
  "InformationalVersion":"5.5.2+1.Branch.master.Sha.a6f3a8d8aaff11939b8b1b77756a4b44a0086ea1",
  "BranchName":"master",
  "EscapedBranchName":"master",
  "Sha":"a6f3a8d8aaff11939b8b1b77756a4b44a0086ea1",
  "ShortSha":"a6f3a8d",
  "NuGetVersionV2":"5.5.2",
  "NuGetVersion":"5.5.2",
  "NuGetPreReleaseTagV2":"",
  "NuGetPreReleaseTag":"",
  "VersionSourceSha":"0a87f66662ee265d5000f2273ebddd78471731d7",
  "CommitsSinceVersionSource":1,
  "CommitsSinceVersionSourcePadded":"0001",
  "CommitDate":"2020-04-17"
}
```

## Context
I was trying to build version 5.5.1

- Version Used: 5.2.4+Branch.master.Sha.643ba1fc16fad3d5659fead16c335fb6288ade7a
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 10
- Link to your project: proprietary
- Link to your CI build (if appropriate): proprietary

**Comment by asbjornu** [comment] 2020-04-22 18:45
How does your `GitVersion.yml` look like (if you have any)?

**Comment by jackjwilliams** [comment] 2020-04-22 19:15
It's very basic, just overrode feature and develop to be ContinuousDeployment:

```
mode: ContinuousDelivery
branches:
  feature:
    mode: ContinuousDeployment
  develop:
    mode: ContinuousDeployment
ignore:
  sha: []
merge-message-formats: {}
```

**Comment by asbjornu** [comment] 2020-04-22 22:39
Are you able to reproduce this problem with a `RepositoryFixture` (in a pull request, most preferably)?

**Comment by jackjwilliams** [comment] 2020-05-14 19:45
Unfortunately, I don't have time to commit to this right now. It looks like the cause may have been found in https://github.com/GitTools/GitVersion/issues/2241 though

**Comment by HHobeck** [comment] 2023-03-16 12:01
@jjwilliams42 Could you please write an integration test or provide us steps to reproduce this issue (take the main branch or preview version for 6.x)?

**Comment by HHobeck** [comment] 2023-03-20 06:51
Because of missing steps to reproduce I'm going to close this issue. Please re-open or create a new bug if you can reproduce it in the current development version. Thank you.

**Closed by HHobeck** 2023-03-20 06:51 UTC
Labels: bug
