### ISSUE TITLE
GitVersion.Tool throws exception and returns exit code 0

### ISSUE THREAD

**Issue by matkoch** [GitTools/GitVersion#2000] opened 2019-12-19 23:09 UTC
Even though there clearly is an error, the exit code is 0.

```
[19:42:13]	[Clean]
INFO [12/19/19 19:42:13:01] Applicable build agent found: 'TeamCity'.
INFO [12/19/19 19:42:13:02] Working directory: /var/www/TeamCity/buildAgent/work/eff7cbc1aff2d3e
INFO [12/19/19 19:42:13:02] IsDynamicGitRepository: False
INFO [12/19/19 19:42:13:04] Returning Project Root from DotGitDirectory: /var/www/TeamCity/buildAgent/work/eff7cbc1aff2d3e/.git/ - /var/www/TeamCity/buildAgent/work/eff7cbc1aff2d3e/
INFO [12/19/19 19:42:13:05] Running on Unix.
INFO [12/19/19 19:42:13:05] Applicable build agent found: 'TeamCity'.INFO [12/19/19 19:42:13:05] Branch from build environment: master
INFO [12/19/19 19:42:13:05] Begin: Normalizing git directory for branch 'master'  
INFO [12/19/19 19:42:13:10] One remote found (origin -> 'https://github.com/XX/YY').  
INFO [12/19/19 19:42:13:10] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.  
INFO [12/19/19 19:42:13:17] End: Normalizing git directory for branch 'master' (Took: 122.44ms)  
ERROR [12/19/19 19:42:13:20] An unexpected error occurred:
[19:42:13]	[Clean] LibGit2Sharp.LibGit2SharpException: remote authentication required but no callback set
[19:42:13]	[Clean]    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
[19:42:13]	[Clean]    at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
[19:42:13]	[Clean]    at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage)
[19:42:13]	[Clean]    at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage)
[19:42:13]	[Clean]    at GitVersion.Helpers.GitRepositoryHelper.Fetch(ILog log, AuthenticationInfo authentication, Remote remote, Repository repo) in D:\a\1\s\src\GitVersionCore\Helpers\GitRepositoryHelper.cs:line 145
[19:42:13]	[Clean]    at GitVersion.Helpers.GitRepositoryHelper.NormalizeGitDirectory(ILog log, IEnvironment environment, String gitDirectory, AuthenticationInfo authentication, Boolean noFetch, String currentBranch, Boolean isDynamicRepository) in D:\a\1\s\src\GitVersionCore\Helpers\GitRepositoryHelper.cs:line 40
[19:42:13]	[Clean]    at GitVersion.GitPreparer.Prepare(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 51
[19:42:13]	[Clean]    at GitVersion.GitVersionCalculator.CalculateVersionVariables() in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 52
[19:42:13]	[Clean]    at GitVersion.ExecCommand.Execute() in D:\a\1\s\src\GitVersionExe\ExecCommand.cs:line 40
[19:42:13]	[Clean]    at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments) in D:\a\1\s\src\GitVersionExe\GitVersionExecutor.cs:line 117  INFO [12/19/19 19:42:13:20]   INFO [12/19/19 19:42:13:20] Attempting to show the current git graph (please include in issue):   INFO [12/19/19 19:42:13:20] Showing max of 100 commits
```

**Comment by matkoch** [comment] 2019-12-19 23:09
@joshclose

**Comment by matkoch** [comment] 2020-01-04 18:53
Forgot to mention, this is `GitVersion.Tool`. I suspect that's relevant.

**Comment by asbjornu** [comment] 2020-01-06 09:45
Are the environment variables `GITVERSION_REMOTE_USERNAME` and `GITVERSION_REMOTE_PASSWORD` defined [as per the documentation](https://gitversion.net/docs/usage/msbuild-task#my-git-repository-requires-authentication.what-should-i-do)?

**Comment by matkoch** [comment] 2020-01-06 11:10
The problem is not the missing environment variables but the exit code of 0
after an exception.

**Comment by asbjornu** [comment] 2020-01-07 07:36
Ah, so in the absence of these environment variables and the resulting exceptions due to their absence, GitVersion still produces an exit code of `0`? That's a bug indeed.

**Comment by VLZZZ** [comment] 2020-02-10 18:43
+1 for the exit code issues.
I've had several different situations when an Error produced but in all cases exit code was `0`.

e.g.
```
❯ gitversion; echo -e "\n\nEXIT_CODE: $?"

INFO [02/10/20 21:41:56:80] Working directory: /opt/test-releaseINFO [02/10/20 21:41:56:81] IsDynamicGitRepository: FalseINFO [02/10/20 21:41:56:82] Returning Project Root from DotGitDirectory: /opt/test-release/.git/ - /opt/test-release/INFO [02/10/20 21:41:56:82] Running on Unix.INFO [02/10/20 21:41:56:82] Project root is: /opt/test-release/INFO [02/10/20 21:41:56:82] DotGit directory is: /opt/test-release/.gitINFO [02/10/20 21:41:56:87] Begin: Loading version variables from disk cache  INFO [02/10/20 21:41:56:87] Cache file /opt/test-release/.git/gitversion_cache/47B6B3F3BFE65B464C9A7A33AF8058E6E82CE7F8.yml not found.  INFO [02/10/20 21:41:56:87] End: Loading version variables from disk cache (Took: 3.60ms)  ERROR [02/10/20 21:41:57:04] An unexpected error occurred:
GitVersion.Configuration.GitVersionConfigurationException: Branch configuration 'all' is missing required configuration 'source-branches'

See http://gitversion.readthedocs.io/en/latest/configuration/ for more info
   at GitVersion.Configuration.ConfigExtensions.Reset(Config config)
   at GitVersion.Configuration.ConfigProvider.Provide(String workingDirectory, Boolean applyDefaults, Config overrideConfig)
   at GitVersion.Configuration.ConfigProvider.Provide(Boolean applyDefaults, Config overrideConfig)
   at GitVersion.GitVersionCalculator.ExecuteInternal(String targetBranch, String commitId, Config overrideConfig)
   at GitVersion.GitVersionCalculator.GetCachedGitVersionInfo(String targetBranch, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.GitVersionCalculator.CalculateVersionVariables()
   at GitVersion.ExecCommand.Execute()
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments)  INFO [02/10/20 21:41:57:04]   INFO [02/10/20 21:41:57:04] Attempting to show the current git graph (please include in issue):   INFO [02/10/20 21:41:57:04] Showing max of 100 commits

EXIT_CODE: 0
```

**Comment by arturcic** [comment] 2020-04-18 14:26
I think this one was fixed here https://github.com/GitTools/GitVersion/pull/2161. Please check the version 5.2.4 and confirm it was fixed. Closing. reopen if still reproducing

**Closed by arturcic** 2020-04-18 14:26 UTC
Labels: bug
