### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by td0wn** [GitTools/GitVersion#2661] opened 2021-04-15 21:20 UTC
**Describe the bug**
Setting next-version prevents Mainline mode from counting direct & merge commits when computing the version, since the changes in commit c701080bfb1eb5ca611fed209d6b6f3f0caef2bb, I believe.

## Expected Behavior
The next-version setting should affect only the baseline version and the commit traversal in Mainline mode should still be executed, as was the previous behavior.

## Actual Behavior
No commits are traversed/recognized as bumping the version so the next-version is just used as the computed version.

Prior to this change the next-version setting was used just for determining the baseline version, but now that setting is being consulted for commit traversal in Mainline mode and resulting in different behavior.  I don't _think_ this was intentional? 

## Possible Fix
Don't check for next-version being null/empty when deciding whether to walk the commit graph in Mainline mode.  Basically I don't think this conditional check should be there: https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Core/VersionCalculation/MainlineVersionCalculator.cs#L55

## Context
Computed version when in Mainline mode and setting next-version results in different values when upgrading to versions released after c701080bfb1eb5ca611fed209d6b6f3f0caef2bb merged.

## Your Environment
- Version Used: 5.6.4
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 10 & Ubuntu 20.04

**Comment by asbjornu** [comment] 2021-04-15 23:12
Duplicate of #2441. Please remove `next-version` and add a `git tag` with the same version number, on the appropriate tag.

**Closed by asbjornu** 2021-04-15 23:12 UTC
Labels: bug
