### ISSUE TITLE
[ISSUE]: GitVersion MSBuild v.6.0.2 does not generate AssemblyInfo.g.cs needed to override AssemblyVersion

### ISSUE THREAD

**Issue by seandkim** [GitTools/GitVersion#4190] opened 2024-09-02 02:27 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.MsBuild

### GitVersion version

6.0.2

### Operating system

Windows

### What are you seeing?

I have a simple console app with the following:
`Program.cs`
```c#
using System.Reflection;
var version = Assembly.GetExecutingAssembly()
    .GetCustomAttribute<AssemblyInformationalVersionAttribute>().InformationalVersion;
Console.WriteLine($"Hello, World! {version}");
```

`.csproj` file
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Version="6.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

I added a git tag so my gitversion output is
```
{
  "AssemblySemFileVer": "2.3.1.0",
  "AssemblySemVer": "2.3.1.0",
  "BranchName": "master",
  "BuildMetaData": null,
  "CommitDate": "2024-09-02",
  "CommitsSinceVersionSource": 0,
  "EscapedBranchName": "master",
  "FullBuildMetaData": "Branch.master.Sha.7ced748ec0ba476224b74e34581bf0ad0e141088",
  "FullSemVer": "2.3.1",
  "InformationalVersion": "2.3.1+Branch.master.Sha.7ced748ec0ba476224b74e34581bf0ad0e141088",
  "Major": 2,
  "MajorMinorPatch": "2.3.1",
  "Minor": 3,
  "Patch": 1,
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": null,
  "PreReleaseTag": "",
  "PreReleaseTagWithDash": "",
  "SemVer": "2.3.1",
  "Sha": "7ced748ec0ba476224b74e34581bf0ad0e141088",
  "ShortSha": "7ced748",
  "UncommittedChanges": 2,
  "VersionSourceSha": "7ced748ec0ba476224b74e34581bf0ad0e141088",
  "WeightedPreReleaseNumber": 60000
}
```

### What is expected?

I expect to see my gitversion; instead, I see the default assembly version, v1.0.0. I noticed that AssemblyInfo.g.cs file is not generated when I run `dotnet build`. 

The problem only occurs in v6.0.2. In v5.12.0, the gitversion is correctly outputted (and AssemblyInfo.g.cs file correctly autogenerated).

### Steps to Reproduce

See above

**Comment by arturcic** [comment] 2024-09-05 12:38
@seandkim can you tell me how are you building the code? Is it via dotnet build or visual studio?

**Comment by neoasis-werx** [comment] 2024-09-05 12:55
I'm having the same issue, It works using dotnet build.
 
But when building in VisualStudio 2022, it does not create the 
- gitversion.json 
- GitVersionInformation.g.cs
- or modifies the AsssemblyInfo.cs

```
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.11.2
.Net 8.0.400
```

**Comment by arturcic** [comment] 2024-09-05 13:10
the issue is has same root as https://github.com/GitTools/GitVersion/issues/4116. GitVersion.MsBuild is disabled when run in Visual Studio, so I will close this issue in favor of the mentioned

**Closed by arturcic** 2024-09-05 13:10 UTC
Labels: msbuild

**Comment by dorssel** [comment] 2024-12-02 01:35
FYI, I created https://www.nuget.org/packages/Dorssel.GitVersion.MsBuild, which does support Visual Studio even with version 6 GitVersion tool.
