### ISSUE TITLE
No v4.0.0-beta.13 in nuget gallery, why ?

### ISSUE THREAD

**Issue by donnib** [GitTools/GitVersion#1409] opened 2018-05-16 12:44 UTC

**Comment by li0nsar3c00l** [comment] 2018-06-20 20:16
Any ETA ?

**Comment by bsagal** [comment] 2018-06-25 08:21
duplicate of #1354

**Comment by JakeGinnivan** [comment] 2018-08-21 13:46
Is it https://www.nuget.org/packages/GitVersion/4.0.0-beta0012 you are interested in?

If so, let me know your use case as this is just the library and am thinking about dropping it.

Anyways, beta0014 of GitVersion command line and task is up. please open a fresh issue if there are any issues

**Comment by JakeGinnivan** [comment] 2018-08-21 13:46
https://www.nuget.org/packages/GitVersionTask/4.0.0-beta0014 and https://www.nuget.org/packages/GitVersion.CommandLine/4.0.0-beta0014  btw

**Closed by JakeGinnivan** 2018-08-21 13:46 UTC
