### ISSUE TITLE
Release of GitVersionNetCoreTask 

### ISSUE THREAD

**Issue by ivanrusso** [GitTools/GitVersion#1542] opened 2018-12-02 21:05 UTC
When will the GitVersionNetCoreTask be available on Azure Devops?

Currently I want to run GitVersion on an Azure pipeline, which is based on ubuntu 16.4. Unfortunately this doesn't work with mono (LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: git2-15e1193). It would be very helpful if I could test the .NET core version.
Is there an alternative to running GitVersion with .NET core today with the Azure pipeline?

**Comment by arturcic** [comment] 2018-12-03 07:10
In case you have .NET Core SDK 2.1.300 and later versions, you can install the prerelease version of [GitVersion.Tool](https://www.nuget.org/packages/GitVersion.Tool)

**Comment by ivanrusso** [comment] 2018-12-03 23:10
This is the NuGet package to use directly with .NET Core as global Tool. What i need is the newest Task for TFS wich will call dotnet GitVersion.dll. This is made by https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTfsTask/GitVersion.ts.

**Comment by asbjornu** [comment] 2019-06-27 11:04
@ivanrusso, so this issue is basically a duplicate of #1150, then?

**Comment by ivanrusso** [comment] 2019-06-27 11:43
@asbjornu , yes it is a duplicate

**Comment by arturcic** [comment] 2019-06-27 11:48
Will be fixed by #1492

**Closed by arturcic** 2019-06-27 11:48 UTC
Labels: build
