### ISSUE TITLE
the combination of VS 2019 Version 16.5.0 Preview 2.0 and .NET Core 3.1.200-preview-014883 fails dotnet build

### ISSUE THREAD

**Issue by barrett777** [GitTools/GitVersion#2063] opened 2020-01-23 18:57 UTC
If you install VS 2019 Version 16.5.0 Preview 2.0 (Released 1/22/2020), ```dotnet build``` fails with this error.  Here's a related StackOverflow question/answer on how to work around.

https://stackoverflow.com/a/59876257/1603663

I don't know if this issue is a bug in .net core, or an update required in GitVersion

```C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018: The "WriteVersionInfoToBuildLog" task failed unexpectedly. [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018: System.TypeInitializationException: The type initializer for 'GitVersion.MSBuildTask.TaskProxy' threw an exception. [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:  ---> System.IO.FileNotFoundException: Could not load file or assembly 'GitVersionTask.MsBuild, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018: File name: 'GitVersionTask.MsBuild, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null' [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:  ---> System.IO.FileNotFoundException: Could not load file or assembly 'GitVersionTask.MsBuild, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018: File name: 'GitVersionTask.MsBuild, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null' [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext) [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext) [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext) [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName) [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at GitVersion.MSBuildTask.LibGit2Sharp.GitLoaderContext.Load(AssemblyName assemblyName) in D:\a\1\s\src\GitVersionTask.MsBuild\LibGit2Sharp\GitLoaderContext.cs:line 30 [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName) [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName) [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:  [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:  [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext) [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase) [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Reflection.Assembly.GetType(String name, Boolean throwOnError) [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at GitVersion.MSBuildTask.TaskProxy..cctor() in D:\a\1\s\src\GitVersionTask.MsBuild\TaskProxy.cs:line 22 [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:  [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:  [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    --- End of inner exception stack trace --- [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at GitVersion.MSBuildTask.Tasks.WriteVersionInfoToBuildLog.Execute() in D:\a\1\s\src\GitVersionTask.MsBuild\Tasks\WriteVersionInfoToBuildLog.cs:line 5 [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [ProjectFile]
C:\Users\benb\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [ProjectFile]```

**Comment by SeppPenner** [comment] 2020-02-09 19:59
I can confirm that. I have the same issue now...

**Comment by SeppPenner** [comment] 2020-02-09 20:03
@barrett777 Thanks for the link to the workaround :)

**Comment by thoemmi** [comment] 2020-03-17 11:11
I experience the same issue with the released 3.1.200 and GitVersionTask 5.2.4. All our CI builds fail now.
Unfortunately, even a global.json with 3.1.101 does not help.

> ##[error]C:\Users\TeamCityTFSAgent\.nuget\packages\gitversiontask\5.2.4\build\GitVersionTask.targets(10,9): Error MSB4018: Unerwarteter Fehler bei der WriteVersionInfoToBuildLog-Aufgabe.
> System.IO.FileNotFoundException: Could not load file or assembly 'GitVersionTask.MsBuild, Version=5.2.4.0, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
> File name: 'GitVersionTask.MsBuild, Version=5.2.4.0, Culture=neutral, PublicKeyToken=null'
>  ---> System.IO.FileNotFoundException: Could not load file or assembly 'GitVersionTask.MsBuild, Version=5.2.4.0, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
> File name: 'GitVersionTask.MsBuild, Version=5.2.4.0, Culture=neutral, PublicKeyToken=null'
>    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
>    at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
>    at GitVersion.MSBuildTask.LibGit2Sharp.GitLoaderContext.Load(AssemblyName assemblyName) in D:\a\GitVersion\GitVersion\src\GitVersionTask.MsBuild\LibGit2Sharp\GitLoaderContext.cs:line 29
>    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
>    at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
> 
> 
>    at GitVersion.MSBuildTask.GitVersionTaskBase.Execute() in D:\a\GitVersion\GitVersion\src\GitVersionTask.MsBuild\GitVersionTaskBase.cs:line 33
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

**Comment by arturcic** [comment] 2020-03-17 11:12
I noticed that as well. I'll need to find a fix for this

**Comment by thoemmi** [comment] 2020-03-17 11:41
Neither pinning to 3.1.101 with global.json nor a downgrade of GitVersionTask to 5.1.2 does help 😕

**Comment by arturcic** [comment] 2020-03-17 11:42
Have you upgraded the sdk on the CI to 3.1.200?

**Comment by thoemmi** [comment] 2020-03-17 11:44
Yes, I have updated the VS Build Tools to 16.5 on our build machine an hour ago.

Our CI Build includes a build step to use .NET Core SDK 3.1.x, so it already used the latest SDK before my update 🙄

**Comment by arturcic** [comment] 2020-03-17 11:46
Then either you downgrade the build tools to 16.4 and used sdk 3.1.102 or just wait for a fix, but it could take some time to fix it.

**Comment by thoemmi** [comment] 2020-03-17 13:32
I've uninstalled 16.5 and installed 16.4.5 (for reference, you can get specific versions [here](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history)). However, this didn't help, as each build agent has its own copy of dotnet + SDK, therefore I had to remove `_tools/dotnet` folder of each agent manually. Afterwards all pipelines built successfully, even with GitVersionTask 5.2.4.
I.e. the pressure is reduced 😅

**Comment by arturcic** [comment] 2020-03-17 13:46
That's great

**Comment by rainersigwald** [comment] 2020-03-18 11:24
This is likely a result of MSBuild changes to improve task isolation (microsoft/msbuild#4916). However, it looks like GitVersion has its own GitLoaderContext, which should have insulated you from that change.

If you're affected by this, can you try setting the environment variable `MSBUILDSINGLELOADCONTEXT=1` before your build and reporting whether that helps. If it does, it's a lighter-weight workaround than downgrading to SDK 3.1.1xx.

**Comment by arturcic** [comment] 2020-03-18 17:23
@rainersigwald  setting `MSBUILDSINGLELOADCONTEXT=1` helped, at least I can confirm the integration tests that test the GitVersionTask passes. 

Is there a way we can enable this without setting this env variable? I'd prefer someone using the package not to set the env variable prior to build

**Comment by bonesoul** [comment] 2020-03-27 10:22
@arturcic this may be a possible fix;

https://github.com/SpecFlowOSS/SpecFlow/issues/1912#issuecomment-604462903

**Comment by arturcic** [comment] 2020-03-27 10:23
thanks for pointing out, I'll check if it can be applied for us as well

**Comment by rainersigwald** [comment] 2020-03-27 11:44
The SpecFlow fix doesn't seem to be relevant to GitVersion. I've been debugging it but haven't figured out what's up yet. I was able to break past the first problem but immediately found other problems.

The reason this is happening is that the tasks don't do work themselves, but load an implementation via reflection and invoke that. When the default AssemblyLoadContext isn't configured to find task assemblies, this fails to load.

Is there someone that can walk me through the intention of this code?

**Comment by arturcic** [comment] 2020-03-27 11:50
@rainersigwald the implementation was somehow inspired from https://github.com/dotnet/sourcelink/blob/01e9ee3b6488c21e8c331d6f918bda5acf09d99f/src/Microsoft.Build.Tasks.Git/TaskImplementation.cs

**Comment by rainersigwald** [comment] 2020-03-27 22:36
Notes on what I've figured out so far. I don't see a super clear path forward at the moment, will continue to look on Monday:

`TaskProxy` has an explicit reference to the stub implementations of the tasks in `GitVersionTask.MsBuild`

`TaskProxy` tries to load the assembly `GitVersionTask` in its private `GitLoaderContext` ALC

`GitVersionTask` depends on `GitVersionTask.MsBuild`, and the type `GitVersion.MSBuildTask.GitVersionTasks` has explicit references back to it, so when it's not available in the private ALC it fails with the original error

```
Could not load file or assembly 'GitVersionTask.MsBuild, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

at 

```csharp
var type = LibGit2SharpLoader.Instance.Assembly.GetType("GitVersion.MSBuildTask.GitVersionTasks", throwOnError: true).GetTypeInfo();

```

If you amend the private ALC to also load `GitVersionTask.MsBuild`, we get past that, but the immediately following line

```csharp
GetVersion = GetMethod<GetVersion>(type, nameof(GetVersion));
...

private static Func<T, bool> GetMethod<T>(TypeInfo type, string name) => (Func<T, bool>)type.GetDeclaredMethod(name).CreateDelegate(typeof(Func<T, bool>));

```

fails, because the `GetVersion` in the type parameter is in the task ALC, while the `GetVersion` returned from reflection is in the `GitLoaderContext` ALC, so they don't match and you get

```
System.ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.
```

In the old MSBuild, there was no task ALC, only the default ALC. That meant that

1. `GitVersionTask.MsBuild` is loaded in the default ALC
1. The `GitVersionTask` assembly is loaded in the private `GitLoaderContext` ALC
1. When loading the type `GitVersion.MSBuildTask.GitVersionTasks`, `GitVersionTask.MsBuild` is not found
1. so it falls back to the default ALC, where it's already loaded and returned.
1. The cast then succeeds because it's the same type in the same ALC

**Comment by rainersigwald** [comment] 2020-04-03 21:18
I think GitTools/GitVersion#2221 should do the trick. Comments welcome.

**Closed** 2020-04-06 17:20 UTC

**Comment by tkrafael** [comment] 2020-04-16 13:36
Is it possible to ilmerge all dependent assemblies and avoid assembly load context?

**Comment by tkrafael** [comment] 2020-05-04 20:38
Thanks guys, you're awesome!

**Comment by bonesoul** [comment] 2020-05-04 22:11
great!

**Comment by SeppPenner** [comment] 2020-05-05 07:58
Can confirm that it's fixed 👍

**Comment by jmevel** [comment] 2020-10-16 11:37
I'm referencing the Nuget package version 5.3.7 and this issue still remains on my side. Building with Visual Studio works but building with `dotnet build` fails for some unknown reasons.

```bash
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018: Échec inattendu de la tâche "WriteVersionInfoToBuildLog". [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018: System.TypeInitializationException: The type initializer for 'GitVersionTask.MsBuild.TaskProxy' threw an exception. [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:  ---> System.IO.FileNotFoundException: Could not load file or assembly 'GitVersionTask.MsBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Le fichier spécifié est introuvable. [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018: File name: 'GitVersionTask.MsBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:  ---> System.IO.FileNotFoundException: Could not load file or assembly 'GitVersionTask.MsBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Le fichier spécifié est introuvable. [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018: File name: 'GitVersionTask.MsBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly) [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext) [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName) [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at GitVersionTask.MsBuild.LibGit2Sharp.GitLoaderContext.Load(AssemblyName assemblyName) in D:\a\1\s\src\GitVersionTask.MsBuild\LibGit2Sharp\GitLoaderContext.cs:line 30 [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName) [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName) [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext) [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase) [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at System.Reflection.Assembly.GetType(String name, Boolean throwOnError) [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at GitVersionTask.MsBuild.TaskProxy..cctor() in D:\a\1\s\src\GitVersionTask.MsBuild\TaskProxy.cs:line 22 [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    --- End of inner exception stack trace --- [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at GitVersionTask.MsBuild.Tasks.WriteVersionInfoToBuildLog.Execute() in D:\a\1\s\src\GitVersionTask.MsBuild\Tasks\WriteVersionInfoToBuildLog.cs:line 5 [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\dev\Git\Project\src\Project\Project.csproj]
C:\Users\mevelje\.nuget\packages\gitversiontask\5.0.1\build\GitVersionTask.targets(10,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\dev\Git\Project\src\Project\Project.csproj]
```

**Comment by SeppPenner** [comment] 2020-10-20 18:21
@jmevel You seem to be using GitVersionTask 5.0.1, not 5.3.7, check your log.

**Comment by jmevel** [comment] 2020-10-20 19:14
> @jmevel You seem to be using GitVersionTask 5.0.1, not 5.3.7, check your log.
> 
> ![grafik](https://user-images.githubusercontent.com/9639361/96628017-f58d9300-1311-11eb-9c85-3c0052ad57da.png)
> 

Hum that's correct, thanks for pointing me this mistake!
