### ISSUE TITLE
[Bug] GitVersion fails on multi-targeted .NETStandard class library when "Generate Packages on Build" option is selected

### ISSUE THREAD

**Issue by NameOfTheDragon** [GitTools/GitVersion#2538] opened 2021-01-14 02:56 UTC
**Describe the bug**
This is what I'm seeing in my build log:
<pre>
CONSOLE: Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
CONSOLE: Copyright (C) Microsoft Corporation. All rights reserved.
CONSOLE: Build started 14/01/2021 01:49:17.
0>------- Started building project: TA.Ascom.ReactiveCommunications
0>C:\Users\Tim\.nuget\packages\gitversion.msbuild\5.6.3\tools\net48/gitversion.exe D:\VS-Projects\ta.ascom.reactivecommunications\TA.Ascom.ReactiveCommunications -output file -outputfile obj\/gitversion.json
0>C:\Users\Tim\.nuget\packages\gitversion.msbuild\5.6.3\tools\net48/gitversion.exe D:\VS-Projects\ta.ascom.reactivecommunications\TA.Ascom.ReactiveCommunications -output file -outputfile obj\/gitversion.json
0>TA.Ascom.ReactiveCommunications -> D:\VS-Projects\ta.ascom.reactivecommunications\TA.Ascom.ReactiveCommunications\bin\Debug\netstandard2.0\TA.Ascom.ReactiveCommunications.dll
0>TA.Ascom.ReactiveCommunications -> D:\VS-Projects\ta.ascom.reactivecommunications\TA.Ascom.ReactiveCommunications\bin\Debug\netstandard2.1\TA.Ascom.ReactiveCommunications.dll
0>C:\Users\Tim\.nuget\packages\gitversion.msbuild\5.6.3\tools\net48/gitversion.exe D:\VS-Projects\ta.ascom.reactivecommunications\TA.Ascom.ReactiveCommunications -output file -outputfile obj\/gitversion.json
0>C:\Users\Tim\.nuget\packages\gitversion.msbuild\5.6.3\tools\GitVersion.MsBuild.targets(110,9): Error MSB4044: The "GenerateGitVersionInformation" task was not given a value for the required parameter "Language".
0>------- Finished building project: TA.Ascom.ReactiveCommunications. Succeeded: True. Errors: 0. Warnings: 0
Build completed in 00:00:08.559
</pre>

The project is multi-targeted to `NETStandard2.0` and `NETStandard2.1`. NCrunch is fine with this and builds it without complaining

![image](https://user-images.githubusercontent.com/1268490/104534611-8079e300-560c-11eb-9937-9958b3edc2f3.png)

However, when I build it in Visual Studio (using either VS buils or ReSharper build) then I get the error above.

From the log, it appears that GitVersion is getting called
- once for the NETStandard2.0 build
- once for the NETStandard2.1 build
- and then again, I suspect for the `pack` target, whereupon it fails.

This only happens for multi-targeted projects and where "Generate Packages on Build" is selected. If I only target one of the runtimes, the error goes away. If I disable `Generate Packages on Build` the problem goes away.

## Expected Behavior
`GitVersion.MSBuild` should be install-and-go. I feel like it is currently fighting me at every turn.

## Actual Behavior
`GitVersion is causing builds to fail. I would speculate that it is probably failing during the NuGet Pack operation, but only under certain conditions, such as with a multi-targeted project.

## Steps to Reproduce

1. File/New project, Class Library, .NET Standard
2. Add `GitVersion.MSBuild` 5.6.3 NuGet package, build and verify build successful.
3. Edit the `*.csproj` file and set it as follows
```lang-xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
      <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Version="5.6.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```
4.  Close and re-load the solution
5. Build. Observe build errors.
6. Remove the `<GeneratePackageOnBuild>` element and rebuild. Observe that the solution builds.

Here is a minimal failing solution: https://github.com/NameOfTheDragon/TA.GitVersionIssues.MultiTargeting

## Context
Prevents building of NuGet packages with multiple platform targets

## Environment
- GitVersion.MSBuild 5.6.3
- Windows 10, Visual Studio 2019 Enterprise
- Link to project: https://github.com/NameOfTheDragon/TA.GitVersionIssues.MultiTargeting

**Comment by NameOfTheDragon** [comment] 2021-01-14 13:36
Additional information. I can build the solution by omitting the 'nuget pack' operation, but then on my build server I need to do that as a separate step. This fails, complaining about "unkown language en-US:en". Attached is the full build log from my TeamCity server.
[Tigra_OSS_TA.ReactiveCommunications_1.3.1-beta.5.log](https://github.com/GitTools/GitVersion/files/5814699/Tigra_OSS_TA.ReactiveCommunications_1.3.1-beta.5.log)

**Comment by asbjornu** [comment] 2021-01-14 14:02
Duplicate of #2539 and #2523 which were fixed in #2529 and will be released in 5.6.4.

**Closed by asbjornu** 2021-01-14 14:02 UTC
Labels: bug

**Comment by NameOfTheDragon** [comment] 2021-01-16 00:00
@asbjornu Notwithstanding the fact that this is a duplicate issue, I'm kind of in limbo here as this is a bit of a showstopper for me. Is 5.6.4 imminent? Alternatively do you have a prerelease NuGet feed I could use?

**Comment by asbjornu** [comment] 2021-01-18 12:36
Yes, the latest builds can be downloaded from [the GitHub Package registry](https://github.com/orgs/GitTools/packages?repo_name=GitVersion).

**Comment by NameOfTheDragon** [comment] 2021-01-19 15:27
@asbjornu I cannot verify that this is fixed in the latest integration build. I'm still getting "unknown language" errors in my build... can we please re-open this issue until I can verify correct operation?

![image](https://user-images.githubusercontent.com/1268490/105055213-bf73c280-5a6a-11eb-892a-af76b92e99b1.png)

**Comment by asbjornu** [comment] 2021-01-19 21:07
@NameOfTheDragon, version 5.6.4 was just released. Can you please give it a new try?

**Comment by NameOfTheDragon** [comment] 2021-01-20 13:19
I saw that… and unfortunately it still doesn’t work for me.

I’ve been digging into it a bit and it looks like GenerateGitVersionInformationTask has a Language parameter that is expecting something like “C#” or “F#”. The Language property has a default value of “C#” but is also marked “[Required]” which seems to defeat the point of having a default value. Anyway, in my build logs, the error states that an invalid value of “en-US:en” is being passed. There seems to be a confusion somewhere between i18n language and programming language. I haven’t been able to trace it through any further than that.

Best regards,
Tim Long
