### ISSUE TITLE
Way to change tag on branch?

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#1018] opened 2016-08-25 07:01 UTC
Lets take GitVersion, we are working on master as our mainline. It is where we are focusing our effort and we are happy to accept anything in which we are happy meets the quality bar (we have good test coverage, so anything which makes sense and the tests pass).

So when we start some risky or breaking changes, we want to bump to the next major and tag as alpha or beta to get feedback. Often these changes involve structural changes so I prefer they happen on master rather than a release branch (because otherwise PR's keep coming into master). Then we branch off the previously released tag to a support branch if we need to release any fixes to it.

The other scenario is when using gitflow, using this feature to promote a release branch from beta to rc.

The config file approach is not really great, because we don't know _when_ it changes so semantically we don't know if it should clear the -beta.2 tag which was a few commits ago unless we actually read the config file for each commit to find out when that tag setting was added to that branch config. Sounds hard =/

Maybe something like: `+semver-tag: beta`, `+semver-tag: none/stable` etc.

Thoughts? Feel free to shoot me down :)

**Comment by JakeGinnivan** [comment] 2016-08-25 07:02
I am actually not sure how to go from beta release to stable on master right now.

**Comment by andreasohlund** [comment] 2016-08-29 10:05
>The other scenario is when using gitflow, using this feature to promote a release branch from beta to rc.

We have same situation now as well , bumping from `beta` => `rc`. I like the  `+semver-tag: rc` idea!

For now we changed GitVersionConfig to:

```
releases?[/-]:
    tag: rc
```

It would also be good to have different rules for "starting" tag depending on if the release is a major

releases?[/-][Major]:
    tag: beta  //all release branches for major should start as beta


releases?[/-][Minor|Patch]:
    tag: rc  //all release branches for Minor/patch should start as RC

**Comment by asbjornu** [comment] 2019-06-28 00:50
This seems like a duplicate of #740 to me. Closing.

**Closed by asbjornu** 2019-06-28 00:50 UTC
